export type CreateFieldType="text"|"textarea"|"date"|"datetime-local"|"number"|"select"|"department"|"user"|"criteria_version"|"indicator_assignment"|"fmea_model"|"checkbox";
export type CreateField={key:string;label:string;type:CreateFieldType;required?:boolean;placeholder?:string;options?:{value:string;label:string}[];wide?:boolean};
export type DomainCreateSpec={recordType:string;buttonLabel:string;intro:string;permissions:string[];commonOwner?:boolean;fields:CreateField[]};
const priority=[{value:"LOW",label:"Thấp"},{value:"NORMAL",label:"Bình thường"},{value:"HIGH",label:"Cao"},{value:"URGENT",label:"Khẩn"}];
const SPECS:Record<string,DomainCreateSpec>={
DIRECTIVE:{recordType:"DIRECTIVE",buttonLabel:"Tạo yêu cầu",intro:"Ghi nhận đúng nguồn, nội dung phải thực hiện, owner, hạn và sản phẩm mong đợi.",permissions:["directives.manage"],commonOwner:true,fields:[{key:"source_authority",label:"Cơ quan / nguồn yêu cầu",type:"text"},{key:"directive_type",label:"Loại yêu cầu",type:"text"},{key:"received_date",label:"Ngày tiếp nhận",type:"date"},{key:"implementation_due_date",label:"Hạn thực hiện",type:"date"},{key:"report_due_date",label:"Hạn báo cáo",type:"date"},{key:"priority",label:"Mức ưu tiên",type:"select",options:priority},{key:"summary",label:"Tóm tắt",type:"textarea",wide:true},{key:"requirements",label:"Nội dung phải thực hiện / sản phẩm",type:"textarea",wide:true}]},
REPORT:{recordType:"REPORT",buttonLabel:"Tạo nghĩa vụ báo cáo",intro:"Chỉ tạo từ nghĩa vụ có thật; chưa có hạn nguồn thì để trống, không tự suy diễn.",permissions:["reports.manage"],commonOwner:true,fields:[{key:"report_type",label:"Loại báo cáo",type:"text"},{key:"reporting_period",label:"Kỳ báo cáo",type:"text"},{key:"reporting_period_start",label:"Từ ngày",type:"date"},{key:"reporting_period_end",label:"Đến ngày",type:"date"},{key:"data_cutoff_date",label:"Ngày chốt dữ liệu",type:"date"},{key:"due_date",label:"Hạn nộp",type:"date"},{key:"recipient_name",label:"Nơi nhận",type:"text"},{key:"submission_method",label:"Phương thức gửi",type:"text"},{key:"notes",label:"Ghi chú / yêu cầu sản phẩm",type:"textarea",wide:true}]},
INSPECTION:{recordType:"INSPECTION",buttonLabel:"Tạo đợt tiếp đoàn",intro:"Inspection Mode sẽ dùng ngày đoàn làm mốc để sinh checklist/countdown khi đã có template cấu hình.",permissions:["inspections.manage","plans.manage"],commonOwner:true,fields:[{key:"inspection_type",label:"Loại kiểm tra / thẩm định",type:"text",required:true},{key:"authority",label:"Cơ quan / đoàn",type:"text"},{key:"visit_date",label:"Ngày đoàn đến",type:"date",required:true}]},
INDICATOR_MEASUREMENT:{recordType:"INDICATOR_MEASUREMENT",buttonLabel:"Nhập kỳ đo",intro:"Kỳ đo phải xuất phát từ chỉ số đã định nghĩa và phân công; không tạo chỉ số tự do từ màn hình này.",permissions:["indicators.enter","indicators.manage"],fields:[{key:"indicator_assignment_id",label:"Chỉ số / đơn vị được phân công",type:"indicator_assignment",required:true,wide:true},{key:"period_start",label:"Kỳ từ",type:"date",required:true},{key:"period_end",label:"Kỳ đến",type:"date",required:true},{key:"numerator_value",label:"Tử số",type:"number"},{key:"denominator_value",label:"Mẫu số",type:"number"},{key:"raw_value",label:"Giá trị thô / trực tiếp",type:"number"}]},
FINDING:{recordType:"FINDING",buttonLabel:"Tạo Finding",intro:"Giữ nguyên phát hiện ban đầu; khắc phục về sau được ghi bằng Action, Evidence và Recheck.",permissions:["findings.manage"],commonOwner:true,fields:[{key:"finding_type",label:"Nguồn / loại phát hiện",type:"text"},{key:"severity",label:"Mức độ",type:"text"},{key:"identified_at",label:"Thời điểm phát hiện",type:"datetime-local"},{key:"due_date",label:"Hạn khắc phục",type:"date"},{key:"description",label:"Mô tả phát hiện",type:"textarea",required:true,wide:true},{key:"immediate_action",label:"Khắc phục tức thời",type:"textarea",wide:true}]},
INCIDENT:{recordType:"INCIDENT",buttonLabel:"Báo cáo sự cố",intro:"Ghi nhận sự việc và xử trí ban đầu. Phân loại/RCA được QLCL xác minh sau, không yêu cầu người báo cáo tự kết luận nguyên nhân.",permissions:["incident.report","incident.triage"],fields:[{key:"report_type",label:"Hình thức báo cáo",type:"select",required:true,options:[{value:"VOLUNTARY",label:"Tự nguyện"},{value:"MANDATORY",label:"Bắt buộc"}]},{key:"incident_location_department_id",label:"Khoa/phòng nơi xảy ra",type:"department"},{key:"occurred_at",label:"Thời điểm xảy ra",type:"datetime-local"},{key:"detected_at",label:"Thời điểm phát hiện",type:"datetime-local"},{key:"incident_location_text",label:"Vị trí cụ thể",type:"text"},{key:"initial_description",label:"Mô tả sự cố",type:"textarea",required:true,wide:true},{key:"initial_harm_assessment",label:"Đánh giá ảnh hưởng ban đầu",type:"textarea",wide:true},{key:"initial_response_description",label:"Xử trí tức thời",type:"textarea",wide:true},{key:"reporter_identity_confidential",label:"Giữ kín danh tính người báo cáo",type:"checkbox"}]},
CAPA:{recordType:"CAPA",buttonLabel:"Tạo CAPA",intro:"CAPA chỉ dùng khi cần xử lý nguyên nhân hệ thống/lặp lại/nghiêm trọng và phải có đánh giá hiệu lực.",permissions:["capa.manage"],commonOwner:true,fields:[{key:"priority",label:"Ưu tiên",type:"select",options:priority},{key:"effectiveness_due_date",label:"Hạn đánh giá hiệu lực",type:"date"},{key:"approval_required",label:"Yêu cầu phê duyệt trước triển khai",type:"checkbox"},{key:"problem_statement",label:"Vấn đề cần CAPA",type:"textarea",required:true,wide:true},{key:"immediate_correction",label:"Khắc phục tức thời",type:"textarea",wide:true}]},
RISK:{recordType:"RISK",buttonLabel:"Ghi nhận rủi ro",intro:"Risk Register lưu sự kiện rủi ro, nguyên nhân, hậu quả, owner và lịch rà soát; chấm điểm là bước đánh giá tiếp theo.",permissions:["risk.manage"],commonOwner:true,fields:[{key:"risk_event",label:"Sự kiện rủi ro",type:"textarea",required:true,wide:true},{key:"cause_summary",label:"Nguyên nhân",type:"textarea",wide:true},{key:"potential_consequence",label:"Hậu quả tiềm tàng",type:"textarea",wide:true},{key:"process_name",label:"Quy trình liên quan",type:"text"},{key:"next_review_date",label:"Ngày rà soát tiếp",type:"date"},{key:"review_frequency",label:"Tần suất rà soát",type:"text"}]},
FMEA:{recordType:"FMEA",buttonLabel:"Tạo FMEA / HFMEA",intro:"Tạo phạm vi nghiên cứu trước; process step, failure mode và S/O/D được bổ sung trong workspace chi tiết.",permissions:["risk.manage"],commonOwner:true,fields:[{key:"method",label:"Phương pháp",type:"select",required:true,options:[{value:"FMEA",label:"FMEA"},{value:"HFMEA",label:"HFMEA"}]},{key:"process_name",label:"Quy trình",type:"text"},{key:"start_date",label:"Ngày bắt đầu",type:"date"},{key:"target_completion_date",label:"Hạn hoàn thành",type:"date"},{key:"scoring_model_version_id",label:"Mô hình chấm điểm",type:"fmea_model"},{key:"scope",label:"Phạm vi",type:"textarea",wide:true}]},
IMPROVEMENT_PROPOSAL:{recordType:"IMPROVEMENT_PROPOSAL",buttonLabel:"Tạo đề xuất",intro:"Đề xuất cần vấn đề và dữ liệu nền trước khi được sàng lọc thành đề án.",permissions:["projects.propose","projects.manage"],commonOwner:true,fields:[{key:"source_type",label:"Nguồn vấn đề",type:"text"},{key:"problem_description",label:"Vấn đề / thực trạng",type:"textarea",required:true,wide:true},{key:"reason_for_improvement",label:"Lý do cần cải tiến",type:"textarea",wide:true},{key:"existing_data_summary",label:"Dữ liệu nền hiện có",type:"textarea",wide:true},{key:"proposed_scope",label:"Phạm vi đề xuất",type:"textarea",wide:true}]},
IMPROVEMENT_PROJECT:{recordType:"IMPROVEMENT_PROJECT",buttonLabel:"Tạo đề án",intro:"Tạo hồ sơ đề án; SMART objective, chỉ số, PDSA và sustainability được quản lý ở bước tiếp theo.",permissions:["projects.manage"],commonOwner:true,fields:[{key:"start_date",label:"Ngày bắt đầu",type:"date"},{key:"target_end_date",label:"Hạn mục tiêu",type:"date"},{key:"problem_statement",label:"Vấn đề / baseline",type:"textarea",wide:true},{key:"scope_description",label:"Phạm vi",type:"textarea",wide:true}]},
ASSESSMENT:{recordType:"ASSESSMENT",buttonLabel:"Tạo đợt tự đánh giá",intro:"Đợt tự đánh giá phải dùng bộ tiêu chí đã PUBLISHED; không tạo hard-code tiêu chí trong giao diện.",permissions:["criteria.manage"],commonOwner:true,fields:[{key:"criteria_version_id",label:"Bộ tiêu chí / phiên bản",type:"criteria_version",required:true,wide:true},{key:"round_type",label:"Loại đợt",type:"text",required:true},{key:"start_date",label:"Ngày bắt đầu",type:"date"},{key:"submission_deadline",label:"Hạn đơn vị nộp",type:"date"},{key:"review_deadline",label:"Hạn rà soát",type:"date"},{key:"finalization_date",label:"Ngày dự kiến chốt",type:"date"}]},
EXTERNAL_ASSESSMENT:{recordType:"EXTERNAL_ASSESSMENT",buttonLabel:"Tạo đánh giá ngoài",intro:"Kết quả đoàn ngoài được lưu riêng để so với self-score, tuyệt đối không ghi đè lịch sử tự đánh giá.",permissions:["criteria.review","criteria.manage"],commonOwner:true,fields:[{key:"authority",label:"Cơ quan / đoàn đánh giá",type:"text",required:true},{key:"assessment_date",label:"Ngày đánh giá",type:"date"},{key:"criteria_version_id",label:"Bộ tiêu chí / phiên bản",type:"criteria_version",wide:true},{key:"notes",label:"Ghi chú / phạm vi",type:"textarea",wide:true}]},
AUDIT:{recordType:"AUDIT",buttonLabel:"Tạo Audit / Tracer",intro:"Tạo cuộc audit trước; scope, team, standard, session, Finding và tracer sẽ gắn vào hồ sơ này.",permissions:["audit.manage"],commonOwner:true,fields:[{key:"audit_type",label:"Loại Audit / Tracer",type:"text",required:true},{key:"start_date",label:"Ngày bắt đầu",type:"date"},{key:"end_date",label:"Ngày kết thúc",type:"date"},{key:"objective",label:"Mục tiêu",type:"textarea",wide:true}]},
SAFETY_ALERT:{recordType:"SAFETY_ALERT",buttonLabel:"Soạn bài học / cảnh báo",intro:"Chỉ phát hành sau rà soát; bản tạo mới ở trạng thái nháp.",permissions:["incident.investigate","incident.close"],fields:[{key:"summary",label:"Tóm tắt",type:"textarea",wide:true},{key:"lesson",label:"Bài học",type:"textarea",wide:true},{key:"recommendation",label:"Khuyến nghị áp dụng",type:"textarea",wide:true},{key:"expires_at",label:"Hết hiệu lực",type:"datetime-local"}]},
FEEDBACK:{recordType:"FEEDBACK",buttonLabel:"Ghi nhận phản ánh",intro:"Phản ánh là nguồn đầu vào; nếu xác minh có vấn đề hệ thống thì chuyển Finding/Action/CAPA.",permissions:["feedback.manage"],commonOwner:true,fields:[{key:"feedback_type",label:"Loại phản ánh",type:"text"},{key:"received_at",label:"Thời điểm tiếp nhận",type:"datetime-local"},{key:"source_channel",label:"Kênh tiếp nhận",type:"text"},{key:"subject",label:"Chủ đề",type:"text"},{key:"response_due_at",label:"Hạn phản hồi",type:"datetime-local"},{key:"description",label:"Nội dung",type:"textarea",required:true,wide:true}]}
};
export function getDomainCreateSpec(type:string){return SPECS[type]||null;}
export function canCreateDomainRecord(permissions:string[],type:string){const s=SPECS[type];return !!s&&s.permissions.some(p=>permissions.includes(p));}
