export type ModuleOperatingSpec={purpose:string;required:string[];evidence:string[];closeGate:string[];cadence?:string[];source:string[]};
const base=["Kế hoạch QLCL 2026 Final","TMMC-GQM-SOP01","Sổ tay QLCL cá nhân"];
const S:Record<string,ModuleOperatingSpec>={
DIRECTIVE:{purpose:"Chuyển chỉ đạo/yêu cầu thành việc có owner, hạn, sản phẩm và bằng chứng.",required:["Nguồn/số văn bản","Nội dung phải thực hiện","Đơn vị chủ trì/phối hợp","Owner","Hạn","Sản phẩm mong đợi"],evidence:["Văn bản nguồn","Sản phẩm đầu ra","Bằng chứng gửi/phê duyệt"],closeGate:["Đủ phạm vi","Có bằng chứng","Được xác nhận khi cần"],source:[...base,"BM-02","BM-05"]},
REPORT:{purpose:"Theo dõi nghĩa vụ báo cáo đến khi có bằng chứng đã gửi hoặc đã tiếp nhận.",required:["Tên báo cáo","Nơi nhận","Kỳ dữ liệu","Hạn nộp","Người lập/duyệt","Nguồn số liệu"],evidence:["Bản cuối","Email/cổng gửi","Xác nhận tiếp nhận nếu có"],closeGate:["Dữ liệu đã rà","Đã gửi đúng nơi nhận","Có bằng chứng gửi"],source:[...base,"BM-06"]},
INSPECTION:{purpose:"Tiếp đoàn theo countdown và theo dõi tồn tại sau kiểm tra đến recheck.",required:["Cơ quan/đoàn","Loại kiểm tra","Nguồn","Ngày đoàn","Phạm vi","Owner đầu mối","Đầu việc trước-trong-sau"],evidence:["Checklist chuẩn bị","Hồ sơ đã rà","Biên bản/kết luận","Minh chứng khắc phục"],closeGate:["Chuẩn bị hoàn tất","Kết luận đã ghi nhận","Tồn tại chuyển Finding/Action","Evidence + Recheck trước khi đóng"],cadence:["D-30 / D-14 / D-7 / D-3 / D-1 / D / D+1 / D+7 khi cấu hình"],source:[...base,"Kế hoạch tự kiểm tra 2026","BM-31"]},
INDICATOR_MEASUREMENT:{purpose:"Quản lý chỉ số từ định nghĩa, tử số/mẫu số đến xác minh, phân tích và hành động.",required:["Mã/tên","Mục đích","Định nghĩa","Tử số","Mẫu số","Nguồn dữ liệu","Đơn vị đo","Tần suất","Owner","Người kiểm tra","Baseline","Target","Warning","Action threshold"],evidence:["Dữ liệu gốc","Tử số/mẫu số/volume","Biểu nộp","Nhận xét xu hướng","Action/CAPA khi cần"],closeGate:["Dữ liệu hợp lệ","Nguồn truy xuất được","Có phân tích khi cảnh báo","Không sửa dữ liệu đã chốt không có giải trình"],cadence:["QMS: đơn vị nguồn gửi trước ngày 05, QLCL tổng hợp trước ngày 08 nếu không có lịch khác","Kiểm định dữ liệu độc lập tối thiểu 01 lần/năm"],source:[...base,"Quyết định 7051/QĐ-BYT","BM-22–24"]},
FINDING:{purpose:"Giữ nguyên phát hiện gốc và theo dõi đến Action, Evidence, Recheck.",required:["Nguồn","Yêu cầu/chuẩn","Bằng chứng","Mô tả","Mức độ","Owner","Hạn","Nhu cầu CAPA"],evidence:["Bằng chứng ban đầu","Action","Minh chứng khắc phục","Kết quả recheck"],closeGate:["Không sửa mất finding gốc","Action hoàn thành","Có minh chứng","Đã recheck","CAPA hiệu lực nếu có"],source:[...base,"BM-31"]},
INCIDENT:{purpose:"Tiếp nhận sự cố/near-miss, xử trí tức thời, xác minh, RCA phù hợp và phòng ngừa tái diễn.",required:["Thời điểm/nơi","Mô tả","Ảnh hưởng","Hành động tức thời","Mức độ","Đơn vị liên quan","Người xác minh","Nhu cầu RCA"],evidence:["Báo cáo sự cố","Hồ sơ xác minh","Dòng thời gian","RCA khi cần","Action/CAPA"],closeGate:["Đã bảo đảm an toàn tức thời","QLCL xác minh/phân loại","Nguyên nhân được xem xét","Action/CAPA đã theo dõi","Không dùng giảm số báo cáo làm KPI"],source:[...base,"Quy trình báo cáo sự cố Y khoa","BM-16","BM-17"]},
CAPA:{purpose:"Liên kết nguồn phát hiện với root cause, corrective/preventive action và kiểm tra hiệu lực.",required:["Nguồn/Record ID","Vấn đề","Ưu tiên","Root cause","CAPA Owner","Khắc phục","Phòng ngừa","Hạn","Bằng chứng","Thước đo hiệu lực"],evidence:["RCA","Bằng chứng Action","Theo dõi quá hạn","Phiếu hiệu lực"],closeGate:["Action bắt buộc xong","Đủ bằng chứng","Đã đánh giá hiệu lực","Người xác minh kết luận","Không đóng chỉ vì Action xong"],source:[...base,"BM-25","BM-26","BM-17"]},
RISK:{purpose:"Duy trì Risk Register có kiểm soát hiện hữu, risk owner và residual risk.",required:["Rủi ro","Nguyên nhân","Hậu quả","Kiểm soát hiện có","Severity","Likelihood","Mức rủi ro","Owner","Action","Hạn","Ngày rà soát"],evidence:["Bằng chứng kiểm soát","Action","Đánh giá lại","Chấp thuận residual risk"],closeGate:["Giữ lịch sử","Đánh giá residual risk","Có owner/ngày rà soát","Rủi ro cao có kiểm soát"],source:[...base,"BM-09"]},
FMEA:{purpose:"Phân tích rủi ro chủ động theo bước quy trình và failure mode, rồi re-score sau can thiệp.",required:["Quy trình/phạm vi","Sponsor","Nhóm FMEA","Go-live","Bước quy trình","Failure mode","Effect","Cause","Control","S-O-D","RPN/ưu tiên","Action owner/hạn"],evidence:["Phiếu phạm vi","Bảng FMEA","Bằng chứng thử nghiệm","Điểm sau can thiệp","Residual risk"],closeGate:["Failure mode gắn đúng bước","Action ưu tiên đã thử","Re-score","Residual risk chấp thuận","Severity cao không bị bỏ qua vì RPN thấp"],source:[...base,"BM-10–12"]},
IMPROVEMENT_PROPOSAL:{purpose:"Sàng lọc vấn đề chất lượng thành đề xuất khả thi trước khi lập đề án.",required:["Vấn đề","Nguồn phát hiện","Phạm vi","Đối tượng","Baseline","Lợi ích","Rào cản","Đơn vị đề xuất","Sponsor"],evidence:["Dữ liệu nền","Phiếu đề xuất","Kết quả thẩm định"],closeGate:["Vấn đề rõ","Có baseline","Đánh giá khả thi","Chỉ chuyển đề án sau phê duyệt"],source:[...base,"Phụ lục 4 Kế hoạch 2026"]},
IMPROVEMENT_PROJECT:{purpose:"Quản lý đề án từ baseline, SMART objective, driver đến PDSA, kết quả và sustain/spread.",required:["Tên/phạm vi","Baseline","Mục tiêu SMART","Outcome/process/balancing measures","Root cause/driver","Can thiệp","Owner","PDSA/mốc","Nguồn lực","Sustain/spread"],evidence:["Phiếu đăng ký","Đề án","Baseline","Root cause","Kế hoạch","Dữ liệu theo dõi","Báo cáo kết quả","Nghiệm thu"],closeGate:["Đã phê duyệt","Có chu trình cải tiến","Có trước-sau","Đánh giá kết quả/hạn chế","Quyết định duy trì/điều chỉnh/nhân rộng"],source:[...base,"BM-27","Phụ lục 4 Kế hoạch 2026"]},
ASSESSMENT:{purpose:"Tự đánh giá trung thực theo bộ tiêu chí, gắn kết luận với minh chứng và kiểm tra chéo.",required:["Bộ tiêu chí/phiên bản","Yêu cầu","Phạm vi","Đơn vị phụ trách","Mức tự đánh giá","Minh chứng","Nhận xét","Người rà soát","Finding/Action nếu thiếu"],evidence:["Tài liệu","Quan sát","Phỏng vấn","Dữ liệu điện tử","Phiếu chấm"],closeGate:["Không chấm khi thiếu bằng chứng","Không tự kế thừa N/A","Có kiểm tra chéo","Khoảng trống sinh Finding/Action","Giữ lịch sử điểm"],cadence:["Theo kế hoạch tự rà soát năm; chu kỳ 2026 hoàn thiện sang quý I/2027"],source:[...base,"Kế hoạch tự kiểm tra 2026"]},
EXTERNAL_ASSESSMENT:{purpose:"Lưu kết quả đoàn ngoài riêng biệt, so với self-score và chuyển chênh lệch thành Finding/Action/CAPA.",required:["Cơ quan/đoàn","Ngày","Bộ tiêu chí","Điểm ngoài","Tồn tại/kiến nghị","Self-score","Chênh lệch","Owner"],evidence:["Biên bản/kết luận","Bảng điểm","Kiến nghị","Bằng chứng khắc phục","Recheck"],closeGate:["Không ghi đè self-score lịch sử","Phân tích chênh lệch","Tồn tại chuyển Finding/Action","Recheck trước khi đóng"],source:[...base,"Kết quả kiểm tra SYT 2025","BM-31"]},
AUDIT:{purpose:"Quản lý audit/tracer từ scope, criteria, evidence đến Finding, CAPA và recheck.",required:["Tên audit","Phạm vi","Tiêu chí","Ngày","Trưởng đoàn/thành viên","Giới hạn","Bằng chứng","Good practice","Finding/mức độ"],evidence:["Kế hoạch/phiếu audit","Bằng chứng","Finding","CAPA/Action","Minh chứng khắc phục","Recheck"],closeGate:["Giữ finding gốc","Có Action/CAPA","Có recheck","Hiệu lực/người xác minh được ghi nhận"],source:[...base,"BM-31"]},
SAFETY_ALERT:{purpose:"Chuyển bài học thành cảnh báo có quyết định Adopt/Adapt và theo dõi áp dụng.",required:["Nguồn bài học","Nội dung cốt lõi","Đối tượng","Adopt/Adapt/Không áp dụng","Owner","Hạn","Cách kiểm tra"],evidence:["Bài học/cảnh báo","Bằng chứng truyền thông","Bằng chứng áp dụng","Kết quả"],closeGate:["Nội dung đã rà","Đơn vị đích quyết định áp dụng","Có kết quả nếu Adopt/Adapt"],source:[...base,"BM-44"]},
FEEDBACK:{purpose:"Dùng phản ánh/góp ý như nguồn phát hiện chất lượng, tách phản hồi khách hàng khỏi khắc phục hệ thống.",required:["Nguồn","Ngày tiếp nhận","Nội dung","Nhóm vấn đề","Đơn vị liên quan","Mức ảnh hưởng","Người phối hợp","Kết quả phản hồi"],evidence:["Phản ánh gốc","Xác minh","Phản hồi đã gửi","Finding/Action/CAPA nếu có vấn đề hệ thống"],closeGate:["Đã xác minh/phản hồi","Vấn đề hệ thống đã sinh Finding/Action/CAPA","Không đóng để làm mất luồng khắc phục"],source:[...base,"Khung QMS – phản hồi là đầu vào chất lượng"]}
};
export function getModuleOperatingSpec(recordTypes:string[]):ModuleOperatingSpec|null{return S[recordTypes[0]]||null;}
