import Link from "next/link";
import { redirect } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { TQM_CHART_CSS, TqmDonut, TqmHorizontalBars, TqmTrend } from "@/components/tqm-charts";
import { hasAnyPermission, requireUserContext } from "@/lib/auth";
import { isOperationallyHiddenStatus } from "@/lib/operational-record";
import { routeForRecord } from "@/lib/record-route";
import { createClient } from "@/lib/supabase/server";
import { getWorkYear } from "@/lib/work-year";

function levelTone(level:string){const v=String(level||"").toUpperCase();if(["EXTREME","CRITICAL","VERY_HIGH","HIGH","RED"].includes(v))return"danger";if(["MEDIUM","MODERATE","YELLOW","AMBER"].includes(v))return"warning";if(["LOW","GREEN"].includes(v))return"success";return"muted"}
function cellTone(levels:string[]){if(levels.some(x=>levelTone(x)==="danger"))return"danger";if(levels.some(x=>levelTone(x)==="warning"))return"warning";if(levels.some(x=>levelTone(x)==="success"))return"success";return"empty"}

export default async function RisksPage(){
 const {user}=await requireUserContext();if(!hasAnyPermission(user,["risk.view","risk.manage"]))redirect("/dashboard?forbidden=1");const year=await getWorkYear();const supabase=await createClient();
 const [recordsRes,risksRes,depsRes]=await Promise.all([
  supabase.from("records").select("id,record_code,title,lifecycle_status,owner_department_id,updated_at").eq("record_type","RISK").eq("work_year",year).order("updated_at",{ascending:false}),
  supabase.from("risks").select("id,record_id,workflow_status,next_review_date,owner_department_id,updated_at"),
  supabase.from("departments").select("id,name,short_name").eq("is_active",true)
 ]);
 const records=((recordsRes.data??[]) as any[]).filter(r=>!isOperationallyHiddenStatus(r.lifecycle_status));const recordMap=new Map(records.map(r=>[r.id,r]));const risks=((risksRes.data??[]) as any[]).filter(r=>recordMap.has(r.record_id));const riskIds=risks.map(r=>r.id);
 const assessmentsRes=riskIds.length?await supabase.from("risk_assessments").select("id,risk_id,assessment_date,assessment_type,severity,likelihood,calculated_score,calculated_level,created_at").in("risk_id",riskIds).order("assessment_date",{ascending:false}).order("created_at",{ascending:false}):{data:[],error:null};
 const latest=new Map<string,any>();for(const a of (assessmentsRes.data??[]) as any[])if(!latest.has(a.risk_id))latest.set(a.risk_id,a);
 const depMap=new Map((depsRes.data??[]).map((d:any)=>[d.id,d.short_name||d.name]));const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh"}).format(new Date());
 const rows=risks.map(r=>{const rec:any=recordMap.get(r.record_id);const a=latest.get(r.id);return{...r,...rec,assessment:a,department:String(depMap.get(r.owner_department_id||rec.owner_department_id)||"Chưa xác định"),route:routeForRecord("RISK",r.record_id)}});
 const assessed=rows.filter(r=>r.assessment),high=rows.filter(r=>levelTone(r.assessment?.calculated_level)==="danger").length,due=rows.filter(r=>r.next_review_date&&r.next_review_date<=today&&!['RETIRED'].includes(r.workflow_status)).length,accepted=rows.filter(r=>["RISK_ACCEPTED","MONITORING"].includes(r.workflow_status)).length;
 const maxS=Math.max(5,...rows.map(r=>Number(r.assessment?.severity||0))),maxL=Math.max(5,...rows.map(r=>Number(r.assessment?.likelihood||0)));
 const cells=new Map<string,{count:number;levels:string[]}>();for(const r of rows){const s=Number(r.assessment?.severity),l=Number(r.assessment?.likelihood);if(!s||!l)continue;const k=`${s}-${l}`;const c=cells.get(k)||{count:0,levels:[]};c.count++;c.levels.push(String(r.assessment.calculated_level||""));cells.set(k,c)}
 const levelCounts=new Map<string,number>();rows.forEach(r=>{const k=String(r.assessment?.calculated_level||"Chưa đánh giá");levelCounts.set(k,(levelCounts.get(k)||0)+1)});const levelSegments=Array.from(levelCounts.entries()).map(([label,value])=>({label,value,tone:levelTone(label)==="danger"?"red" as const:levelTone(label)==="warning"?"amber" as const:levelTone(label)==="success"?"green" as const:"slate" as const}));
 const depAgg=new Map<string,number>();rows.forEach(r=>depAgg.set(r.department,(depAgg.get(r.department)||0)+1));const depBars=Array.from(depAgg.entries()).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([label,value],i)=>({label,value,tone:(i<3?"brand":"blue") as any}));
 const months=Array.from({length:12},(_,i)=>({label:`T${i+1}`,value:0}));rows.forEach(r=>{const d=new Date(r.updated_at);if(!Number.isNaN(d.getTime()))months[d.getMonth()].value++});
 const firstError=[recordsRes,risksRes,depsRes,assessmentsRes].find((x:any)=>x.error)?.error;
 return <div className="page-stack risk-tqm">
  <style>{TQM_CHART_CSS+`.risk-tqm .kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.risk-tqm .kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:16px}.risk-tqm .kpi span{font-size:10px;color:#718187;font-weight:800;text-transform:uppercase}.risk-tqm .kpi strong{display:block;font-size:30px;margin-top:8px}.risk-tqm .grid{display:grid;grid-template-columns:1.15fr .85fr;gap:14px}.risk-tqm .head{padding:16px 18px 4px}.risk-tqm .head h2{margin:0;font-size:15px}.risk-tqm .head p{margin:4px 0 0;color:#74838a;font-size:11px}.risk-heatmap{padding:12px 18px 20px;overflow:auto}.risk-heatmap-grid{display:grid;grid-template-columns:52px repeat(${maxS},minmax(46px,1fr));gap:5px;min-width:${Math.max(430,maxS*58+60)}px}.risk-heatmap-grid .axis{display:grid;place-items:center;font-size:9px;font-weight:850;color:#718087}.risk-cell{min-height:54px;border-radius:10px;display:grid;place-items:center;align-content:center;border:1px solid #e6ecee}.risk-cell strong{font-size:17px}.risk-cell small{font-size:8px;margin-top:2px}.risk-cell.empty{background:#f6f8f9;color:#a0adb2}.risk-cell.success{background:#e8f7ef;color:#17643f;border-color:#c9ead8}.risk-cell.warning{background:#fff5df;color:#9a6512;border-color:#f2dfb5}.risk-cell.danger{background:#fff0f0;color:#b7353f;border-color:#f0c9cc}.risk-table td.level span{display:inline-flex;padding:4px 8px;border-radius:99px;font-size:9px;font-weight:850}.risk-table td.level .danger{background:#fff0f0;color:#b7353f}.risk-table td.level .warning{background:#fff5df;color:#9a6512}.risk-table td.level .success{background:#e8f7ef;color:#17643f}.risk-table td.level .muted{background:#f1f4f5;color:#65747a}@media(max-width:900px){.risk-tqm .grid{grid-template-columns:1fr}.risk-tqm .kpis{grid-template-columns:1fr 1fr}}`}</style>
  <PageHeader eyebrow={`QUẢN LÝ RỦI RO · ${year}`} title="Risk Register" description="TQM Risk Intelligence: nhận diện điểm nóng trên ma trận Severity × Likelihood, theo dõi rủi ro cao, lịch rà soát và residual risk từ dữ liệu đánh giá thực tế."/>
  {firstError?<div className="alert error">Một phần dữ liệu chưa tải được: {firstError.message}</div>:null}
  <section className="kpis"><article className="kpi"><span>Tổng rủi ro</span><strong>{rows.length}</strong></article><article className="kpi"><span>Đã đánh giá</span><strong>{assessed.length}</strong></article><article className="kpi"><span>Mức cao / rất cao</span><strong>{high}</strong></article><article className="kpi"><span>Đến hạn rà soát</span><strong>{due}</strong></article></section>
  <section className="grid"><article className="panel"><div className="head"><h2>Risk Heatmap · Severity × Likelihood</h2><p>Mỗi ô là số rủi ro có đánh giá hiện tại tại tổ hợp Severity và Likelihood. Màu lấy từ risk level thực tế, không tự đặt ngưỡng.</p></div><div className="risk-heatmap"><div className="risk-heatmap-grid"><div className="axis">L \ S</div>{Array.from({length:maxS},(_,i)=><div className="axis" key={`s${i+1}`}>S{i+1}</div>)}{Array.from({length:maxL},(_,ri)=>maxL-ri).flatMap(l=>[<div className="axis" key={`l${l}`}>L{l}</div>,...Array.from({length:maxS},(_,si)=>{const s=si+1,c=cells.get(`${s}-${l}`);return <div className={`risk-cell ${c?cellTone(c.levels):"empty"}`} key={`${s}-${l}`}><strong>{c?.count||0}</strong><small>S{s} × L{l}</small></div>})])}</div></div></article><article className="panel"><div className="head"><h2>Cơ cấu mức rủi ro</h2><p>{accepted} rủi ro đang ở trạng thái chấp nhận/theo dõi.</p></div><TqmDonut value={rows.length?Math.round(assessed.length/rows.length*100):0} label="Đã đánh giá" segments={levelSegments.length?levelSegments:[{label:"Chưa có dữ liệu",value:1,tone:"slate"}]}/></article></section>
  <section className="grid"><article className="panel"><div className="head"><h2>Rủi ro theo khoa/phòng</h2><p>Đơn vị có nhiều rủi ro đang được quản lý.</p></div><TqmHorizontalBars rows={depBars}/></article><article className="panel"><div className="head"><h2>Nhịp cập nhật Risk Register</h2><p>Số rủi ro có cập nhật theo tháng.</p></div><TqmTrend points={months} unit=""/></article></section>
  <section className="panel risk-table"><div className="head"><h2>Rủi ro cần theo dõi</h2><p>Drill-down để xem Action, minh chứng, residual risk và quyết định chấp nhận.</p></div><div className="table-wrap"><table><thead><tr><th>Rủi ro</th><th>Khoa/Phòng</th><th>S × L</th><th>Mức</th><th>Rà soát tiếp</th><th>Trạng thái</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.record_code} · {r.title}</strong></td><td>{r.department}</td><td>{r.assessment?`${r.assessment.severity} × ${r.assessment.likelihood}`:"—"}</td><td className="level"><span className={levelTone(r.assessment?.calculated_level)}>{r.assessment?.calculated_level||"Chưa đánh giá"}</span></td><td>{r.next_review_date||"—"}</td><td><StatusBadge status={r.workflow_status}/></td><td><Link className="button tertiary small" href={r.route}>Mở</Link></td></tr>)}</tbody></table></div></section>
 </div>
}