import Link from "next/link";
import { redirect } from "next/navigation";
import { CsvDownloadButton } from "@/components/csv-download-button";
import { DomainCreateClient } from "@/components/domain-create-client";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { TQM_CHART_CSS, TqmDonut, TqmHorizontalBars, TqmTrend } from "@/components/tqm-charts";
import { hasAnyPermission, requireUserContext } from "@/lib/auth";
import { hcmMonthNumber } from "@/lib/hcm-date";
import { isOperationallyHiddenStatus } from "@/lib/operational-record";
import { routeForRecord } from "@/lib/record-route";
import { createClient } from "@/lib/supabase/server";
import { tqmCsvFileName } from "@/lib/tqm-csv";
import { getWorkYear } from "@/lib/work-year";

const REVIEW_LABEL:Record<string,string>={EFFECTIVE:"Có hiệu lực",PARTIALLY_EFFECTIVE:"Hiệu lực một phần",INEFFECTIVE:"Không hiệu lực"};
function reviewTone(v:string){return v==="EFFECTIVE"?"green" as const:v==="PARTIALLY_EFFECTIVE"?"amber" as const:v==="INEFFECTIVE"?"red" as const:"slate" as const}
function workflowLabel(value:string){return String(value||"").replaceAll("_"," ")}
function isClosed(x:any){return ["EFFECTIVE","CLOSED"].includes(String(x.workflow_status||""))}
function isOverdue(x:any,today:string){return !!x.effectiveness_due_date&&x.effectiveness_due_date<today&&!isClosed(x)}
function actionLabel(x:any,today:string){if(isOverdue(x,today))return"Đánh giá hiệu lực đã quá hạn";if(x.workflow_status==="EFFECTIVENESS_REVIEW")return"Thực hiện đánh giá hiệu lực";if(x.workflow_status==="ROOT_CAUSE_ANALYSIS")return"Hoàn tất RCA và thiết kế Action";if(x.workflow_status==="IN_PROGRESS")return"Theo dõi Corrective + Preventive";if(x.workflow_status==="PENDING_APPROVAL")return"Chờ phê duyệt CAPA";if(x.workflow_status==="DRAFT")return"Khởi động CAPA";if(x.workflow_status==="EFFECTIVE")return"Đủ gate để đóng CAPA";return"Theo dõi hồ sơ"}
function actionRank(x:any,today:string){if(isOverdue(x,today))return 0;if(x.workflow_status==="EFFECTIVENESS_REVIEW")return 1;if(x.workflow_status==="ROOT_CAUSE_ANALYSIS")return 2;if(x.workflow_status==="IN_PROGRESS")return 3;if(x.workflow_status==="PENDING_APPROVAL")return 4;if(x.workflow_status==="DRAFT")return 5;if(x.workflow_status==="EFFECTIVE")return 6;return 7}

export default async function CapaPage({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}){
 const {user}=await requireUserContext();if(!hasAnyPermission(user,["capa.view","capa.manage"]))redirect("/dashboard?forbidden=1");const canCreate=hasAnyPermission(user,["capa.manage"]);const year=await getWorkYear();const query=await searchParams;const qRaw=String(query.q||"").trim();const q=qRaw.toLocaleLowerCase("vi");const status=String(query.status||"").trim();const supabase=await createClient();
 const [recordsRes,capasRes,depsRes]=await Promise.all([
  supabase.from("records").select("id,record_code,title,lifecycle_status,owner_department_id,updated_at").eq("record_type","CAPA").eq("work_year",year).order("updated_at",{ascending:false}),
  supabase.from("capas").select("id,record_id,workflow_status,effectiveness_due_date,priority,lead_department_id,updated_at"),
  supabase.from("departments").select("id,name,short_name").eq("is_active",true)
 ]);
 const records=((recordsRes.data??[]) as any[]).filter(r=>!isOperationallyHiddenStatus(r.lifecycle_status));const recordMap=new Map(records.map(r=>[r.id,r]));const capas=((capasRes.data??[]) as any[]).filter(c=>recordMap.has(c.record_id));const ids=capas.map(c=>c.id);
 const reviewsRes=ids.length?await supabase.from("capa_effectiveness_reviews").select("id,capa_id,review_no,actual_review_date,result,created_at").in("capa_id",ids).order("review_no",{ascending:false}):{data:[],error:null};const latest=new Map<string,any>();for(const r of (reviewsRes.data??[]) as any[])if(!latest.has(r.capa_id))latest.set(r.capa_id,r);
 const depMap=new Map((depsRes.data??[]).map((d:any)=>[d.id,d.short_name||d.name]));const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh"}).format(new Date());
 const allRows=capas.map(c=>{const rec:any=recordMap.get(c.record_id);return{...c,...rec,review:latest.get(c.id),department:String(depMap.get(c.lead_department_id||rec.owner_department_id)||"Chưa xác định"),route:routeForRecord("CAPA",c.record_id)}});
 const statusOptions=Array.from(new Set(allRows.map(x=>String(x.workflow_status||"")).filter(Boolean))).sort();
 const rows=allRows.filter(x=>{const text=`${x.record_code} ${x.title} ${x.department} ${x.priority||""} ${x.review?.result||""}`.toLocaleLowerCase("vi");return(!q||text.includes(q))&&(!status||x.workflow_status===status)});
 const filteredIds=new Set(rows.map(x=>x.id));const filteredReviews=((reviewsRes.data??[]) as any[]).filter(r=>filteredIds.has(r.capa_id));
 const open=rows.filter(x=>x.workflow_status!=="CLOSED").length,reviewing=rows.filter(x=>x.workflow_status==="EFFECTIVENESS_REVIEW").length,rca=rows.filter(x=>x.workflow_status==="ROOT_CAUSE_ANALYSIS").length,inProgress=rows.filter(x=>x.workflow_status==="IN_PROGRESS").length,effective=rows.filter(x=>x.review?.result==="EFFECTIVE"||isClosed(x)).length,overdue=rows.filter(x=>isOverdue(x,today)).length,effectivePct=rows.length?Math.round(effective/rows.length*100):0;
 const actionable=[...rows].filter(x=>x.workflow_status!=="CLOSED").sort((a,b)=>actionRank(a,today)-actionRank(b,today)||String(a.effectiveness_due_date||"9999").localeCompare(String(b.effectiveness_due_date||"9999")));
 const reviewMap=new Map<string,number>();rows.forEach(x=>{const k=String(x.review?.result||"NOT_REVIEWED");reviewMap.set(k,(reviewMap.get(k)||0)+1)});const reviewSegments=Array.from(reviewMap.entries()).map(([k,value])=>({label:k==="NOT_REVIEWED"?"Chưa đánh giá":REVIEW_LABEL[k]||k,value,tone:k==="NOT_REVIEWED"?"slate" as const:reviewTone(k)}));
 const stageMap=new Map<string,number>();rows.forEach(x=>stageMap.set(x.workflow_status,(stageMap.get(x.workflow_status)||0)+1));const stageBars=Array.from(stageMap.entries()).sort((a,b)=>b[1]-a[1]).map(([label,value],i)=>({label:workflowLabel(label),value,tone:(i<2?"brand":"blue") as any}));
 const depAgg=new Map<string,number>();rows.forEach(x=>depAgg.set(x.department,(depAgg.get(x.department)||0)+1));const depBars=Array.from(depAgg.entries()).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([label,value],i)=>({label,value,tone:(i<3?"brand":"blue") as any}));
 const months=Array.from({length:12},(_,i)=>({label:`T${i+1}`,value:0}));for(const r of filteredReviews){const month=hcmMonthNumber(r.actual_review_date||r.created_at);if(month)months[month-1].value++}
 const firstError=[recordsRes,capasRes,depsRes,reviewsRes].find((x:any)=>x.error)?.error;
 const exportRows=rows.map((x,index)=>[index+1,x.record_code,x.title,x.department,x.priority||"—",workflowLabel(x.workflow_status),x.effectiveness_due_date||"",x.review?REVIEW_LABEL[x.review.result]||x.review.result:"Chưa đánh giá",x.review?.actual_review_date||""]);
 return <div className="page-stack capa-tqm">
  <style>{TQM_CHART_CSS+`.capa-tqm .kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.capa-tqm .kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:16px}.capa-tqm .kpi.danger{border-color:#efc6c6;background:#fffafa}.capa-tqm .kpi.warning{border-color:#f3d7a5;background:#fffdf7}.capa-tqm .kpi span{font-size:10px;color:#718187;font-weight:800;text-transform:uppercase}.capa-tqm .kpi strong{display:block;font-size:30px;margin-top:8px}.capa-tqm .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.capa-tqm .head{padding:16px 18px 4px}.capa-tqm .head h2{margin:0;font-size:15px}.capa-tqm .head p{margin:4px 0 0;color:#74838a;font-size:11px}.capa-filter{display:grid;grid-template-columns:minmax(220px,1fr) 220px auto auto;gap:9px;padding:14px 16px 6px}.capa-filter-summary{padding:0 16px 10px;color:#74838a;font-size:10px}.capa-list{display:grid;gap:8px;padding:8px 16px 16px}.capa-row{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(150px,.8fr) 120px 120px auto;gap:10px;align-items:center;border:1px solid #e4eaec;border-radius:13px;padding:12px}.capa-row.overdue{border-color:#efc6c6;background:#fffafa}.capa-next{font-weight:800;color:#334155}.capa-row.overdue .capa-next{color:#b42318}.capa-due{font-size:12px}.capa-due.overdue{color:#b42318;font-weight:800}.capa-analytics>summary{cursor:pointer;padding:16px 18px;font-weight:850;color:#334155}.capa-analytics[open]>summary{border-bottom:1px solid #e7eef0}.capa-analytics-body{display:grid;gap:14px;padding:14px}@media(max-width:900px){.capa-tqm .grid{grid-template-columns:1fr}.capa-tqm .kpis{grid-template-columns:1fr 1fr}.capa-filter{grid-template-columns:1fr 1fr}.capa-filter .button{width:100%}.capa-row{grid-template-columns:1fr 1fr}.capa-row>div:first-child,.capa-row>div:nth-child(2){grid-column:1/-1}}@media(max-width:560px){.capa-filter,.capa-tqm .kpis{grid-template-columns:1fr}}`}</style>
  <PageHeader eyebrow={`KHẮC PHỤC & CAPA · ${year}`} title="CAPA" description="Điều hành CAPA theo việc cần xử lý trước: quá hạn, đánh giá hiệu lực, RCA và Action; phân tích TQM chuyên sâu đặt phía sau." actions={canCreate?<DomainCreateClient recordType="CAPA" workYear={year}/>:null}/>
  {firstError?<div className="alert error">Một phần dữ liệu chưa tải được: {firstError.message}</div>:null}
  <section className="panel"><form className="capa-filter" method="get"><input name="q" defaultValue={qRaw} placeholder="Tìm mã, CAPA, khoa/phòng, ưu tiên..."/><select name="status" defaultValue={status}><option value="">Tất cả trạng thái</option>{statusOptions.map(value=><option value={value} key={value}>{workflowLabel(value)}</option>)}</select><button className="button secondary" type="submit">Áp dụng lọc</button>{qRaw||status?<Link className="button tertiary" href="/capa">Xóa lọc</Link>:<span/>}</form><div className="capa-filter-summary">Đang hiển thị <strong>{rows.length}</strong> / {allRows.length} CAPA trong năm {year}. Danh sách ưu tiên, KPI, phân tích và file xuất cùng dùng bộ lọc này.</div><div style={{padding:"0 16px 14px"}}><CsvDownloadButton filename={tqmCsvFileName("capa-theo-doi",year)} headers={["STT","Mã CAPA","Tên CAPA","Khoa/Phòng","Ưu tiên","Trạng thái","Hạn đánh giá hiệu lực","Kết quả hiệu lực gần nhất","Ngày đánh giá gần nhất"]} rows={exportRows} metadata={[["Module","CAPA"],["Năm",year],["Từ khóa",qRaw||"Tất cả"],["Trạng thái",status?workflowLabel(status):"Tất cả"],["Số hồ sơ xuất",rows.length]]}/></div></section>
  <section className="kpis"><article className={`kpi ${overdue?"danger":""}`}><span>Quá hạn đánh giá</span><strong>{overdue}</strong></article><article className={`kpi ${reviewing?"warning":""}`}><span>Chờ đánh giá hiệu lực</span><strong>{reviewing}</strong></article><article className="kpi"><span>Đang RCA</span><strong>{rca}</strong></article><article className="kpi"><span>Đang triển khai Action</span><strong>{inProgress}</strong></article></section>
  <section className="panel"><div className="head"><h2>CAPA CẦN XỬ LÝ</h2><p>Danh sách được ưu tiên theo: quá hạn → đánh giá hiệu lực → RCA → triển khai Action → phê duyệt/khởi động.</p></div><div className="capa-list">{actionable.map(x=>{const overdueNow=isOverdue(x,today);return <div className={`capa-row ${overdueNow?"overdue":""}`} key={x.id}><div><strong>{x.record_code} · {x.title}</strong><small className="subline">{x.department} · Ưu tiên {x.priority||"—"}</small></div><div><span className="capa-next">{actionLabel(x,today)}</span><small className="subline">Việc tiếp theo</small></div><div className={`capa-due ${overdueNow?"overdue":""}`}>{x.effectiveness_due_date||"—"}<small className="subline">Hạn hiệu lực</small></div><div><StatusBadge status={x.workflow_status}/></div><Link className="button tertiary small" href={x.route}>Xử lý</Link></div>})}{!actionable.length?<div className="empty-state">Không có CAPA đang mở phù hợp bộ lọc.</div>:null}</div></section>
  <details className="panel capa-analytics"><summary>Báo cáo và phân tích CAPA chuyên sâu · {open} CAPA đang mở · {effectivePct}% đã xác nhận hiệu lực</summary><div className="capa-analytics-body"><section className="grid"><article className="panel"><div className="head"><h2>Kết quả hiệu lực CAPA</h2><p>Tỷ trọng kết luận đánh giá hiệu lực gần nhất của từng CAPA trong bộ lọc hiện tại.</p></div><TqmDonut value={effectivePct} label="Có hiệu lực" segments={reviewSegments.length?reviewSegments:[{label:"Chưa có dữ liệu",value:1,tone:"slate"}]}/></article><article className="panel"><div className="head"><h2>CAPA theo giai đoạn</h2><p>Cho biết hồ sơ đang nghẽn ở RCA, triển khai hay đánh giá hiệu lực.</p></div><TqmHorizontalBars rows={stageBars}/></article></section><section className="grid"><article className="panel"><div className="head"><h2>CAPA theo khoa/phòng</h2><p>Khối lượng CAPA theo đơn vị đầu mối trong bộ lọc hiện tại.</p></div><TqmHorizontalBars rows={depBars}/></article><article className="panel"><div className="head"><h2>Nhịp đánh giá hiệu lực</h2><p>Số lượt effectiveness review theo tháng của các CAPA đang lọc, quy đổi theo múi giờ Việt Nam.</p></div><TqmTrend points={months} unit=""/></article></section></div></details>
 </div>
}
