import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { TQM_CHART_CSS, TqmDonut, TqmGantt, TqmHorizontalBars, TqmTrend } from "@/components/tqm-charts";
import { TqmSmartCommandCenter } from "@/components/tqm-smart-command-center";
import { TqmProcessMap } from "@/components/tqm-process-map";
import { TqmScorecard } from "@/components/tqm-scorecard";
import { TqmInterventionLoop } from "@/components/tqm-intervention-loop";
import { TqmPriorityBoard } from "@/components/tqm-priority-board";
import { requireUserContext } from "@/lib/auth";
import { buildIndicatorKpi, buildProjectActionKpi, isDueOnOrBeforeToday } from "@/lib/dashboard-kpi";
import { createClient } from "@/lib/supabase/server";
import { getWorkYear } from "@/lib/work-year";

const CLOSED = new Set(["CANCELLED","ARCHIVED","INACTIVE","RETIRED"]);
function todayHcm(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh"}).format(new Date())}

export default async function DashboardPage(){
 await requireUserContext(); const year=await getWorkYear(); const supabase=await createClient(); const today=todayHcm();
 const [recordsRes,programProgressRes,departmentsRes,indicatorsRes,monitoringRes,projectsRes,findingsRes,capasRes,incidentsRes]=await Promise.all([
  supabase.from("records").select("id,record_type,record_code,title,work_year,lifecycle_status,owner_department_id,owner_user_id").eq("work_year",year),
  supabase.from("vw_program_progress").select("program_id,record_id,record_code,title,work_year,required_actions,completed_actions,progress_pct,overdue_actions").eq("work_year",year),
  supabase.from("departments").select("id,name,short_name").eq("is_active",true).order("name"),
  supabase.from("indicator_measurements").select("id,record_id,workflow_status,result_level,period_end"),
  supabase.from("monitoring_rounds").select("id,record_id,scheduled_date,target_department_id,workflow_status").eq("work_year",year).neq("workflow_status","CANCELLED"),
  supabase.from("improvement_projects").select("id,record_id,workflow_status,start_date,target_end_date,actual_end_date,problem_statement"),
  supabase.from("findings").select("id,record_id,workflow_status,due_date,severity"),
  supabase.from("capas").select("id,record_id,workflow_status,effectiveness_due_date,priority"),
  supabase.from("incidents").select("id,record_id,workflow_status,serious_event_flag,reported_at,harm_status")
 ]);
 const all=[recordsRes,programProgressRes,departmentsRes,indicatorsRes,monitoringRes,projectsRes,findingsRes,capasRes,incidentsRes]; const firstError=all.find((x:any)=>x.error)?.error;
 const records=((recordsRes.data??[]) as any[]).filter((r:any)=>!CLOSED.has(r.lifecycle_status)); const recordMap=new Map(records.map((r:any)=>[r.id,r])); const recordIds=new Set(records.map((r:any)=>r.id)); const depMap=new Map(((departmentsRes.data??[]) as any[]).map((d:any)=>[d.id,d.short_name||d.name]));

 const plans=((programProgressRes.data??[]) as any[]).filter((x:any)=>recordIds.has(x.record_id)); const planReq=plans.reduce((s:any,x:any)=>s+Number(x.required_actions||0),0); const planDone=plans.reduce((s:any,x:any)=>s+Number(x.completed_actions||0),0); const planOverdue=plans.reduce((s:any,x:any)=>s+Number(x.overdue_actions||0),0); const planPct=planReq?Math.round(planDone/planReq*100):(plans.length?Math.round(plans.reduce((s:any,x:any)=>s+Number(x.progress_pct||0),0)/plans.length):0);

 const indicators=((indicatorsRes.data??[]) as any[]).filter((x:any)=>recordIds.has(x.record_id)); const indicatorKpi=buildIndicatorKpi(indicators); const evaluableIndicators=indicatorKpi.evaluable; const inTarget=indicatorKpi.inTarget; const outTarget=indicatorKpi.outTarget; const indicatorPct=indicatorKpi.percentage; const indicatorTrend=indicatorKpi.trend;

 const monitoring=((monitoringRes.data??[]) as any[]).filter((x:any)=>recordIds.has(x.record_id)); const roundIds=monitoring.map((x:any)=>x.id); const responsesRes=roundIds.length?await supabase.from("checklist_responses").select("monitoring_round_id,result_status").in("monitoring_round_id",roundIds):{data:[] as any[],error:null}; const responseMap=new Map<string,{pass:number;fail:number}>(); for(const x of (responsesRes.data??[]) as any[]){const a=responseMap.get(x.monitoring_round_id)??{pass:0,fail:0};if(String(x.result_status).toUpperCase()==="PASS")a.pass++;if(String(x.result_status).toUpperCase()==="FAIL")a.fail++;responseMap.set(x.monitoring_round_id,a)}
 let monitorPass=0,monitorFail=0; const deptAgg=new Map<string,{pass:number;fail:number}>(); for(const r of monitoring){const a=responseMap.get(r.id)??{pass:0,fail:0};monitorPass+=a.pass;monitorFail+=a.fail;const key=r.target_department_id||"none";const d=deptAgg.get(key)??{pass:0,fail:0};d.pass+=a.pass;d.fail+=a.fail;deptAgg.set(key,d)} const monitoringPct=(monitorPass+monitorFail)?Math.round(monitorPass/(monitorPass+monitorFail)*100):0;
 const deptBars=Array.from(deptAgg.entries()).map(([id,a])=>{const n=a.pass+a.fail;const pct=n?Math.round(a.pass/n*100):0;return{label:String(depMap.get(id)||"Chưa xác định"),value:pct,tone:pct>=90?"green" as const:pct>=75?"blue" as const:pct>=60?"amber" as const:"red" as const,caption:`${n} mục đã chấm`}}).filter((x)=>x.caption!=="0 mục đã chấm").sort((a,b)=>a.value-b.value).slice(0,10);

 const projects=((projectsRes.data??[]) as any[]).filter((x:any)=>recordIds.has(x.record_id)); const projectRecordIds=projects.map((x:any)=>x.record_id); const linksRes=projectRecordIds.length?await supabase.from("record_links").select("source_record_id,target_record_id").in("source_record_id",projectRecordIds).eq("relation_type","HAS_ACTION"):{data:[] as any[],error:null}; const links=(linksRes.data??[]) as any[]; const actionIds=Array.from(new Set(links.map((x:any)=>x.target_record_id).filter(Boolean))); const projectActionsRes=actionIds.length?await supabase.from("actions").select("record_id,workflow_status,due_date").in("record_id",actionIds):{data:[] as any[],error:null}; const actionMap=new Map(((projectActionsRes.data??[]) as any[]).map((x:any)=>[x.record_id,x])); const projectActions=new Map<string,any[]>(); for(const l of links){const a=actionMap.get(l.target_record_id);if(!a)continue;const arr=projectActions.get(l.source_record_id)??[];arr.push(a);projectActions.set(l.source_record_id,arr)}
 const projectRows=projects.map((p:any)=>{const r:any=recordMap.get(p.record_id);const acts=(projectActions.get(p.record_id)??[]).filter((a:any)=>!["CANCELLED","NOT_APPLICABLE"].includes(String(a.workflow_status)));const done=acts.filter((a:any)=>a.workflow_status==="COMPLETED").length;const progress=acts.length?Math.round(done/acts.length*100):0;const overdue=acts.filter((a:any)=>a.workflow_status!=="COMPLETED"&&a.due_date&&a.due_date<today).length;return{...p,title:r?.title||"Đề án cải tiến",record_code:r?.record_code||"—",actions:acts.length,completed:done,progress,overdue}}); const projectKpi=buildProjectActionKpi(projectRows); const projectPct=projectKpi.percentage;
 const ganttRows=projectRows.filter((x:any)=>x.start_date&&x.target_end_date).map((x:any)=>({label:x.title,start:x.start_date,end:x.target_end_date,progress:x.progress,tone:x.overdue?"red" as const:x.progress>=75?"green" as const:"blue" as const}));

 const findings=((findingsRes.data??[]) as any[]).filter((x:any)=>recordIds.has(x.record_id)&&!["CLOSED","CANCELLED"].includes(String(x.workflow_status))); const capas=((capasRes.data??[]) as any[]).filter((x:any)=>recordIds.has(x.record_id)&&!["CLOSED","CANCELLED","EFFECTIVE"].includes(String(x.workflow_status))); const incidents=((incidentsRes.data??[]) as any[]).filter((x:any)=>recordIds.has(x.record_id)&&!["CLOSED","CANCELLED","REJECTED"].includes(String(x.workflow_status))); const serious=incidents.filter((x:any)=>x.serious_event_flag).length; const overdueFindings=findings.filter((x:any)=>x.due_date&&x.due_date<today).length; const capaDue=capas.filter((x:any)=>String(x.workflow_status)==="EFFECTIVENESS_REVIEW"||isDueOnOrBeforeToday(x.effectiveness_due_date,today)).length;
 const hotspots=[{label:"Finding quá hạn",value:overdueFindings,href:"/findings",tone:"red" as const},{label:"CAPA đến hạn đánh giá",value:capaDue,href:"/capa",tone:"amber" as const},{label:"Sự cố nghiêm trọng đang mở",value:serious,href:"/incidents",tone:"red" as const},{label:"Chỉ số ngoài mục tiêu",value:outTarget,href:"/indicators",tone:"amber" as const}].sort((a,b)=>b.value-a.value);
 const hasPrioritySignals=serious>0||overdueFindings>0||capaDue>0||outTarget>0||planOverdue>0;

 return <div className="page-stack tqm-dashboard">
  <style>{TQM_CHART_CSS+`.tqm-dashboard .hero{padding:25px 27px;border-radius:24px;color:#fff;background:radial-gradient(circle at 85% 10%,rgba(159,196,235,.25),transparent 18rem),linear-gradient(135deg,#102848,#1d3f73 45%,#3f6fa8);box-shadow:0 22px 52px rgba(16,40,72,.2)}.tqm-dashboard .hero .eyebrow{color:#c6daf2}.tqm-dashboard .hero h2{font-size:28px;margin:7px 0}.tqm-dashboard .hero p{margin:0;color:#ffffffcc;max-width:850px;line-height:1.6}.tqm-dashboard .kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px}.tqm-dashboard .kpi{background:#fff;border:1px solid #e1e9ec;border-radius:18px;padding:17px;box-shadow:0 8px 24px rgba(20,48,58,.05)}.tqm-dashboard .kpi span{font-size:10px;color:#718187;text-transform:uppercase;font-weight:800}.tqm-dashboard .kpi strong{display:block;font-size:32px;margin-top:8px}.tqm-dashboard .kpi small{display:block;color:#7d8c92;font-size:10px;margin-top:5px}.tqm-dashboard .grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px}.tqm-dashboard .grid3{display:grid;grid-template-columns:1.15fr .85fr;gap:14px}.tqm-dashboard .head{padding:17px 18px 6px}.tqm-dashboard .head h2{margin:0;font-size:15px}.tqm-dashboard .head p{margin:4px 0 0;color:#74838a;font-size:11px}.tqm-dashboard .hotspots{display:grid;gap:8px;padding:8px 16px 16px}.tqm-dashboard .hotspot{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:13px;border-radius:13px;border:1px solid #e4eaec;background:#fbfdfd}.tqm-dashboard .hotspot strong{font-size:12px}.tqm-dashboard .hotspot b{font-size:22px}.tqm-dashboard .hotspot.red b{color:#c84350}.tqm-dashboard .hotspot.amber b{color:#b86f1a}.tqm-dashboard .quick{display:flex;gap:8px;flex-wrap:wrap;padding:0 16px 16px}@media(max-width:920px){.tqm-dashboard .grid2,.tqm-dashboard .grid3{grid-template-columns:1fr}.tqm-dashboard .kpis{grid-template-columns:1fr 1fr}}`}</style>
  <PageHeader eyebrow={`TQM EXECUTIVE DASHBOARD · ${year}`} title="Bức tranh chất lượng toàn viện" description="Dashboard phân tích để nhìn mục tiêu, quá trình, kết quả và điểm cần cải tiến. Công việc cá nhân được tách sang Việc của tôi." />
  {firstError?<div className="alert error">Một phần dữ liệu chưa tải được: {firstError.message}</div>:null}
  <section className="hero"><div className="eyebrow">TỔNG QUAN TQM</div><h2>{hasPrioritySignals?"Có tín hiệu cần ưu tiên điều hành":"Chưa ghi nhận tín hiệu ưu tiên trên các chỉ số theo dõi"}</h2><p>Kế hoạch năm đạt {planPct}%, chỉ số chất lượng đạt mục tiêu {indicatorPct}%, giám sát đạt {monitoringPct}% và tỷ lệ Action hoàn thành của đề án cải tiến là {projectPct}%.</p></section>
  <section className="kpis"><article className="kpi"><span>Hoàn thành kế hoạch năm</span><strong>{planPct}%</strong><small>{planDone}/{planReq} Action · {planOverdue} quá hạn</small></article><article className="kpi"><span>Chỉ số đạt mục tiêu</span><strong>{indicatorPct}%</strong><small>{inTarget}/{evaluableIndicators.length} kỳ VERIFIED/LOCKED có kết luận</small></article><article className="kpi"><span>Kết quả giám sát đạt</span><strong>{monitoringPct}%</strong><small>{monitorPass}/{monitorPass+monitorFail} mục đã chấm</small></article><article className="kpi"><span>Action đề án cải tiến</span><strong>{projectPct}%</strong><small>{projectKpi.completed}/{projectKpi.actions} Action · {projectRows.length} đề án</small></article></section>
  <TqmSmartCommandCenter year={year} />
  <TqmProcessMap planPct={planPct} indicatorPct={indicatorPct} monitoringPct={monitoringPct} openFindings={findings.length} capaDue={capaDue} projectPct={projectPct} />
  <TqmScorecard planPct={planPct} indicatorPct={indicatorPct} monitoringPct={monitoringPct} projectPct={projectPct} seriousIncidents={serious} overdueFindings={overdueFindings} />
  <TqmInterventionLoop openFindings={findings.length} overdueFindings={overdueFindings} capaDue={capaDue} projectPct={projectPct} />
  <TqmPriorityBoard serious={serious} overdueFindings={overdueFindings} capaDue={capaDue} outTarget={outTarget} planOverdue={planOverdue} />
  <section className="grid3"><article className="panel"><div className="head"><h2>Tiến độ kế hoạch chất lượng năm</h2><p>Từ Action thực tế của các kế hoạch.</p></div><TqmDonut value={planPct} label="Hoàn thành" segments={[{label:"Đã hoàn thành",value:planDone,tone:"brand"},{label:"Còn lại",value:Math.max(0,planReq-planDone),tone:"blue"},{label:"Quá hạn",value:planOverdue,tone:"red"}]}/></article><article className="panel"><div className="head"><h2>Điểm nóng cần chú ý</h2><p>Chỉ giữ các vấn đề quản trị cấp bệnh viện.</p></div><div className="hotspots">{hotspots.map((x)=><Link href={x.href} key={x.label} className={`hotspot ${x.tone}`}><strong>{x.label}</strong><b>{x.value}</b></Link>)}</div><div className="quick"><Link className="button secondary" href="/plans">Kế hoạch năm</Link><Link className="button secondary" href="/monitoring">Giám sát</Link><Link className="button secondary" href="/improvement/projects">Cải tiến</Link></div></article></section>
  <section className="grid2"><article className="panel"><div className="head"><h2>Xu hướng chỉ số đạt mục tiêu 12 tháng</h2><p>Tỷ lệ MEETS_TARGET trong các kỳ VERIFIED/LOCKED đã có kết luận mục tiêu.</p></div><TqmTrend points={indicatorTrend}/></article><article className="panel"><div className="head"><h2>Giám sát theo khoa/phòng</h2><p>Đơn vị có tỷ lệ mục đạt thấp được đưa lên trước.</p></div>{deptBars.length?<TqmHorizontalBars rows={deptBars} max={100}/>:<div className="empty-state">Chưa có dữ liệu giám sát đủ để so sánh.</div>}</article></section>
  <section className="panel"><div className="head"><h2>Gantt đề án cải tiến trọng tâm</h2><p>Thời gian và tiến độ lấy từ dữ liệu đề án/Action thật.</p></div>{ganttRows.length?<TqmGantt year={year} rows={ganttRows}/>:<div className="empty-state">Chưa đủ mốc thời gian đề án để dựng Gantt.</div>}</section>
 </div>
}