import Link from "next/link";
import { redirect } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { TQM_CHART_CSS, TqmDonut, TqmGantt, TqmHorizontalBars } from "@/components/tqm-charts";
import { hasAnyPermission, requireUserContext } from "@/lib/auth";
import { isOperationallyHiddenStatus } from "@/lib/operational-record";
import { routeForRecord } from "@/lib/record-route";
import { createClient } from "@/lib/supabase/server";
import { getWorkYear } from "@/lib/work-year";

const DONE = new Set(["COMPLETED","CANCELLED","NOT_APPLICABLE"]);

export default async function ImprovementProjectsPage(){
 const {user}=await requireUserContext(); if(!hasAnyPermission(user,["projects.view","projects.propose","projects.manage"])) redirect("/dashboard?forbidden=1");
 const year=await getWorkYear(); const supabase=await createClient();
 const [recordsRes,projectsRes]=await Promise.all([
  supabase.from("records").select("id,record_code,title,lifecycle_status,owner_department_id,owner_user_id,updated_at").eq("record_type","IMPROVEMENT_PROJECT").eq("work_year",year).order("updated_at",{ascending:false}),
  supabase.from("improvement_projects").select("id,record_id,problem_statement,start_date,target_end_date,actual_end_date,scope_description,workflow_status,approved_at").order("updated_at",{ascending:false})
 ]);
 const records=((recordsRes.data??[]) as any[]).filter((r:any)=>!isOperationallyHiddenStatus(r.lifecycle_status)); const recordMap=new Map(records.map((r:any)=>[r.id,r]));
 const projects=((projectsRes.data??[]) as any[]).filter((p:any)=>recordMap.has(p.record_id)); const recordIds=projects.map((p:any)=>p.record_id);
 const linksRes=recordIds.length?await supabase.from("record_links").select("source_record_id,target_record_id").in("source_record_id",recordIds).eq("relation_type","HAS_ACTION"):{data:[] as any[],error:null};
 const links=(linksRes.data??[]) as any[]; const actionIds=Array.from(new Set(links.map((x:any)=>x.target_record_id).filter(Boolean)));
 const actionsRes=actionIds.length?await supabase.from("actions").select("record_id,workflow_status,due_date").in("record_id",actionIds):{data:[] as any[],error:null};
 const actionMap=new Map((actionsRes.data??[]).map((x:any)=>[x.record_id,x])); const byProject=new Map<string,any[]>();
 for(const l of links){const arr=byProject.get(l.source_record_id)??[];const a=actionMap.get(l.target_record_id);if(a)arr.push(a);byProject.set(l.source_record_id,arr)}
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh"}).format(new Date());
 const rows=projects.map((p:any)=>{const r:any=recordMap.get(p.record_id);const acts=byProject.get(p.record_id)??[];const active=acts.filter((a:any)=>!["CANCELLED","NOT_APPLICABLE"].includes(String(a.workflow_status)));const completed=active.filter((a:any)=>a.workflow_status==="COMPLETED").length;const progress=active.length?Math.round(completed/active.length*100):0;const overdue=active.filter((a:any)=>a.workflow_status!=="COMPLETED"&&a.due_date&&a.due_date<today).length;return{...p,...r,actions:active.length,completed,progress,overdue,route:routeForRecord("IMPROVEMENT_PROJECT",p.record_id)}});
 const activeProjects=rows.filter((x:any)=>["IN_PROGRESS","APPROVED","PENDING_APPROVAL"].includes(x.workflow_status)).length; const delayed=rows.filter((x:any)=>x.overdue>0||(x.target_end_date&&x.target_end_date<today&&!['EVALUATED','CLOSED'].includes(x.workflow_status))).length; const allActions=rows.reduce((s:any,x:any)=>s+x.actions,0); const doneActions=rows.reduce((s:any,x:any)=>s+x.completed,0); const overall=allActions?Math.round(doneActions/allActions*100):0; const achieved=rows.filter((x:any)=>["EVALUATED","CLOSED"].includes(x.workflow_status)).length;
 const bars=[...rows].sort((a:any,b:any)=>b.progress-a.progress).slice(0,10).map((x:any)=>({label:x.title,value:x.progress,tone:x.overdue?"red" as const:x.progress>=75?"green" as const:"blue" as const,caption:`${x.completed}/${x.actions} Action`}));
 const gantt=rows.filter((x:any)=>x.start_date&&x.target_end_date).slice(0,12).map((x:any)=>({label:x.title,start:x.start_date,end:x.target_end_date,progress:x.progress,tone:x.overdue?"red" as const:x.progress>=75?"green" as const:"blue" as const}));
 const statusCounts=new Map<string,number>();for(const x of rows)statusCounts.set(x.workflow_status,(statusCounts.get(x.workflow_status)??0)+1);
 const statusSegments=[{label:"Đang triển khai",value:statusCounts.get("IN_PROGRESS")??0,tone:"brand" as const},{label:"Chờ/đã phê duyệt",value:(statusCounts.get("PENDING_APPROVAL")??0)+(statusCounts.get("APPROVED")??0),tone:"blue" as const},{label:"Đã đánh giá/đóng",value:(statusCounts.get("EVALUATED")??0)+(statusCounts.get("CLOSED")??0),tone:"green" as const},{label:"Nháp",value:statusCounts.get("DRAFT")??0,tone:"slate" as const}];
 const firstError=[recordsRes,projectsRes,linksRes,actionsRes].find((x:any)=>x.error)?.error;
 return <div className="page-stack tqm-improvement">
  <style>{TQM_CHART_CSS+`.tqm-improvement .kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.tqm-improvement .kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:16px}.tqm-improvement .kpi span{font-size:10px;color:#718187;font-weight:800;text-transform:uppercase}.tqm-improvement .kpi strong{display:block;font-size:30px;margin-top:8px}.tqm-improvement .kpi small{font-size:10px;color:#7d8c92}.tqm-improvement .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.tqm-improvement .head{padding:17px 18px 6px}.tqm-improvement .head h2{margin:0;font-size:15px}.tqm-improvement .head p{margin:4px 0 0;color:#74838a;font-size:11px}.tqm-improvement .project-list{display:grid;gap:8px;padding:8px 16px 16px}.tqm-improvement .project-row{display:grid;grid-template-columns:minmax(0,1.6fr) 110px 110px 100px auto;gap:10px;align-items:center;padding:12px;border:1px solid #e4eaec;border-radius:13px}.tqm-improvement .project-row strong{font-size:12px}.tqm-improvement .project-row small{display:block;color:#7a898f;margin-top:3px}.tqm-improvement .mini-progress{height:7px;background:#edf2f3;border-radius:99px;overflow:hidden;margin-top:5px}.tqm-improvement .mini-progress i{display:block;height:100%;background:#0b8a7f}@media(max-width:900px){.tqm-improvement .grid{grid-template-columns:1fr}.tqm-improvement .kpis{grid-template-columns:1fr 1fr}.tqm-improvement .project-row{grid-template-columns:1fr 1fr}.tqm-improvement .project-row>div:first-child{grid-column:1/-1}}`}</style>
  <PageHeader eyebrow={`CẢI TIẾN LIÊN TỤC · ${year}`} title="Cải tiến chất lượng" description="Theo dõi đề án theo logic TQM: vấn đề → mục tiêu → Action/PDSA → kết quả → duy trì/nhân rộng. Tiến độ được tính từ Action thực tế của từng đề án."/>
  {firstError?<div className="alert error">Một phần dữ liệu chưa tải được: {firstError.message}</div>:null}
  <section className="kpis"><article className="kpi"><span>Đề án đang vận hành</span><strong>{activeProjects}</strong><small>{rows.length} đề án trong năm</small></article><article className="kpi"><span>Action hoàn thành</span><strong>{overall}%</strong><small>{doneActions}/{allActions} Action</small></article><article className="kpi"><span>Đã đạt/đóng</span><strong>{achieved}</strong><small>Đề án đã qua bước đánh giá kết quả</small></article><article className="kpi"><span>Cần can thiệp</span><strong>{delayed}</strong><small>Có Action quá hạn hoặc quá mốc đề án</small></article></section>
  <section className="grid"><article className="panel"><div className="head"><h2>Tiến độ đề án cải tiến</h2><p>Đề án chậm được tô đỏ để ưu tiên điều hành.</p></div><TqmHorizontalBars rows={bars} max={100}/></article><article className="panel"><div className="head"><h2>Trạng thái chu trình cải tiến</h2><p>Phân bố đề án theo trạng thái workflow thật.</p></div><TqmDonut value={overall} label="Action hoàn thành" segments={statusSegments}/></article></section>
  <section className="panel"><div className="head"><h2>Gantt lộ trình đề án</h2><p>Từ ngày bắt đầu đến mốc kết thúc mục tiêu; thanh bên trong thể hiện % Action đã hoàn thành.</p></div>{gantt.length?<TqmGantt year={year} rows={gantt}/>:<div className="empty-state">Chưa đủ dữ liệu thời gian để dựng Gantt.</div>}</section>
  <section className="panel"><div className="head"><h2>Danh sách đề án & trạng thái triển khai</h2><p>Drill-down vào từng hồ sơ để xem SMART, milestone/PDSA, Action, minh chứng và đánh giá kết quả.</p></div><div className="project-list">{rows.map((x:any)=><div className="project-row" key={x.record_id}><div><strong>{x.record_code} · {x.title}</strong><small>{x.problem_statement||"Chưa mô tả vấn đề"}</small><div className="mini-progress"><i style={{width:`${x.progress}%`}}/></div></div><div><strong>{x.progress}%</strong><small>{x.completed}/{x.actions} Action</small></div><div><StatusBadge status={x.workflow_status}/></div><div><strong>{x.overdue}</strong><small>Action quá hạn</small></div><Link className="button tertiary small" href={x.route}>Mở đề án</Link></div>)}{!rows.length?<div className="empty-state">Chưa có đề án cải tiến trong năm.</div>:null}</div></section>
 </div>
}
