import Link from "next/link";
import { redirect } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { TQM_CHART_CSS, TqmGantt, TqmHorizontalBars } from "@/components/tqm-charts";
import { hasAnyPermission, requireUserContext } from "@/lib/auth";
import { isOperationallyHiddenStatus } from "@/lib/operational-record";
import { routeForRecord } from "@/lib/record-route";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { getWorkYear } from "@/lib/work-year";
import { DomainCreateClient } from "@/components/domain-create-client";

const DONE = new Set(["COMPLETED","CANCELLED","NOT_APPLICABLE"]);
const CLOSED = new Set(["EVALUATED","CLOSED"]);
const STATUS_FILTERS = [
  ["attention","Cần can thiệp"],
  ["active","Đang triển khai"],
  ["closed","Đã đánh giá/đóng"],
] as const;

type PageProps = { searchParams?: Promise<{ status?: string; domain?: string }> };

export default async function ImprovementProjectsPage({searchParams}:PageProps){
 const {user}=await requireUserContext(); if(!hasAnyPermission(user,["projects.view","projects.propose","projects.manage"])) redirect("/dashboard?forbidden=1");
 const canManage=hasAnyPermission(user,["projects.manage"]);
 const filters=await searchParams; const selectedStatus=String(filters?.status||""); const selectedDomain=String(filters?.domain||"");
 const year=await getWorkYear(); const supabase=await createClient(); const admin=createAdminClient();
 const [recordsRes,projectsRes]=await Promise.all([
  supabase.from("records").select("id,record_code,title,lifecycle_status,owner_department_id,owner_user_id,updated_at").eq("record_type","IMPROVEMENT_PROJECT").eq("work_year",year).order("updated_at",{ascending:false}),
  supabase.from("improvement_projects").select("id,record_id,problem_statement,start_date,target_end_date,actual_end_date,scope_description,workflow_status,approved_at,lead_department_id,project_leader_user_id").order("updated_at",{ascending:false})
 ]);
 const records=((recordsRes.data??[]) as any[]).filter((r:any)=>!isOperationallyHiddenStatus(r.lifecycle_status)); const recordMap=new Map(records.map((r:any)=>[r.id,r]));
 const projects=((projectsRes.data??[]) as any[]).filter((p:any)=>recordMap.has(p.record_id)); const recordIds=projects.map((p:any)=>p.record_id); const projectIds=projects.map((p:any)=>p.id);
 const [linksRes,objectivesRes,milestonesRes,closureRes,domainLinksRes]=await Promise.all([
  recordIds.length?supabase.from("record_links").select("source_record_id,target_record_id").in("source_record_id",recordIds).eq("relation_type","HAS_ACTION"):Promise.resolve({data:[] as any[],error:null}),
  projectIds.length?supabase.from("project_objectives").select("project_id,objective_text,indicator_name,baseline_value,target_value,target_date").in("project_id",projectIds):Promise.resolve({data:[] as any[],error:null}),
  projectIds.length?supabase.from("project_milestones").select("project_id,status,pdsa_phase,due_date,planned_end_date,study_result,learning_summary,act_decision").in("project_id",projectIds):Promise.resolve({data:[] as any[],error:null}),
  projectIds.length?supabase.from("project_closure_reviews").select("project_id,overall_result,sustainability_required,scaleout_recommended,reviewed_at").in("project_id",projectIds):Promise.resolve({data:[] as any[],error:null}),
  recordIds.length?admin.from("record_quality_domain_links").select("record_id,domain_id").in("record_id",recordIds):Promise.resolve({data:[] as any[],error:null}),
 ] as any);
 const links=(linksRes.data??[]) as any[]; const actionIds=Array.from(new Set(links.map((x:any)=>x.target_record_id).filter(Boolean)));
 const [actionsRes,domainsRes,departmentsRes,profilesRes]=await Promise.all([
  actionIds.length?supabase.from("actions").select("record_id,workflow_status,due_date").in("record_id",actionIds):Promise.resolve({data:[] as any[],error:null}),
  admin.from("quality_domains").select("id,name,sort_order").eq("is_active",true).order("sort_order"),
  supabase.from("departments").select("id,name,short_name").eq("is_active",true),
  supabase.from("profiles").select("user_id,full_name,email").eq("is_active",true),
 ] as any);
 const actionMap=new Map((actionsRes.data??[]).map((x:any)=>[x.record_id,x])); const byProject=new Map<string,any[]>();
 for(const l of links){const arr=byProject.get(l.source_record_id)??[];const a=actionMap.get(l.target_record_id);if(a)arr.push(a);byProject.set(l.source_record_id,arr)}
 const objectiveMap=new Map<string,any[]>();for(const x of (objectivesRes.data??[]) as any[]){const a=objectiveMap.get(x.project_id)??[];a.push(x);objectiveMap.set(x.project_id,a)}
 const milestoneMap=new Map<string,any[]>();for(const x of (milestonesRes.data??[]) as any[]){const a=milestoneMap.get(x.project_id)??[];a.push(x);milestoneMap.set(x.project_id,a)}
 const closureMap=new Map<string,any>();for(const x of (closureRes.data??[]) as any[])closureMap.set(x.project_id,x);
 const domainMap=new Map<string,string>();for(const x of (domainsRes.data??[]) as any[])domainMap.set(String(x.id),String(x.name));
 const recordDomains=new Map<string,string[]>();for(const x of (domainLinksRes.data??[]) as any[]){const a=recordDomains.get(String(x.record_id))??[];a.push(String(x.domain_id));recordDomains.set(String(x.record_id),a)}
 const departmentMap=new Map<string,string>();for(const x of (departmentsRes.data??[]) as any[])departmentMap.set(String(x.id),String(x.short_name||x.name||"—"));
 const profileMap=new Map<string,string>();for(const x of (profilesRes.data??[]) as any[])profileMap.set(String(x.user_id),String(x.full_name||x.email||"—"));
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh"}).format(new Date());
 const rows=projects.map((p:any)=>{const r:any=recordMap.get(p.record_id);const acts=byProject.get(p.record_id)??[];const active=acts.filter((a:any)=>!["CANCELLED","NOT_APPLICABLE"].includes(String(a.workflow_status)));const completed=active.filter((a:any)=>a.workflow_status==="COMPLETED").length;const progress=active.length?Math.round(completed/active.length*100):0;const overdue=active.filter((a:any)=>a.workflow_status!=="COMPLETED"&&a.due_date&&a.due_date<today).length;const objectives=objectiveMap.get(p.id)??[];const objectiveReady=objectives.filter((o:any)=>o.objective_text&&o.indicator_name&&o.baseline_value&&o.target_value&&o.target_date).length;const milestones=milestoneMap.get(p.id)??[];const pdsaPhases=new Set(milestones.map((m:any)=>String(m.pdsa_phase||"").toUpperCase()).filter(Boolean));const pdsaCoverage=["PLAN","DO","STUDY","ACT"].filter(x=>pdsaPhases.has(x)).length;const milestoneOverdue=milestones.filter((m:any)=>!DONE.has(String(m.status||""))&&(m.due_date||m.planned_end_date)&&(m.due_date||m.planned_end_date)<today).length;const domains=recordDomains.get(p.record_id)??[];const closure=closureMap.get(p.id)||null;const delayed=overdue>0||milestoneOverdue>0||(p.target_end_date&&p.target_end_date<today&&!CLOSED.has(p.workflow_status));return{...p,...r,actions:active.length,completed,progress,overdue,milestoneOverdue,objectives:objectives.length,objectiveReady,pdsaCoverage,domains,closure,delayed,route:routeForRecord("IMPROVEMENT_PROJECT",p.record_id)}});
 const activeProjects=rows.filter((x:any)=>["IN_PROGRESS","APPROVED","PENDING_APPROVAL"].includes(x.workflow_status)).length; const delayed=rows.filter((x:any)=>x.delayed).length; const allActions=rows.reduce((s:number,x:any)=>s+x.actions,0); const doneActions=rows.reduce((s:number,x:any)=>s+x.completed,0); const overall=allActions?Math.round(doneActions/allActions*100):0; const achieved=rows.filter((x:any)=>CLOSED.has(x.workflow_status)).length;
 const objectiveTotal=rows.reduce((s:number,x:any)=>s+x.objectives,0); const objectiveReadyTotal=rows.reduce((s:number,x:any)=>s+x.objectiveReady,0); const objectiveCoverage=objectiveTotal?Math.round(objectiveReadyTotal/objectiveTotal*100):0;
 const pdsaReady=rows.filter((x:any)=>x.pdsaCoverage===4).length;
 const bars=[...rows].sort((a:any,b:any)=>Number(b.delayed)-Number(a.delayed)||a.progress-b.progress).slice(0,10).map((x:any)=>({label:x.title,value:x.progress,tone:x.delayed?"red" as const:x.progress>=75?"green" as const:"blue" as const,caption:`${x.completed}/${x.actions} Action`}));
 const gantt=rows.filter((x:any)=>x.start_date&&x.target_end_date).sort((a:any,b:any)=>Number(b.delayed)-Number(a.delayed)).slice(0,12).map((x:any)=>({label:x.title,start:x.start_date,end:x.target_end_date,progress:x.progress,tone:x.delayed?"red" as const:x.progress>=75?"green" as const:"blue" as const}));
 const domainOptions=(domainsRes.data??[]) as any[];
 let filtered=rows.filter((x:any)=>!selectedDomain||x.domains.includes(selectedDomain));
 if(selectedStatus==="attention")filtered=filtered.filter((x:any)=>x.delayed);else if(selectedStatus==="active")filtered=filtered.filter((x:any)=>["IN_PROGRESS","APPROVED","PENDING_APPROVAL"].includes(x.workflow_status));else if(selectedStatus==="closed")filtered=filtered.filter((x:any)=>CLOSED.has(x.workflow_status));
 filtered.sort((a:any,b:any)=>Number(b.delayed)-Number(a.delayed)||b.overdue-a.overdue||a.progress-b.progress||String(b.updated_at).localeCompare(String(a.updated_at)));
 const firstError=[recordsRes,projectsRes,linksRes,actionsRes,objectivesRes,milestonesRes,closureRes,domainLinksRes,domainsRes].find((x:any)=>x.error)?.error;
 function href(status:string,domain:string){const p=new URLSearchParams();if(status)p.set("status",status);if(domain)p.set("domain",domain);const q=p.toString();return `/improvement/projects${q?`?${q}`:""}`}
 return <div className="page-stack tqm-improvement">
  <style>{TQM_CHART_CSS+`.tqm-improvement .kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}.tqm-improvement .kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:15px}.tqm-improvement .kpi span{font-size:9px;color:#718187;font-weight:800;text-transform:uppercase}.tqm-improvement .kpi strong{display:block;font-size:27px;margin-top:8px}.tqm-improvement .kpi small{font-size:10px;color:#7d8c92}.tqm-improvement .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.tqm-improvement .head{padding:17px 18px 6px}.tqm-improvement .head h2{margin:0;font-size:15px}.tqm-improvement .head p{margin:4px 0 0;color:#74838a;font-size:11px}.tqm-improvement .filters{display:flex;gap:7px;flex-wrap:wrap;padding:14px 16px}.tqm-improvement .filter-chip{border:1px solid #d8e3e6;border-radius:999px;padding:6px 10px;font-size:10px;font-weight:800;color:#52666d;text-decoration:none;background:#fff}.tqm-improvement .filter-chip.on{background:#e8f4f3;border-color:#a6d3ce;color:#17675f}.tqm-improvement .domain-filter{min-width:220px;margin-left:auto}.tqm-improvement .project-list{display:grid;gap:8px;padding:8px 16px 16px}.tqm-improvement .project-row{display:grid;grid-template-columns:minmax(0,1.8fr) 125px 115px 125px 120px auto;gap:10px;align-items:center;padding:12px;border:1px solid #e4eaec;border-radius:13px}.tqm-improvement .project-row.attention{border-color:#f1c3bd;background:#fffafa}.tqm-improvement .project-row strong{font-size:12px}.tqm-improvement .project-row small{display:block;color:#7a898f;margin-top:3px}.tqm-improvement .mini-progress{height:7px;background:#edf2f3;border-radius:99px;overflow:hidden;margin-top:5px}.tqm-improvement .mini-progress i{display:block;height:100%;background:#0b8a7f}.tqm-improvement .tags{display:flex;gap:4px;flex-wrap:wrap;margin-top:5px}.tqm-improvement .tag{font-size:9px;padding:3px 6px;border-radius:999px;background:#eef5f6;color:#52666d}.tqm-improvement .attention-note{font-size:10px;color:#9a3412;font-weight:800;margin-top:4px}@media(max-width:1100px){.tqm-improvement .kpis{grid-template-columns:repeat(3,1fr)}.tqm-improvement .project-row{grid-template-columns:1fr 1fr 1fr}.tqm-improvement .project-row>div:first-child{grid-column:1/-1}}@media(max-width:760px){.tqm-improvement .grid{grid-template-columns:1fr}.tqm-improvement .kpis{grid-template-columns:1fr 1fr}.tqm-improvement .domain-filter{margin-left:0;width:100%}.tqm-improvement .project-row{grid-template-columns:1fr 1fr}}`}</style>
  <PageHeader eyebrow={`PORTFOLIO CẢI TIẾN · ${year}`} title="Danh mục đề án cải tiến" description="Màn hình điều hành danh mục: ưu tiên đề án chậm, theo dõi Action, SMART, PDSA, kết quả và lĩnh vực chất lượng/an toàn trên dữ liệu QARICA hiện có." actions={canManage?<DomainCreateClient recordType="IMPROVEMENT_PROJECT" workYear={year}/>:null}/>
  {firstError?<div className="alert error">Một phần dữ liệu chưa tải được: {firstError.message}</div>:null}
  <section className="kpis"><article className="kpi"><span>Đang vận hành</span><strong>{activeProjects}</strong><small>{rows.length} đề án trong năm</small></article><article className="kpi"><span>Cần can thiệp</span><strong>{delayed}</strong><small>Quá hạn Action/mốc/đề án</small></article><article className="kpi"><span>Action hoàn thành</span><strong>{overall}%</strong><small>{doneActions}/{allActions} Action</small></article><article className="kpi"><span>SMART đủ dữ liệu</span><strong>{objectiveCoverage}%</strong><small>{objectiveReadyTotal}/{objectiveTotal} mục tiêu</small></article><article className="kpi"><span>Đủ 4 pha PDSA</span><strong>{pdsaReady}</strong><small>Đề án có Plan–Do–Study–Act</small></article><article className="kpi"><span>Đã đánh giá/đóng</span><strong>{achieved}</strong><small>Đã qua đánh giá kết quả</small></article></section>
  <section className="grid"><article className="panel"><div className="head"><h2>Tiến độ Action theo đề án</h2><p>Đề án cần can thiệp được đưa lên trước và tô đỏ.</p></div><TqmHorizontalBars rows={bars} max={100}/></article><article className="panel"><div className="head"><h2>Lộ trình danh mục</h2><p>Gantt theo mốc bắt đầu–kết thúc; tiến độ tính từ Action thực tế.</p></div>{gantt.length?<TqmGantt year={year} rows={gantt}/>:<div className="empty-state">Chưa đủ dữ liệu thời gian để dựng Gantt.</div>}</article></section>
  <section className="panel"><div className="head"><h2>VIỆC CẦN XỬ LÝ · Portfolio</h2><p>Lọc danh mục theo tình trạng và lĩnh vực; mặc định xếp đề án có blocker/quá hạn lên đầu.</p></div><div className="filters"><Link className={`filter-chip ${!selectedStatus?"on":""}`} href={href("",selectedDomain)}>Tất cả</Link>{STATUS_FILTERS.map(([value,label])=><Link key={value} className={`filter-chip ${selectedStatus===value?"on":""}`} href={href(value,selectedDomain)}>{label}</Link>)}<select className="domain-filter" value={selectedDomain} onChange={undefined} aria-label="Lĩnh vực chất lượng" style={{display:"none"}} /><span className="filter-chip">Lĩnh vực:</span><Link className={`filter-chip ${!selectedDomain?"on":""}`} href={href(selectedStatus,"")}>Tất cả</Link>{domainOptions.map((d:any)=><Link key={d.id} className={`filter-chip ${selectedDomain===String(d.id)?"on":""}`} href={href(selectedStatus,String(d.id))}>{d.name}</Link>)}</div><div className="project-list">{filtered.map((x:any)=>{const owner=x.project_leader_user_id||x.owner_user_id;const dept=x.lead_department_id||x.owner_department_id;return <div className={`project-row ${x.delayed?"attention":""}`} key={x.record_id}><div><strong>{x.record_code} · {x.title}</strong><small>{x.problem_statement||"Chưa mô tả vấn đề"}</small><div className="tags">{x.domains.map((id:string)=><span className="tag" key={id}>{domainMap.get(id)||"Lĩnh vực"}</span>)}</div>{x.delayed?<div className="attention-note">Cần xử lý: {x.overdue} Action quá hạn · {x.milestoneOverdue} mốc quá hạn{x.target_end_date&&x.target_end_date<today&&!CLOSED.has(x.workflow_status)?" · quá hạn đề án":""}</div>:null}<div className="mini-progress"><i style={{width:`${x.progress}%`}}/></div></div><div><strong>{departmentMap.get(String(dept))||"Chưa gán"}</strong><small>{profileMap.get(String(owner))||"Chưa gán trưởng đề án"}</small></div><div><strong>{x.progress}%</strong><small>{x.completed}/{x.actions} Action</small></div><div><strong>{x.objectiveReady}/{x.objectives}</strong><small>SMART đủ / tổng</small></div><div><strong>{x.pdsaCoverage}/4 PDSA</strong><small>{x.closure?.overall_result?`KQ: ${x.closure.overall_result}`:"Chưa kết luận"}</small></div><div><StatusBadge status={x.workflow_status}/><Link className="button tertiary small" href={x.route} style={{marginTop:6}}>Mở đề án</Link></div></div>})}{!filtered.length?<div className="empty-state">Không có đề án phù hợp bộ lọc hiện tại.</div>:null}</div></section>
 </div>
}
