import { TQM_CHART_CSS, TqmDonut, TqmHorizontalBars, TqmTrend } from "@/components/tqm-charts";
import { createClient } from "@/lib/supabase/server";

type Row={id:string;record_code:string;title:string;lifecycle_status:string;department_name:string;created_at:string;updated_at:string};
type Tone="brand"|"blue"|"amber"|"red"|"green"|"slate";
const DONE=new Set(["CLOSED","COMPLETED","FINALIZED","APPROVED","REVIEWED","SUBMITTED"]);
const ACTION_DONE=new Set(["COMPLETED","CANCELLED","NOT_APPLICABLE"]);
const CSS=`${TQM_CHART_CSS}.av2-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.av2-kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:15px 16px}.av2-kpi span{display:block;font-size:10px;color:#728188;font-weight:800;text-transform:uppercase}.av2-kpi strong{display:block;font-size:29px;line-height:1;margin-top:8px}.av2-kpi small{display:block;font-size:10px;color:#7d8c92;margin-top:6px}.av2-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.av2-head{padding:16px 18px 4px}.av2-head h2{margin:0;font-size:15px}.av2-head p{margin:4px 0 0;color:#74838a;font-size:11px}.av2-strip{display:grid;grid-template-columns:repeat(8,minmax(0,1fr));gap:7px;padding:8px 18px 18px}.av2-milestone{border:1px solid #e0e8eb;border-radius:12px;padding:10px 8px;text-align:center}.av2-milestone strong{font-size:11px}.av2-milestone span{display:block;font-size:18px;font-weight:900;margin-top:5px}.av2-milestone small{display:block;font-size:9px;color:#728188;margin-top:3px}@media(max-width:900px){.av2-grid{grid-template-columns:1fr}.av2-strip{grid-template-columns:repeat(4,1fr)}}@media(max-width:700px){.av2-kpis{grid-template-columns:1fr 1fr}.av2-strip{grid-template-columns:repeat(2,1fr)}}`;
function Kpis({items}:{items:{label:string;value:string|number;note:string}[]}){return <section className="av2-kpis">{items.map(x=><article className="av2-kpi" key={x.label}><span>{x.label}</span><strong>{x.value}</strong><small>{x.note}</small></article>)}</section>}
function monthPoints(values:(string|null|undefined)[]){const p=Array.from({length:12},(_,i)=>({label:`T${i+1}`,value:0}));values.forEach(v=>{if(!v)return;const d=new Date(v);if(!Number.isNaN(d.getTime()))p[d.getMonth()].value++});return p}
function statusBars(values:string[]){const m=new Map<string,number>();values.forEach(v=>m.set(v||"UNKNOWN",(m.get(v||"UNKNOWN")||0)+1));return Array.from(m.entries()).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([label,value],i)=>({label:label.replaceAll("_"," "),value,tone:(i===0?"brand":i===1?"blue":i===2?"amber":"slate") as Tone}))}

export async function AssessmentInspectionOverviewV2({rows,recordType}:{rows:Row[];recordType:string}){
 const supabase=await createClient();const recordIds=rows.map(r=>r.id);if(!recordIds.length)return null;
 if(recordType==="ASSESSMENT"){
  const {data:rounds}=await supabase.from("assessment_rounds").select("id,record_id,workflow_status").in("record_id",recordIds);const rr=(rounds??[]) as any[];const roundIds=rr.map(x=>x.id);
  const [scopeResult,assessmentResult]=await Promise.all([roundIds.length?supabase.from("assessment_round_criteria").select("id,assessment_round_id").in("assessment_round_id",roundIds):Promise.resolve({data:[] as any[]}),roundIds.length?supabase.from("criterion_assessments").select("assessment_round_id,workflow_status").in("assessment_round_id",roundIds):Promise.resolve({data:[] as any[]})]);
  const scopes=(scopeResult.data??[]) as any[];const assessments=(assessmentResult.data??[]) as any[];const submitted=assessments.filter(x=>DONE.has(String(x.workflow_status))).length;const completion=scopes.length?Math.min(100,Math.round(submitted/scopes.length*100)):0;const finalized=rr.filter(x=>String(x.workflow_status)==="FINALIZED").length;
  return <><style>{CSS}</style><Kpis items={[{label:"Đợt tự đánh giá",value:rows.length,note:"Trong năm đang chọn"},{label:"Tiêu chí trong phạm vi",value:scopes.length,note:"Scope đã cấu hình"},{label:"Đã gửi đánh giá",value:`${completion}%`,note:`${submitted}/${scopes.length||0} tiêu chí`},{label:"Đợt đã chốt",value:finalized,note:"Đã qua kiểm tra chéo"}]}/><section className="av2-grid"><article className="panel"><div className="av2-head"><h2>Mức hoàn thành tự đánh giá</h2><p>Tỷ lệ tiêu chí đã gửi/được rà soát trên tổng phạm vi.</p></div><TqmDonut value={completion} label="Hoàn thành" segments={[{label:"Đã gửi",value:submitted,tone:"green"},{label:"Còn lại",value:Math.max(0,scopes.length-submitted),tone:"slate"}]}/></article><article className="panel"><div className="av2-head"><h2>Đợt đánh giá theo workflow</h2><p>Phân bố các đợt theo bước nghiệp vụ.</p></div><TqmHorizontalBars rows={statusBars(rr.map(x=>String(x.workflow_status||"DRAFT")))}/></article></section><section className="panel"><div className="av2-head"><h2>Đợt tự đánh giá được khởi tạo theo tháng</h2><p>Dùng Registry <strong>created_at</strong> để quan sát nhịp khởi tạo hồ sơ; không diễn giải đây là xu hướng kết quả chất lượng.</p></div><TqmTrend points={monthPoints(rows.map(r=>r.created_at))} unit=""/></section></>;
 }
 if(recordType==="EXTERNAL_ASSESSMENT"){
  const {data:events}=await supabase.from("external_assessment_events").select("record_id,assessment_date").in("record_id",recordIds);const eventRows=(events??[]) as any[];
  const [comparisonResult,findingLinkResult]=await Promise.all([supabase.from("record_links").select("source_record_id,target_record_id").in("source_record_id",recordIds).eq("relation_type","COMPARED_WITH_SELF"),supabase.from("record_links").select("source_record_id,target_record_id").in("source_record_id",recordIds).eq("relation_type","GENERATED_FINDING")]);const comparisons=(comparisonResult.data??[]) as any[];const links=(findingLinkResult.data??[]) as any[];const findingIds=links.map(x=>x.target_record_id).filter(Boolean);const {data:findings}=findingIds.length?await supabase.from("findings").select("record_id,workflow_status,severity").in("record_id",findingIds):{data:[] as any[]};const fr=(findings??[]) as any[];const open=fr.filter(x=>!["CLOSED","CANCELLED"].includes(String(x.workflow_status))).length;const closed=Math.max(0,fr.length-open);const linkedRate=rows.length?Math.round(comparisons.length/rows.length*100):0;
  return <><style>{CSS}</style><Kpis items={[{label:"Đợt đánh giá ngoài",value:rows.length,note:"Trong năm"},{label:"Đã khóa Self",value:`${linkedRate}%`,note:`${comparisons.length}/${rows.length}`},{label:"Chênh lệch sinh Finding",value:fr.length,note:"Không ghi đè Self"},{label:"Finding còn mở",value:open,note:"Cần recheck"}]}/><section className="av2-grid"><article className="panel"><div className="av2-head"><h2>Khép vòng chênh lệch Self ↔ Đoàn ngoài</h2><p>Finding phát sinh phải được xử lý trước khi chốt đối chiếu.</p></div><TqmDonut value={fr.length?Math.round(closed/fr.length*100):0} label="Finding đã đóng" segments={[{label:"Đã đóng",value:closed,tone:"green"},{label:"Còn mở",value:open,tone:"red"}]}/></article><article className="panel"><div className="av2-head"><h2>Finding theo mức độ</h2><p>Ưu tiên chênh lệch nghiêm trọng/tới hạn.</p></div><TqmHorizontalBars rows={statusBars(fr.map(x=>String(x.severity||"UNKNOWN")))}/></article></section><section className="panel"><div className="av2-head"><h2>Đánh giá ngoài theo tháng thực hiện</h2><p>Dùng <strong>assessment_date</strong> của đoàn ngoài, không dùng ngày chỉnh sửa hồ sơ.</p></div><TqmTrend points={monthPoints(eventRows.map(x=>x.assessment_date))} unit=""/></section></>;
 }
 if(recordType==="AUDIT"){
  const {data:audits}=await supabase.from("audits").select("id,record_id,workflow_status").in("record_id",recordIds);const ar=(audits??[]) as any[];const auditIds=ar.map(x=>x.id);const [scopeResult,sessionResult,linkResult]=await Promise.all([auditIds.length?supabase.from("audit_scopes").select("id,audit_id").in("audit_id",auditIds):Promise.resolve({data:[] as any[]}),auditIds.length?supabase.from("audit_sessions").select("id,audit_id").in("audit_id",auditIds):Promise.resolve({data:[] as any[]}),auditIds.length?supabase.from("audit_finding_links").select("audit_id,finding_id").in("audit_id",auditIds):Promise.resolve({data:[] as any[]})]);const scopes=(scopeResult.data??[]) as any[];const sessions=(sessionResult.data??[]) as any[];const links=(linkResult.data??[]) as any[];const findingIds=links.map(x=>x.finding_id).filter(Boolean);const {data:findings}=findingIds.length?await supabase.from("findings").select("id,workflow_status").in("id",findingIds):{data:[] as any[]};const fr=(findings??[]) as any[];const open=fr.filter(x=>!["CLOSED","CANCELLED"].includes(String(x.workflow_status))).length;const closed=ar.filter(x=>String(x.workflow_status)==="CLOSED").length;
  return <><style>{CSS}</style><Kpis items={[{label:"Audit / Tracer",value:rows.length,note:"Trong năm"},{label:"Phạm vi audit",value:scopes.length,note:"Scope đã cấu hình"},{label:"Phiên thực hiện",value:sessions.length,note:"Session đã ghi nhận"},{label:"Finding còn mở",value:open,note:`${fr.length} Finding tổng`}]} /><section className="av2-grid"><article className="panel"><div className="av2-head"><h2>Khép vòng Audit / Tracer</h2><p>Chỉ đóng sau follow-up Finding.</p></div><TqmDonut value={ar.length?Math.round(closed/ar.length*100):0} label="Audit đã đóng" segments={[{label:"Đã đóng",value:closed,tone:"green"},{label:"Còn mở",value:Math.max(0,ar.length-closed),tone:"amber"}]}/></article><article className="panel"><div className="av2-head"><h2>Audit theo workflow</h2><p>Scope → thực hiện → review báo cáo → follow-up.</p></div><TqmHorizontalBars rows={statusBars(ar.map(x=>String(x.workflow_status||"DRAFT")))}/></article></section><section className="panel"><div className="av2-head"><h2>Hồ sơ Audit / Tracer được khởi tạo theo tháng</h2><p>Schema hiện chưa cung cấp business date audit đủ chuẩn cho landing này; dùng <strong>created_at</strong> và không gọi đây là quality trend.</p></div><TqmTrend points={monthPoints(rows.map(r=>r.created_at))} unit=""/></section></>;
 }
 if(recordType==="INSPECTION"){
  const {data:events}=await supabase.from("inspection_events").select("id,record_id,visit_date,workflow_status").in("record_id",recordIds);const er=(events??[]) as any[];const eventIds=er.map(x=>x.id);const {data:links}=eventIds.length?await supabase.from("inspection_action_links").select("inspection_event_id,action_id,offset_days").in("inspection_event_id",eventIds):{data:[] as any[]};const lr=(links??[]) as any[];const actionIds=lr.map(x=>x.action_id).filter(Boolean);const {data:actions}=actionIds.length?await supabase.from("actions").select("id,workflow_status,due_date").in("id",actionIds):{data:[] as any[]};const aa=(actions??[]) as any[];const done=aa.filter(x=>ACTION_DONE.has(String(x.workflow_status))).length;const progress=aa.length?Math.round(done/aa.length*100):0;const today=new Date().toISOString().slice(0,10);const upcoming=er.filter(x=>x.visit_date&&x.visit_date>=today&&String(x.workflow_status)!=="CLOSED").length;const onSite=er.filter(x=>String(x.workflow_status)==="ON_SITE").length;const follow=er.filter(x=>String(x.workflow_status)==="FOLLOW_UP").length;const byOffset=new Map<number,{total:number;done:number}>();lr.forEach(x=>byOffset.set(Number(x.offset_days),{total:(byOffset.get(Number(x.offset_days))?.total||0)+1,done:byOffset.get(Number(x.offset_days))?.done||0}));const actionMap=new Map(aa.map(x=>[x.id,x]));lr.forEach(x=>{const cur=byOffset.get(Number(x.offset_days));if(cur&&ACTION_DONE.has(String(actionMap.get(x.action_id)?.workflow_status)))cur.done++});
  return <><style>{CSS}</style><Kpis items={[{label:"Đợt tiếp đoàn",value:er.length,note:"Inspection Mode"},{label:"Action countdown",value:aa.length,note:`${progress}% hoàn tất`},{label:"Đoàn sắp tới",value:upcoming,note:"Chưa đóng"},{label:"Đang tại chỗ / follow-up",value:onSite+follow,note:`${onSite} on-site · ${follow} follow-up`}]} /><section className="av2-grid"><article className="panel"><div className="av2-head"><h2>Sẵn sàng Inspection Mode</h2><p>Countdown Action phải có sản phẩm/minh chứng và được xác minh.</p></div><TqmDonut value={progress} label="Action hoàn tất" segments={[{label:"Hoàn tất",value:done,tone:"green"},{label:"Còn lại",value:Math.max(0,aa.length-done),tone:"amber"}]}/></article><article className="panel"><div className="av2-head"><h2>Đợt tiếp đoàn theo workflow</h2><p>Planning → Preparation → On-site → Follow-up → Closed.</p></div><TqmHorizontalBars rows={statusBars(er.map(x=>String(x.workflow_status||"PLANNING")))}/></article></section><section className="panel"><div className="av2-head"><h2>Ngày đoàn làm việc theo tháng</h2><p>Dùng <strong>visit_date</strong> thực tế của Inspection, không dùng `updated_at`.</p></div><TqmTrend points={monthPoints(er.map(x=>x.visit_date))} unit=""/></section><section className="panel"><div className="av2-head"><h2>Countdown D-30 → D+7</h2><p>Mỗi mốc hiển thị số Action hoàn tất/tổng Action đã sinh.</p></div><div className="av2-strip">{[-30,-14,-7,-3,-1,0,1,7].map(offset=>{const x=byOffset.get(offset)||{total:0,done:0};return <div className="av2-milestone" key={offset}><strong>{offset<0?`D${offset}`:offset===0?"D-Day":`D+${offset}`}</strong><span>{x.done}/{x.total}</span><small>Action hoàn tất</small></div>})}</div></section></>;
 }
 return null;
}
