"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

type Option = { id: string; label: string };
type Scope = { id: string; department: string; process: string; area: string; description: string };
type Session = { id: string; start: string; end: string; department: string; location: string; status: string };

export function AuditWorkflowClient({ recordId, status, canManage, scopes, sessions, findings, openFindings, evidence, departments, scopeRows, sessionRows }: { recordId: string; status: string; canManage: boolean; scopes: number; sessions: number; findings: number; openFindings: number; evidence: number; departments: Option[]; scopeRows: Scope[]; sessionRows: Session[] }) {
  const router = useRouter();
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [scope, setScope] = useState({ department_id: "", process_name: "", area_name: "", scope_description: "" });
  const [session, setSession] = useState({ department_id: "", scheduled_start: "", scheduled_end: "", location: "" });
  async function call(url: string, action: string, payload: Record<string, unknown> = {}) { setBusy(true); setError(""); setNotice(""); try { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const json = await response.json().catch(() => ({})); if (!response.ok) throw new Error(json.error || "Không xử lý được Audit."); setNotice(json.message); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không xử lý được Audit."); } finally { setBusy(false); } }
  const run = (action: string, payload: Record<string, unknown> = {}) => call(`/api/audits/${recordId}/workflow`, action, payload);
  const setup = (action: string, payload: Record<string, unknown>) => call(`/api/audits/${recordId}/setup`, action, payload);
  return <section className="panel"><div className="panel-title"><div><h2>Audit/Tracer Workflow</h2><p>Phạm vi → thực hiện → báo cáo → Finding → recheck → đóng.</p></div><strong>{status}</strong></div><div style={{ padding: "0 18px 18px", display: "grid", gap: 14 }}>
    {error ? <div className="alert error">{error}</div> : null}{notice ? <div className="alert success">{notice}</div> : null}
    <div className="domain-metrics"><div><strong>{scopes}</strong><span>Phạm vi</span></div><div><strong>{sessions}</strong><span>Phiên Audit</span></div><div><strong>{findings}/{openFindings}</strong><span>Finding/chưa đóng</span></div><div><strong>{evidence}</strong><span>Bằng chứng</span></div></div>
    {status === "DRAFT" && canManage ? <div className="page-stack"><h3>Thêm phạm vi Audit</h3><div className="detail-grid"><label><span>Khoa/phòng</span><select value={scope.department_id} onChange={(e) => setScope({ ...scope, department_id: e.target.value })}><option value="">Chọn...</option>{departments.map((x) => <option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label><span>Quy trình</span><input value={scope.process_name} onChange={(e) => setScope({ ...scope, process_name: e.target.value })} /></label><label><span>Khu vực</span><input value={scope.area_name} onChange={(e) => setScope({ ...scope, area_name: e.target.value })} /></label><label className="wide"><span>Mô tả phạm vi</span><textarea rows={2} value={scope.scope_description} onChange={(e) => setScope({ ...scope, scope_description: e.target.value })} /></label></div><button className="button secondary" disabled={busy || (!scope.department_id && !scope.process_name && !scope.area_name && !scope.scope_description)} onClick={() => setup("ADD_SCOPE", scope)}>Thêm phạm vi</button></div> : null}
    {scopeRows.length ? <div className="table-wrap"><table><thead><tr><th>Khoa/phòng</th><th>Quy trình</th><th>Khu vực</th><th>Phạm vi</th></tr></thead><tbody>{scopeRows.map((x) => <tr key={x.id}><td>{x.department || "—"}</td><td>{x.process || "—"}</td><td>{x.area || "—"}</td><td>{x.description || "—"}</td></tr>)}</tbody></table></div> : null}
    {status === "DRAFT" && canManage ? <button className="button primary" disabled={busy || scopes < 1} onClick={() => run("START")}>Bắt đầu Audit</button> : null}
    {status === "IN_PROGRESS" && canManage ? <div className="page-stack"><h3>Tạo phiên thực hiện Audit</h3><div className="detail-grid"><label><span>Bắt đầu *</span><input type="datetime-local" value={session.scheduled_start} onChange={(e) => setSession({ ...session, scheduled_start: e.target.value })} /></label><label><span>Kết thúc</span><input type="datetime-local" value={session.scheduled_end} onChange={(e) => setSession({ ...session, scheduled_end: e.target.value })} /></label><label><span>Khoa/phòng</span><select value={session.department_id} onChange={(e) => setSession({ ...session, department_id: e.target.value })}><option value="">Chọn...</option>{departments.map((x) => <option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label><span>Địa điểm</span><input value={session.location} onChange={(e) => setSession({ ...session, location: e.target.value })} /></label></div><button className="button secondary" disabled={busy || !session.scheduled_start} onClick={() => setup("ADD_SESSION", session)}>Tạo phiên Audit</button></div> : null}
    {sessionRows.length ? <div className="table-wrap"><table><thead><tr><th>Bắt đầu</th><th>Kết thúc</th><th>Khoa/phòng</th><th>Địa điểm</th><th>Trạng thái</th></tr></thead><tbody>{sessionRows.map((x) => <tr key={x.id}><td>{x.start}</td><td>{x.end || "—"}</td><td>{x.department || "—"}</td><td>{x.location || "—"}</td><td>{x.status}</td></tr>)}</tbody></table></div> : null}
    {status === "IN_PROGRESS" && canManage ? <button className="button primary" disabled={busy || sessions < 1 || evidence < 1} onClick={() => run("SUBMIT_REPORT")}>Gửi báo cáo rà soát</button> : null}
    {["DRAFT_REPORT", "REPORT_REVIEW"].includes(status) && canManage ? <button className="button primary" disabled={busy} onClick={() => run("START_FOLLOW_UP")}>Chuyển theo dõi Finding</button> : null}
    {status === "FOLLOW_UP" && canManage ? <button className="button primary" disabled={busy || openFindings > 0} onClick={() => { const conclusion = window.prompt("Kết luận đóng Audit/Tracer:"); if (conclusion?.trim()) run("CLOSE", { comment: conclusion.trim() }); }}>Đóng Audit/Tracer</button> : null}
  </div></section>;
}
