"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";

const LABEL:Record<string,string>={DRAFT:"Nháp",PENDING_APPROVAL:"Chờ phê duyệt",ROOT_CAUSE_ANALYSIS:"Phân tích nguyên nhân",IN_PROGRESS:"Đang triển khai",EFFECTIVENESS_REVIEW:"Đánh giá hiệu lực",EFFECTIVE:"Đã xác nhận hiệu lực",CLOSED:"Đã đóng"};
const NEXT:Record<string,string>={DRAFT:"Xác nhận phạm vi và khởi động CAPA.",PENDING_APPROVAL:"Phê duyệt phạm vi, owner và ưu tiên trước khi RCA.",ROOT_CAUSE_ANALYSIS:"Hoàn tất RCA, sau đó phải có cả Corrective và Preventive Action.",IN_PROGRESS:"Hoàn tất toàn bộ Action áp dụng và bổ sung minh chứng trước đánh giá hiệu lực.",EFFECTIVENESS_REVIEW:"So sánh mục tiêu với kết quả thực tế và kết luận hiệu lực.",EFFECTIVE:"CAPA đã đạt gate hiệu lực; thực hiện đóng hồ sơ.",CLOSED:"CAPA đã đóng; giữ nguyên RCA, Action, minh chứng và lịch sử đánh giá."};
export function CapaWorkflowClient({recordId,status,canManage,approvalRequired,hasCompletedRca,correctiveCount,preventiveCount,incompleteActionCount,evidenceCount,effectivenessReviewCount,requiredResources}:{recordId:string;status:string;canManage:boolean;approvalRequired:boolean;hasCompletedRca:boolean;correctiveCount:number;preventiveCount:number;incompleteActionCount:number;evidenceCount:number;effectivenessReviewCount:number;requiredResources:string}){
 const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[method,setMethod]=useState("5_WHY");const[conclusion,setConclusion]=useState("");const[evalMethod,setEvalMethod]=useState("");const[target,setTarget]=useState("");const[actual,setActual]=useState("");const[result,setResult]=useState("EFFECTIVE");const[comment,setComment]=useState("");const[resources,setResources]=useState(requiredResources||"");
 async function command(action:string,payload:Record<string,unknown>={}){if(busy)return;setBusy(true);setError("");setNotice("");try{const r=await fetch(`/api/capa/${recordId}/workflow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Không xử lý được CAPA.");setNotice(j.message);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Không xử lý được CAPA.")}finally{setBusy(false)}}
 function saveRca(e:FormEvent){e.preventDefault();command("SAVE_RCA",{method,conclusion})}function review(e:FormEvent){e.preventDefault();command("REVIEW_EFFECTIVENESS",{evaluation_method:evalMethod,target_description:target,actual_result:actual,result,comment})}function saveResources(e:FormEvent){e.preventDefault();command("SET_RESOURCES",{required_resources:resources})}
 const steps=["Khởi tạo","RCA","Corrective + Preventive","Đánh giá hiệu lực","Đóng"];
 const progress=status==="CLOSED"?5:status==="EFFECTIVE"?4:status==="EFFECTIVENESS_REVIEW"?4:status==="IN_PROGRESS"?3:status==="ROOT_CAUSE_ANALYSIS"?2:1;
 const actionBlockers=status==="ROOT_CAUSE_ANALYSIS"?[!hasCompletedRca?"RCA chưa hoàn tất":"",correctiveCount<1?"Thiếu Corrective Action":"",preventiveCount<1?"Thiếu Preventive Action":""].filter(Boolean):[];
 const reviewBlockers=status==="IN_PROGRESS"?[correctiveCount<1?"Thiếu Corrective Action":"",preventiveCount<1?"Thiếu Preventive Action":"",incompleteActionCount>0?`Còn ${incompleteActionCount} Action chưa hoàn tất`:"",evidenceCount<1?"Thiếu minh chứng":"",!resources.trim()?"Thiếu nguồn lực cần":""].filter(Boolean):[];
 return <section className="panel capa-wf"><style>{`.capa-wf{overflow:hidden}.cw-head{display:flex;justify-content:space-between;gap:12px;padding:18px;border-bottom:1px solid #e7eef0}.cw-head h2{margin:0;font-size:18px}.cw-head p{margin:5px 0 0;color:#64748b;font-size:12px}.cw-status{padding:6px 10px;border-radius:999px;background:#eff6ff;color:#1d4ed8;font-size:11px;font-weight:850;height:max-content}.cw-next{margin:14px 18px 0;padding:13px 14px;border:1px solid #bdd9e2;border-radius:12px;background:#f2f9fb;display:grid;gap:3px}.cw-next span{font-size:9px;font-weight:900;color:#55737d;text-transform:uppercase}.cw-next strong{font-size:13px;color:#173f4a}.cw-steps{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;padding:14px 18px;background:#fbfdff}.cw-step{text-align:center;padding:9px 5px;border-radius:10px;background:#edf2f4;color:#718087;font-size:10px;font-weight:800}.cw-step.on{background:#dbeafe;color:#1d4ed8}.cw-body{display:grid;gap:12px;padding:0 18px 18px}.cw-metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.cw-metric{border:1px solid #dfe8ea;border-radius:11px;padding:10px}.cw-metric strong{display:block;font-size:18px}.cw-metric span{font-size:9px;color:#64748b}.cw-box{border:1px solid #dfe8ea;border-radius:12px;padding:14px}.cw-box h3{margin:0 0 5px;font-size:14px}.cw-box p{margin:0 0 11px;font-size:11px;color:#64748b}.cw-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cw-form .wide{grid-column:1/-1}.cw-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:11px}.cw-blockers{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.cw-blocker{padding:5px 8px;border-radius:999px;background:#fff1f2;color:#9f1239;font-size:10px;font-weight:800}@media(max-width:760px){.cw-steps,.cw-metrics,.cw-form{grid-template-columns:1fr 1fr}.cw-form .wide{grid-column:1/-1}.cw-head{display:grid}}`}</style>
 <div className="cw-head"><div><h2>CAPA Workflow · Khắc phục và phòng ngừa</h2><p>Không đóng CAPA chỉ vì Action hoàn tất; bắt buộc xác minh hiệu lực bằng kết quả thực tế.</p></div><span className="cw-status">{LABEL[status]||status}</span></div><div className="cw-next"><span>Việc cần làm tiếp theo</span><strong>{NEXT[status]||"Tiếp tục xử lý theo trạng thái CAPA."}</strong></div><div className="cw-steps">{steps.map((x,i)=><div className={`cw-step ${progress>=i+1?"on":""}`} key={x}>{i+1}. {x}</div>)}</div>
 <div className="cw-body">{error?<div className="alert error">{error}</div>:null}{notice?<div className="alert success">{notice}</div>:null}<div className="cw-metrics"><div className="cw-metric"><strong>{hasCompletedRca?"Đủ":"Thiếu"}</strong><span>RCA hoàn tất</span></div><div className="cw-metric"><strong>{correctiveCount}</strong><span>Corrective</span></div><div className="cw-metric"><strong>{preventiveCount}</strong><span>Preventive</span></div><div className="cw-metric"><strong>{incompleteActionCount}</strong><span>Action chưa xong</span></div><div className="cw-metric"><strong>{evidenceCount}</strong><span>Minh chứng</span></div></div>
 {status!=="CLOSED"?<form className="cw-box" onSubmit={saveResources}><h3>Nguồn lực cần</h3><p>Nhân lực, kinh phí, thiết bị... cần để thực hiện CAPA — bắt buộc theo mục 9.3 London Protocol 2024, khai báo và cập nhật được ở bất kỳ bước nào trước khi đóng.</p><div className="cw-form"><label className="wide">Mô tả nguồn lực *<textarea rows={2} value={resources} onChange={e=>setResources(e.target.value)} disabled={!canManage}/></label></div>{canManage?<div className="cw-actions"><button className="button secondary" disabled={busy}>Lưu nguồn lực</button></div>:null}</form>:null}
 {status==="DRAFT"&&canManage?<div className="cw-box"><h3>Bước 1 · Khởi động CAPA</h3><p>{approvalRequired?"CAPA này phải được phê duyệt trước khi phân tích và triển khai.":"CAPA có thể chuyển thẳng sang phân tích nguyên nhân gốc."}</p><button className="button primary" disabled={busy} onClick={()=>command("START")}>{approvalRequired?"Gửi phê duyệt":"Bắt đầu CAPA"}</button></div>:null}
 {status==="PENDING_APPROVAL"&&canManage?<div className="cw-box"><h3>Phê duyệt CAPA</h3><p>Xác nhận phạm vi, owner, ưu tiên và nhu cầu xử lý hệ thống.</p><button className="button primary" disabled={busy} onClick={()=>command("APPROVE")}>Phê duyệt triển khai</button></div>:null}
 {status==="ROOT_CAUSE_ANALYSIS"&&canManage?<form className="cw-box" onSubmit={saveRca}><h3>Bước 2 · Phân tích nguyên nhân gốc</h3><p>Kết luận phải chỉ ra nguyên nhân hệ thống làm căn cứ thiết kế hành động khắc phục và phòng ngừa.</p><div className="cw-form"><label>Phương pháp<select value={method} onChange={e=>setMethod(e.target.value)}><option value="5_WHY">5 Why</option><option value="FISHBONE">Xương cá</option><option value="RCA_TEAM">RCA nhóm</option><option value="OTHER">Khác</option></select></label><label className="wide">Kết luận nguyên nhân gốc *<textarea rows={4} value={conclusion} onChange={e=>setConclusion(e.target.value)}/></label></div>{actionBlockers.length?<div className="cw-blockers">{actionBlockers.map(x=><span className="cw-blocker" key={x}>{x}</span>)}</div>:null}<div className="cw-actions"><button className="button secondary" disabled={busy}>Lưu/hoàn tất RCA</button><button type="button" className="button primary" disabled={busy||actionBlockers.length>0} onClick={()=>command("START_ACTIONS")}>Bắt đầu triển khai Action</button></div></form>:null}
 {status==="IN_PROGRESS"&&canManage?<div className="cw-box"><h3>Bước 3 · Theo dõi Action</h3><p>Gate chuyển đánh giá hiệu lực: có Corrective + Preventive, toàn bộ Action áp dụng đã hoàn tất và có minh chứng.</p>{reviewBlockers.length?<div className="cw-blockers">{reviewBlockers.map(x=><span className="cw-blocker" key={x}>{x}</span>)}</div>:null}<button className="button primary" disabled={busy||reviewBlockers.length>0} onClick={()=>command("REQUEST_EFFECTIVENESS")}>Chuyển đánh giá hiệu lực</button></div>:null}
 {status==="EFFECTIVENESS_REVIEW"&&canManage?<form className="cw-box" onSubmit={review}><h3>Bước 4 · Đánh giá hiệu lực lần {effectivenessReviewCount+1}</h3><p>So sánh mục tiêu với kết quả thực tế. Nếu chưa hiệu lực, hệ thống mở lại bước triển khai.</p><div className="cw-form"><label>Phương pháp đánh giá *<input value={evalMethod} onChange={e=>setEvalMethod(e.target.value)}/></label><label>Kết luận<select value={result} onChange={e=>setResult(e.target.value)}><option value="EFFECTIVE">Có hiệu lực</option><option value="PARTIALLY_EFFECTIVE">Hiệu lực một phần</option><option value="INEFFECTIVE">Không hiệu lực</option></select></label><label className="wide">Mục tiêu/tiêu chuẩn đạt *<textarea rows={3} value={target} onChange={e=>setTarget(e.target.value)}/></label><label className="wide">Kết quả thực tế *<textarea rows={3} value={actual} onChange={e=>setActual(e.target.value)}/></label><label className="wide">Nhận xét<textarea rows={2} value={comment} onChange={e=>setComment(e.target.value)}/></label></div><div className="cw-actions"><button className="button primary" disabled={busy}>Lưu đánh giá hiệu lực</button></div></form>:null}
 {status==="EFFECTIVE"&&canManage?<div className="cw-box"><h3>Bước 5 · Đóng CAPA</h3><p>RCA, Action, minh chứng và đánh giá hiệu lực đã đạt gate nghiệp vụ.</p><button className="button primary" disabled={busy} onClick={()=>command("CLOSE")}>Đóng CAPA</button></div>:null}
 </div></section>
}
