import { TQM_CHART_CSS, TqmDonut, TqmHorizontalBars, TqmTrend } from "@/components/tqm-charts";
import { createClient } from "@/lib/supabase/server";

type Row={id:string;record_code:string;title:string;lifecycle_status:string;department_name:string;created_at:string;updated_at:string};
type Tone="brand"|"blue"|"amber"|"red"|"green"|"slate";
const CSS=`${TQM_CHART_CSS}.cs-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.cs-kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:15px 16px}.cs-kpi span{display:block;font-size:10px;color:#728188;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.cs-kpi strong{display:block;font-size:29px;line-height:1;margin-top:8px}.cs-kpi small{display:block;font-size:10px;color:#7d8c92;margin-top:6px}.cs-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.cs-head{padding:16px 18px 4px}.cs-head h2{margin:0;font-size:15px}.cs-head p{margin:4px 0 0;color:#74838a;font-size:11px}@media(max-width:900px){.cs-grid{grid-template-columns:1fr}}@media(max-width:700px){.cs-kpis{grid-template-columns:1fr 1fr}}`;
function Kpis({items}:{items:{label:string;value:string|number;note:string}[]}){return <section className="cs-kpis">{items.map(x=><article className="cs-kpi" key={x.label}><span>{x.label}</span><strong>{x.value}</strong><small>{x.note}</small></article>)}</section>}
function monthPoints(values:(string|null|undefined)[]){const out=Array.from({length:12},(_,i)=>({label:`T${i+1}`,value:0}));values.forEach(value=>{if(!value)return;const d=new Date(value);if(!Number.isNaN(d.getTime()))out[d.getMonth()].value++});return out}
function bars(values:string[]){const map=new Map<string,number>();values.forEach(v=>map.set(v||"UNKNOWN",(map.get(v||"UNKNOWN")||0)+1));return Array.from(map.entries()).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([label,value],i)=>({label:label.replaceAll("_"," "),value,tone:(i===0?"brand":i===1?"blue":i===2?"amber":"slate") as Tone}))}

export async function CorrectiveSafetyOverview({rows,recordType}:{rows:Row[];recordType:string}){
 const supabase=await createClient();const ids=rows.map(r=>r.id);if(!ids.length)return null;
 if(recordType==="FINDING"){
  const {data}=await supabase.from("findings").select("id,record_id,workflow_status,severity,due_date,identified_at").in("record_id",ids);const findings=(data??[]) as any[];const today=new Date().toISOString().slice(0,10);
  const open=findings.filter(x=>!["CLOSED","CANCELLED"].includes(String(x.workflow_status))).length;const closed=findings.length-open;const overdue=findings.filter(x=>x.due_date&&x.due_date<today&&!["CLOSED","CANCELLED"].includes(String(x.workflow_status))).length;const returned=findings.filter(x=>String(x.workflow_status)==="RETURNED").length;
  const severityMap=new Map<string,number>();findings.forEach(x=>severityMap.set(String(x.severity||"UNKNOWN"),(severityMap.get(String(x.severity||"UNKNOWN"))||0)+1));const severity=Array.from(severityMap.entries()).sort((a,b)=>b[1]-a[1]).map(([label,value])=>({label:label.replaceAll("_"," "),value,tone:(label==="CRITICAL"?"red":label==="MAJOR"?"amber":label==="MINOR"?"blue":"slate") as Tone}));
  const {data:links}=await supabase.from("record_links").select("source_record_id,target_record_id").in("source_record_id",ids).eq("relation_type","ESCALATED_TO_CAPA");const escalated=(links??[]).length;
  return <><style>{CSS}</style><Kpis items={[{label:"Finding",value:findings.length,note:"Tất cả nguồn trong năm"},{label:"Còn mở",value:open,note:"Chưa hoàn tất recheck"},{label:"Quá hạn",value:overdue,note:"Ưu tiên xử lý ngay"},{label:"Chuyển CAPA",value:escalated,note:`${returned} Finding bị trả lại`}]} /><section className="cs-grid"><article className="panel"><div className="cs-head"><h2>Khép vòng Finding → Action → Evidence → Recheck</h2><p>Finding chỉ được đóng sau xác minh; không tính hoàn tất chỉ vì Action đã làm xong.</p></div><TqmDonut value={findings.length?Math.round(closed/findings.length*100):0} label="Đã đóng" segments={[{label:"Đã đóng",value:closed,tone:"green"},{label:"Còn mở",value:open,tone:overdue?"red":"amber"}]}/></article><article className="panel"><div className="cs-head"><h2>Mức độ Finding</h2><p>Ưu tiên Critical/Major và các Finding đã quá hạn trước.</p></div><TqmHorizontalBars rows={severity}/></article></section><section className="cs-grid"><article className="panel"><div className="cs-head"><h2>Finding theo bước xác minh</h2><p>Open/Assigned → In progress → Evidence submitted → Verifying → Closed/Returned.</p></div><TqmHorizontalBars rows={bars(findings.map(x=>String(x.workflow_status||"OPEN")))}/></article><article className="panel"><div className="cs-head"><h2>Finding phát hiện theo tháng</h2><p>Dùng <strong>identified_at</strong> của Finding để phản ánh thời điểm phát hiện thực tế, không dùng ngày chỉnh sửa hồ sơ.</p></div><TqmTrend points={monthPoints(findings.map(x=>x.identified_at))} unit=""/></article></section></>;
 }
 if(recordType==="FEEDBACK"){
  const {data}=await supabase.from("feedback_records").select("id,record_id,workflow_status").in("record_id",ids);const feedback=(data??[]) as any[];const responded=feedback.filter(x=>["RESPONDED","CLOSED"].includes(String(x.workflow_status))).length;const coordinating=feedback.filter(x=>String(x.workflow_status)==="COORDINATING").length;
  const {data:links}=await supabase.from("record_links").select("source_record_id,target_record_id").in("source_record_id",ids).eq("relation_type","GENERATED_FINDING");const generated=(links??[]).length;const responseRate=feedback.length?Math.round(responded/feedback.length*100):0;const conversion=feedback.length?Math.round(generated/feedback.length*100):0;
  const depMap=new Map<string,number>();rows.forEach(r=>depMap.set(r.department_name,(depMap.get(r.department_name)||0)+1));const deps=Array.from(depMap.entries()).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value],i)=>({label,value,tone:(i<3?"brand":"blue") as Tone}));
  return <><style>{CSS}</style><Kpis items={[{label:"Phản ánh / góp ý",value:feedback.length,note:"Trong năm đang chọn"},{label:"Đã phản hồi",value:`${responseRate}%`,note:`${responded}/${feedback.length||0} hồ sơ`},{label:"Đang phối hợp",value:coordinating,note:"Cần xác minh/xử lý"},{label:"Sinh Finding",value:generated,note:`${conversion}% phản ánh chuyển tồn tại hệ thống`}]} /><section className="cs-grid"><article className="panel"><div className="cs-head"><h2>Khép vòng phản hồi người bệnh/khách hàng</h2><p>Phản ánh được xử lý và phản hồi độc lập; Finding phát sinh tiếp tục đi vòng CAPA khi cần.</p></div><TqmDonut value={responseRate} label="Đã phản hồi" segments={[{label:"Đã phản hồi/đóng",value:responded,tone:"green"},{label:"Đang xử lý",value:Math.max(0,feedback.length-responded),tone:"amber"}]}/></article><article className="panel"><div className="cs-head"><h2>Phản ánh theo khoa/phòng phụ trách</h2><p>Nhận diện nơi có tải phối hợp và nhu cầu cải tiến cao.</p></div><TqmHorizontalBars rows={deps}/></article></section><section className="cs-grid"><article className="panel"><div className="cs-head"><h2>Phản ánh theo bước xử lý</h2><p>Received → Triaged → Coordinating → Responded → Closed.</p></div><TqmHorizontalBars rows={bars(feedback.map(x=>String(x.workflow_status||"RECEIVED")))}/></article><article className="panel"><div className="cs-head"><h2>Phản ánh được ghi nhận theo tháng</h2><p>Dùng ngày tạo hồ sơ Registry như thời điểm hệ thống ghi nhận phản ánh; biểu đồ này chưa được diễn giải như xu hướng chất lượng đầu ra.</p></div><TqmTrend points={monthPoints(rows.map(r=>r.created_at))} unit=""/></article></section></>;
 }
 return null;
}
