"use client";
import { FormEvent,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";

type SetRow={id:string;code:string|null;name:string;description:string|null;is_active:boolean};
type Version={id:string;version_no:number;status:string;effective_from:string|null;effective_to:string|null;published_at:string|null};
type Item={id:string;code:string|null;title:string|null;description:string|null;sequence_no:number|null;chapter_code:string|null;chapter_name:string|null;score_weight:number;is_core:boolean;is_mandatory:boolean;max_score:number|null;parent_criteria_item_id:string|null;item_type:string;is_active:boolean};
type Form={id:string;parent_id:string;item_type:string;code:string;title:string;description:string;chapter_code:string;chapter_name:string;score_weight:string;max_score:string;is_core:boolean;is_mandatory:boolean};
const empty:Form={id:"",parent_id:"",item_type:"CRITERION",code:"",title:"",description:"",chapter_code:"",chapter_name:"",score_weight:"1",max_score:"",is_core:false,is_mandatory:false};

export function CriteriaSetEditorClient({criteriaSet,versions,version,items,canManage}:{criteriaSet:SetRow;versions:Version[];version:Version|null;items:Item[];canManage:boolean}){
 const router=useRouter();const [form,setForm]=useState<Form>(empty);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<{tone:"success"|"error";text:string}|null>(null);
 const editable=canManage&&criteriaSet.is_active&&version?.status==="DRAFT";
 const roots=useMemo(()=>items.filter(x=>!x.parent_criteria_item_id),[items]);
 const children=useMemo(()=>{const map=new Map<string,Item[]>();for(const item of items.filter(x=>x.parent_criteria_item_id)){const key=item.parent_criteria_item_id!;map.set(key,[...(map.get(key)||[]),item]);}return map},[items]);
 function add(parentId=""){setForm({...empty,parent_id:parentId,item_type:parentId?"SUBITEM":"CRITERION"});setMessage(null);setOpen(true)}
 function edit(item:Item){setForm({id:item.id,parent_id:item.parent_criteria_item_id||"",item_type:item.item_type||"CRITERION",code:item.code||"",title:item.title||"",description:item.description||"",chapter_code:item.chapter_code||"",chapter_name:item.chapter_name||"",score_weight:String(item.score_weight||1),max_score:item.max_score===null||item.max_score===undefined?"":String(item.max_score),is_core:item.is_core,is_mandatory:item.is_mandatory});setMessage(null);setOpen(true)}
 async function submit(e:FormEvent){e.preventDefault();if(!form.title.trim())return setMessage({tone:"error",text:"Vui lòng nhập tên tiêu chí/tiểu mục."});setBusy(true);setMessage(null);try{
  const url=form.id?`/api/criteria-items/${form.id}`:`/api/criteria-sets/${criteriaSet.id}/items`;const payload={parent_criteria_item_id:form.parent_id||null,item_type:form.item_type,code:form.code||null,title:form.title,description:form.description||null,chapter_code:form.chapter_code||null,chapter_name:form.chapter_name||null,score_weight:Number(form.score_weight)||1,max_score:form.max_score||null,is_core:form.is_core,is_mandatory:form.is_mandatory};
  const res=await fetch(url,{method:form.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.error||"Không lưu được tiêu chí.");setMessage({tone:"success",text:"Đã lưu."});router.refresh();setTimeout(()=>setOpen(false),250);
 }catch(e){setMessage({tone:"error",text:e instanceof Error?e.message:"Có lỗi xảy ra."})}finally{setBusy(false)}}
 async function toggle(item:Item){if(!window.confirm(item.is_active?"Ngưng tiêu chí này? Nếu là tiêu chí cha, các tiểu mục bên dưới cũng sẽ ngưng.":"Kích hoạt lại mục này?"))return;setBusy(true);try{const res=await fetch(`/api/criteria-items/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({is_active:!item.is_active})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Không cập nhật được trạng thái.");router.refresh()}catch(e){alert(e instanceof Error?e.message:"Có lỗi xảy ra.")}finally{setBusy(false)}}
 async function createRevision(){if(!window.confirm("Tạo phiên bản Nháp mới từ phiên bản hiện tại để cập nhật nội dung?"))return;setBusy(true);try{const res=await fetch(`/api/criteria-sets/${criteriaSet.id}/versions`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Không tạo được bản cập nhật.");router.refresh()}catch(e){alert(e instanceof Error?e.message:"Có lỗi xảy ra.")}finally{setBusy(false)}}
 async function publish(){if(!version||!window.confirm(`Phát hành phiên bản v${version.version_no}? Bản đã phát hành trước đó sẽ chuyển sang lịch sử.`))return;setBusy(true);try{const res=await fetch(`/api/criteria-sets/${criteriaSet.id}/publish`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({version_id:version.id})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Không phát hành được.");router.refresh()}catch(e){alert(e instanceof Error?e.message:"Có lỗi xảy ra.")}finally{setBusy(false)}}
 return <>
  <section className="kpi-grid"><article className="kpi-card"><span>Phiên bản đang xem</span><strong>{version?`v${version.version_no}`:"—"}</strong><small>{version?.status==="DRAFT"?"Nháp · được chỉnh sửa":version?.status==="PUBLISHED"?"Đã phát hành · khóa nội dung":"—"}</small></article><article className="kpi-card"><span>Tiêu chí cấp 1</span><strong>{roots.length}</strong><small>{roots.filter(x=>x.is_active).length} đang áp dụng</small></article><article className="kpi-card"><span>Tiểu mục</span><strong>{items.length-roots.length}</strong><small>Tối đa 1 cấp dưới tiêu chí</small></article><article className="kpi-card success"><span>Trạng thái bộ</span><strong style={{fontSize:18}}>{criteriaSet.is_active?"Đang áp dụng":"Đã ngưng"}</strong><small>{versions.length} phiên bản được lưu</small></article></section>
  <section className="panel"><div className="panel-title"><div><h2>Cấu trúc tiêu chí</h2><p>Tiêu chí cấp 1 có thể có nhiều tiểu mục. Không tạo cây sâu hơn để giao diện chấm điểm vẫn đơn giản.</p></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}>{canManage&&version?.status!=="DRAFT"&&criteriaSet.is_active?<button className="button secondary" disabled={busy} onClick={createRevision}>Tạo bản cập nhật</button>:null}{editable?<><button className="button primary" onClick={()=>add()}><Icon name="plus" size={16}/> Thêm tiêu chí</button><button className="button secondary" disabled={busy||!items.some(x=>x.is_active)} onClick={publish}>Phát hành v{version?.version_no}</button></>:null}</div></div>
   {!criteriaSet.is_active?<div className="scope-note" style={{margin:"0 18px 16px"}}>Bộ tiêu chí đã ngưng áp dụng. Dữ liệu lịch sử vẫn được giữ nhưng không cho cấu hình mới.</div>:null}
   {version?.status==="PUBLISHED"?<div className="scope-note" style={{margin:"0 18px 16px"}}>Phiên bản đã phát hành được khóa. Chọn <strong>Tạo bản cập nhật</strong> để QARICA sao chép sang phiên bản Nháp mới.</div>:null}
   <div style={{padding:"0 16px 16px",display:"grid",gap:9}}>{roots.map((root,index)=><article key={root.id} className="operating-spec-card" style={{opacity:root.is_active?1:.6}}>
     <div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start",flexWrap:"wrap"}}><div><div className="eyebrow">TIÊU CHÍ {index+1}</div><strong>{root.code?`${root.code} · `:""}{root.title}</strong>{root.description?<div className="subline">{root.description}</div>:null}{root.chapter_name?<div className="subline">{root.chapter_code?root.chapter_code+" · ":""}{root.chapter_name}</div>:null}</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><span className={`status-badge ${root.is_active?"success":"muted"}`}>{root.is_active?"Áp dụng":"Ngưng"}</span>{editable?<><button className="button tertiary small" onClick={()=>add(root.id)}>+ Tiểu mục</button><button className="button secondary small" onClick={()=>edit(root)}>Sửa</button><button className="button secondary small" onClick={()=>toggle(root)}>{root.is_active?"Ngưng":"Kích hoạt"}</button></>:null}</div></div>
     {(children.get(root.id)||[]).length?<div style={{display:"grid",gap:6,marginTop:10,paddingLeft:18}}>{(children.get(root.id)||[]).map((child,childIndex)=><div key={child.id} style={{display:"flex",justifyContent:"space-between",gap:8,padding:"9px 10px",border:"1px solid var(--line)",borderRadius:10,opacity:child.is_active?1:.55}}><div><strong>{child.code?`${child.code} · `:""}{child.title}</strong><span className="subline">Tiểu mục {index+1}.{childIndex+1}</span></div>{editable?<div style={{display:"flex",gap:5}}><button className="button tertiary small" onClick={()=>edit(child)}>Sửa</button><button className="button secondary small" onClick={()=>toggle(child)}>{child.is_active?"Ngưng":"Kích hoạt"}</button></div>:null}</div>)}</div>:null}
   </article>)}{!roots.length?<div className="empty-state">Phiên bản này chưa có tiêu chí.{editable?<div style={{marginTop:10}}><button className="button primary" onClick={()=>add()}>Thêm tiêu chí đầu tiên</button></div>:null}</div>:null}</div>
  </section>
  {versions.length>1?<section className="panel"><div className="panel-title"><div><h2>Lịch sử phiên bản</h2><p>Không sửa đè phiên bản đã dùng trong đánh giá.</p></div></div><div className="table-wrap"><table><thead><tr><th>Phiên bản</th><th>Trạng thái</th><th>Hiệu lực</th><th>Phát hành</th></tr></thead><tbody>{versions.map(v=><tr key={v.id}><td><strong>v{v.version_no}</strong></td><td>{v.status}</td><td>{v.effective_from||"—"}{v.effective_to?` → ${v.effective_to}`:""}</td><td>{v.published_at?new Date(v.published_at).toLocaleString("vi-VN"):"—"}</td></tr>)}</tbody></table></div></section>:null}
  {open?<div className="modal-backdrop"><form className="modal-card" onSubmit={submit} style={{width:"min(820px,calc(100vw - 32px))"}}><div className="modal-head"><div><div className="eyebrow">{form.item_type==="SUBITEM"?"TIỂU MỤC":form.item_type==="TOPIC"?"CHUYÊN ĐỀ":form.item_type==="GROUP"?"NHÓM":"TIÊU CHÍ"}</div><h2>{form.id?"Cập nhật":"Thêm"} {form.parent_id?"tiểu mục":"tiêu chí"}</h2></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><Icon name="x"/></button></div><div className="modal-body">{message?<div className={`alert ${message.tone}`}>{message.text}</div>:null}<div className="form-grid two"><label>Loại nội dung<select value={form.item_type} onChange={e=>setForm({...form,item_type:e.target.value})} disabled={!!form.parent_id}><option value="CRITERION">Tiêu chí</option><option value="TOPIC">Chuyên đề</option><option value="GROUP">Nhóm / phần</option>{form.parent_id?<option value="SUBITEM">Tiểu mục</option>:null}</select></label><label>Mã<input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder={form.parent_id?"Ví dụ: A1.1.a":"Ví dụ: A1.1"}/></label><label>Trọng số<input type="number" min="1" value={form.score_weight} onChange={e=>setForm({...form,score_weight:e.target.value})}/></label><label className="span-2">Tên / nội dung *<textarea rows={3} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Chương / phần<input value={form.chapter_code} onChange={e=>setForm({...form,chapter_code:e.target.value})}/></label><label>Tên chương / phần<input value={form.chapter_name} onChange={e=>setForm({...form,chapter_name:e.target.value})}/></label><label>Điểm tối đa<input type="number" step="0.01" value={form.max_score} onChange={e=>setForm({...form,max_score:e.target.value})}/></label><div style={{display:"flex",gap:12,alignItems:"end"}}><label className="inline-check"><input type="checkbox" checked={form.is_core} onChange={e=>setForm({...form,is_core:e.target.checked})}/> Cốt lõi</label><label className="inline-check"><input type="checkbox" checked={form.is_mandatory} onChange={e=>setForm({...form,is_mandatory:e.target.checked})}/> Bắt buộc</label></div><label className="span-2">Mô tả / hướng dẫn<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div></div><div className="modal-footer"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Đóng</button><button className="button primary" disabled={busy}>{busy?"Đang lưu...":"Lưu"}</button></div></form></div>:null}
 </>;
}
