"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";

type Row={id:string;code:string|null;name:string;description:string|null;is_active:boolean;latest_version_id:string|null;latest_version_no:number|null;latest_version_status:string|null;published_version_no:number|null;item_count:number};
type Form={id:string;code:string;name:string;description:string;effective_from:string};
const empty:Form={id:"",code:"",name:"",description:"",effective_from:""};

export function CriteriaCatalogClient({rows,canManage}:{rows:Row[];canManage:boolean}){
 const router=useRouter();const [q,setQ]=useState("");const [showInactive,setShowInactive]=useState(false);const [open,setOpen]=useState(false);const [form,setForm]=useState<Form>(empty);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<{tone:"success"|"error";text:string}|null>(null);
 const filtered=useMemo(()=>{const n=q.trim().toLowerCase();return rows.filter(r=>(showInactive||r.is_active)&&(!n||`${r.code||""} ${r.name} ${r.description||""}`.toLowerCase().includes(n)))},[rows,q,showInactive]);
 function create(){setForm(empty);setMessage(null);setOpen(true)}
 function edit(row:Row){setForm({id:row.id,code:row.code||"",name:row.name,description:row.description||"",effective_from:""});setMessage(null);setOpen(true)}
 async function submit(e:FormEvent){e.preventDefault();if(!form.name.trim())return setMessage({tone:"error",text:"Vui lòng nhập tên bộ tiêu chí."});setBusy(true);setMessage(null);try{
  const res=await fetch(form.id?`/api/criteria-sets/${form.id}`:"/api/criteria-sets",{method:form.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:form.code||undefined,name:form.name,description:form.description||null,effective_from:form.effective_from||null})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Không lưu được bộ tiêu chí.");setMessage({tone:"success",text:form.id?"Đã cập nhật thông tin bộ tiêu chí.":`Đã tạo ${data.code} ở trạng thái Nháp.`});router.refresh();if(!form.id&&data.id)setTimeout(()=>router.push(`/assessments/catalog/${data.id}`),350);
 }catch(e){setMessage({tone:"error",text:e instanceof Error?e.message:"Có lỗi xảy ra."})}finally{setBusy(false)}}
 async function toggle(row:Row){if(!window.confirm(row.is_active?"Ngưng áp dụng bộ tiêu chí này? Dữ liệu đánh giá cũ vẫn được giữ.":"Kích hoạt lại bộ tiêu chí này?"))return;setBusy(true);try{const res=await fetch(`/api/criteria-sets/${row.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({is_active:!row.is_active})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Không cập nhật được trạng thái.");router.refresh()}catch(e){alert(e instanceof Error?e.message:"Có lỗi xảy ra.")}finally{setBusy(false)}}
 return <>
  <section className="kpi-grid"><article className="kpi-card"><span>Tổng bộ tiêu chí</span><strong>{rows.length}</strong><small>{rows.filter(x=>x.is_active).length} đang áp dụng</small></article><article className="kpi-card success"><span>Đã phát hành</span><strong>{rows.filter(x=>x.published_version_no).length}</strong><small>Có phiên bản đang hiệu lực</small></article><article className="kpi-card warning"><span>Đang cập nhật</span><strong>{rows.filter(x=>x.latest_version_status==="DRAFT").length}</strong><small>Có phiên bản nháp</small></article><article className="kpi-card"><span>Tiêu chí hiện hành</span><strong>{rows.reduce((s,x)=>s+x.item_count,0)}</strong><small>Tính trên phiên bản mới nhất</small></article></section>
  <section className="panel"><div className="toolbar"><div className="search-box"><Icon name="search" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm mã hoặc tên bộ tiêu chí..."/></div><label className="inline-check"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/> Hiện đã ngưng</label>{canManage?<button className="button primary" onClick={create}><Icon name="plus" size={17}/> Thêm bộ tiêu chí</button>:null}</div>
   <div className="table-wrap"><table><thead><tr><th>Mã</th><th>Bộ tiêu chí</th><th>Phiên bản</th><th>Cấu trúc</th><th>Trạng thái</th><th></th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><span className="record-code-pill">{row.code||"—"}</span></td><td><Link className="table-link" href={`/assessments/catalog/${row.id}`}><strong>{row.name}</strong></Link>{row.description?<span className="subline">{row.description}</span>:null}</td><td><strong>{row.latest_version_no?`v${row.latest_version_no}`:"—"}</strong><span className="subline">{row.latest_version_status==="DRAFT"?"Nháp":row.latest_version_status==="PUBLISHED"?"Đã phát hành":row.latest_version_status||"—"}</span></td><td>{row.item_count} mục</td><td><span className={`status-badge ${row.is_active?"success":"muted"}`}>{row.is_active?"Đang áp dụng":"Đã ngưng"}</span></td><td><div style={{display:"flex",gap:6,justifyContent:"flex-end",flexWrap:"wrap"}}><Link className="button tertiary small" href={`/assessments/catalog/${row.id}`}>Mở</Link>{canManage?<><button className="button secondary small" onClick={()=>edit(row)}>Cập nhật</button><button className="button secondary small" disabled={busy} onClick={()=>toggle(row)}>{row.is_active?"Ngưng":"Kích hoạt"}</button></>:null}</div></td></tr>)}{!filtered.length?<tr><td colSpan={6}><div className="empty-state">Chưa có bộ tiêu chí phù hợp.</div></td></tr>:null}</tbody></table></div>
  </section>
  {open?<div className="modal-backdrop"><form className="modal-card" onSubmit={submit} style={{width:"min(760px,calc(100vw - 32px))"}}><div className="modal-head"><div><div className="eyebrow">DANH MỤC TIÊU CHÍ</div><h2>{form.id?"Cập nhật bộ tiêu chí":"Thêm bộ tiêu chí"}</h2></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><Icon name="x"/></button></div><div className="modal-body">{message?<div className={`alert ${message.tone}`}>{message.text}</div>:null}<div className="form-stack"><label>Mã bộ tiêu chí <input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="Để trống để QARICA tự sinh TC-YYYY-####"/></label><label>Tên bộ tiêu chí *<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Mô tả / nguồn áp dụng<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{!form.id?<label>Ngày hiệu lực dự kiến<input type="date" value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label>:null}</div></div><div className="modal-footer"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Đóng</button><button className="button primary" disabled={busy}>{busy?"Đang lưu...":"Lưu"}</button></div></form></div>:null}
 </>;
}
