"use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { getDomainCreateSpec, type CreateField } from "@/lib/domain-create-spec";
import { routeForRecord } from "@/lib/record-route";

type Option={id:string;name?:string;short_name?:string;full_name?:string;email?:string;label?:string;department_id?:string};
type Options={departments:Option[];profiles:Option[];criteria_versions:Option[];indicator_assignments:Option[];fmea_models:Option[]};
const EMPTY:Options={departments:[],profiles:[],criteria_versions:[],indicator_assignments:[],fmea_models:[]};

function normalizedValue(field:CreateField,value:any){if(field.type==="datetime-local"&&value)return new Date(value).toISOString();if(field.type==="number")return value===""?null:Number(value);if(field.type==="checkbox")return !!value;return value||null;}

export function DomainCreateClient({recordType,workYear}:{recordType:string;workYear:number}){
 const router=useRouter();const spec=getDomainCreateSpec(recordType);const [open,setOpen]=useState(false);const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [options,setOptions]=useState<Options>(EMPTY);const [title,setTitle]=useState("");const [department,setDepartment]=useState("");const [owner,setOwner]=useState("");const [values,setValues]=useState<Record<string,any>>({});
 const [similar,setSimilar]=useState<{record_id:string;record_code:string;title:string;department:string;similarity:number}[]>([]);
 useEffect(()=>{if(!open||!spec)return;let active=true;setLoading(true);setError("");fetch(`/api/domain-records?type=${encodeURIComponent(recordType)}&year=${workYear}`).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"Không tải được danh mục.");if(active)setOptions({...EMPTY,...j})}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[open,recordType,workYear,spec]);
 // Gợi ý sự cố có thể trùng — chỉ áp dụng khi đang tạo hồ sơ INCIDENT, không ảnh hưởng các loại hồ sơ khác.
 useEffect(()=>{if(recordType!=="INCIDENT"){setSimilar([]);return}const text=String(values.initial_description||"").trim();if(text.length<8){setSimilar([]);return}let active=true;const timer=setTimeout(()=>{fetch("/api/incidents/similar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,work_year:workYear,department_id:values.incident_location_department_id||null})}).then(r=>r.json()).then(j=>{if(active)setSimilar(Array.isArray(j.items)?j.items:[])}).catch(()=>{if(active)setSimilar([])})},500);return()=>{active=false;clearTimeout(timer)}},[recordType,values.initial_description,values.incident_location_department_id,workYear]);
 const profileOptions=useMemo(()=>department?options.profiles.filter(p=>!p.department_id||p.department_id===department):options.profiles,[options.profiles,department]);
 if(!spec)return null;
 function fieldOptions(field:CreateField){if(field.type==="department")return options.departments.map(x=>({value:x.id,label:x.short_name||x.name||x.id}));if(field.type==="user")return options.profiles.map(x=>({value:x.id,label:x.full_name||x.email||x.id}));if(field.type==="criteria_version")return options.criteria_versions.map(x=>({value:x.id,label:x.label||x.id}));if(field.type==="indicator_assignment")return options.indicator_assignments.map(x=>({value:x.id,label:x.label||x.id}));if(field.type==="fmea_model")return options.fmea_models.map(x=>({value:x.id,label:x.label||x.id}));return field.options||[];}
 function close(){if(saving)return;setOpen(false);setError("");}
 async function submit(e:React.FormEvent){e.preventDefault();setError("");if(!title.trim()){setError("Tên hồ sơ là bắt buộc.");return}if(spec.commonOwner&&!department){setError("Cần chọn khoa/phòng phụ trách.");return}for(const field of spec.fields){if(field.required&&!values[field.key]){setError(`Cần nhập: ${field.label}.`);return}}
  setSaving(true);try{const fields=Object.fromEntries(spec.fields.map(f=>[f.key,normalizedValue(f,values[f.key])]));const res=await fetch("/api/domain-records",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({record_type:recordType,title:title.trim(),work_year:workYear,owner_department_id:department||null,owner_user_id:owner||null,fields})});const json=await res.json();if(!res.ok)throw new Error(json.error||"Không tạo được hồ sơ.");setOpen(false);setTitle("");setDepartment("");setOwner("");setValues({});router.push(routeForRecord(recordType,json.record_id));router.refresh()}catch(e:any){setError(e.message||"Không tạo được hồ sơ.")}finally{setSaving(false)}}
 return <>
  <button className="button primary" onClick={()=>setOpen(true)}>+ {spec.buttonLabel}</button>
  {open?<div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><div className="modal-card domain-create-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><span className="eyebrow">TẠO HỒ SƠ NGHIỆP VỤ</span><h2>{spec.buttonLabel}</h2><p>{spec.intro}</p></div><button className="icon-button" onClick={close} aria-label="Đóng">×</button></div>
   <form onSubmit={submit}><div className="domain-create-grid"><label className="field span-2"><span>Tên hồ sơ *</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Tên ngắn gọn, nhận diện được nội dung..." autoFocus/></label><label className="field"><span>Năm làm việc</span><input value={workYear} disabled/></label>
    {spec.commonOwner?<><label className="field"><span>Khoa/phòng phụ trách *</span><select value={department} onChange={e=>{setDepartment(e.target.value);setOwner("")}}><option value="">Chọn khoa/phòng</option>{options.departments.map(x=><option value={x.id} key={x.id}>{x.short_name||x.name}</option>)}</select></label><label className="field"><span>Người phụ trách</span><select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Chưa gán người</option>{profileOptions.map(x=><option value={x.id} key={x.id}>{x.full_name||x.email}</option>)}</select></label></>:null}
    {spec.fields.map(field=>{const value=values[field.key]??(field.type==="checkbox"?false:"");const choices=fieldOptions(field);const cls=`field ${field.wide?"span-2":""}`;if(field.type==="textarea")return <label className={cls} key={field.key}><span>{field.label}{field.required?" *":""}</span><textarea rows={3} value={value} onChange={e=>setValues(v=>({...v,[field.key]:e.target.value}))} placeholder={field.placeholder}/></label>;if(field.type==="checkbox")return <label className={`${cls} domain-checkbox`} key={field.key}><input type="checkbox" checked={!!value} onChange={e=>setValues(v=>({...v,[field.key]:e.target.checked}))}/><span>{field.label}</span></label>;if(["select","department","user","criteria_version","indicator_assignment","fmea_model"].includes(field.type))return <label className={cls} key={field.key}><span>{field.label}{field.required?" *":""}</span><select value={value} onChange={e=>setValues(v=>({...v,[field.key]:e.target.value}))}><option value="">Chọn...</option>{choices.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>;return <label className={cls} key={field.key}><span>{field.label}{field.required?" *":""}</span><input type={field.type} value={value} onChange={e=>setValues(v=>({...v,[field.key]:e.target.value}))} placeholder={field.placeholder}/></label>})}
   </div>{recordType==="INCIDENT"&&similar.length?<div className="alert warning" style={{marginTop:8}}><strong>Có thể trùng với {similar.length} sự cố gần đây:</strong><ul style={{margin:"6px 0 0",paddingLeft:18}}>{similar.map(s=><li key={s.record_id}>{s.record_code} · {s.title} <small>({Math.round(s.similarity*100)}% giống · {s.department})</small></li>)}</ul><small>Chỉ để tham khảo (so khớp từ ngữ, không phải AI) — vẫn có thể là sự cố khác; không tự động chặn báo cáo.</small></div>:null}{loading?<div className="scope-note">Đang tải danh mục...</div>:null}{error?<div className="alert error">{error}</div>:null}<div className="modal-actions"><button type="button" className="button secondary" onClick={close} disabled={saving}>Hủy</button><button type="submit" className="button primary" disabled={saving||loading}>{saving?"Đang tạo...":"Tạo hồ sơ"}</button></div></form>
  </div></div>:null}
 </>
}
