"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Icon } from "@/components/icon";

type Cat={slug:string;code:string;label:string;description:string;total:number;done:number;blocked:number;completion:number|null};
type Item={id:string;category:string;title:string;description:string|null;status:string;priority?:string;due_date?:string|null;updated_at:string};
type DomainCell={code:string;slug:string;label:string;total:number;done:number;blocked:number;completion:number|null};
type Dept={id:string;name:string;total:number;done:number;open:number;overdue:number;blockers:number;gates:number;gatesPassed:number;completion:number|null;domains:DomainCell[]};
type Escalation=Item & {reasons:string[];score:number};
type Data={generatedAt:string;total:number;completion:number;stale:number;overdue:number;controlCoverage:{owner:number;department:number;deadline:number;gateEvidence:number};gates:{total:number;passed:number;evidenceMissing:number};unassigned:number;criticalOpen:number;counts:Record<string,number>;categories:Cat[];attention:Item[];departmentMatrix:Dept[];upcoming:Item[];escalation:Escalation[]};
const statusLabel:Record<string,string>={TODO:"Chưa làm",IN_PROGRESS:"Đang thực hiện",DONE:"Hoàn tất",BLOCKED:"Bị chặn"};
const tones=["blue","green","orange","purple","cyan","red"];
export function EmrCommandCenter(){
 const [data,setData]=useState<Data|null>(null); const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/emr/dashboard").then(r=>r.json()).then(j=>{if(!j.ok)throw new Error(j.error);setData(j)}).catch(e=>setError(e.message))},[]);
 if(error)return <div className="alert error">{error}</div>; if(!data)return <div className="empty-state">Đang tổng hợp dữ liệu EMR...</div>;
 const blocked=data.counts.BLOCKED||0, active=data.counts.IN_PROGRESS||0, todo=data.counts.TODO||0, done=data.counts.DONE||0;
 const donutTotal=Math.max(1,data.total); const doneDeg=done/donutTotal*360; const activeDeg=(done+active)/donutTotal*360; const todoDeg=(done+active+todo)/donutTotal*360;
 return <div className="emr-command">
  <div className="emr-title"><div><div className="crumb">EMR <b>›</b> Tổng quan</div><h1><span className="title-icon"><Icon name="building-2" size={24}/></span>Trung tâm Điều hành Bệnh án điện tử (EMR)</h1><p>Theo dõi tiến độ triển khai, vận hành và tuân thủ bệnh án điện tử</p></div><div className="emr-filters"><span><Icon name="calendar-days" size={15}/> Dữ liệu đến {new Date(data.generatedAt).toLocaleString("vi-VN",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})}</span><span>Toàn đơn vị⌄</span></div></div>
  <div className="emr-kpis">
   <Kpi icon="gauge" label="Mức độ triển khai EMR" value={`${data.completion}%`} note={`${done}/${data.total} hạng mục hoàn tất`} tone="blue"/>
   <Kpi icon="building-2" label="Cấu phần có dữ liệu" value={`${data.categories.filter(x=>x.total>0).length}/${data.categories.length}`} note="Theo các workstream EMR" tone="green"/>
   <Kpi icon="workflow" label="Đang thực hiện" value={String(active)} note="Hạng mục đang triển khai" tone="orange"/>
   <Kpi icon="shield-check" label="Go-live gates" value={`${data.gates.passed}/${data.gates.total}`} note="Đã đủ bằng chứng & xác minh" tone="purple"/>
   <Kpi icon="calendar-days" label="Quá hạn" value={String(data.overdue)} note={`${data.stale} việc >7 ngày chưa cập nhật`} tone="cyan"/>
   <Kpi icon="circle-alert" label="Vấn đề cần xử lý" value={String(blocked+data.criticalOpen)} note={`${blocked} blocker · ${data.criticalOpen} critical`} tone="red"/>
  </div>

  <div className="hero-grid">
   <section className="emr-panel emr-trend"><PanelHead title="Xu hướng triển khai EMR" sub="Tiến độ theo thời gian sẽ hiển thị khi có dữ liệu lịch sử"/><div className="chart-shell"><div className="yaxis"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div className="chart-area"><div className="gridlines"/><div className="empty-chart"><Icon name="chart-no-axes-column-increasing" size={30}/><b>Chưa có dữ liệu lịch sử</b><span>Dashboard không tạo số liệu minh họa giả.</span></div></div></div><div className="emr-legend"><i className="lg total"/>Tổng hạng mục <i className="lg complete"/>Hoàn tất <i className="lg line"/>Tỷ lệ hoàn thành</div></section>
   <section className="emr-panel emr-distribution"><PanelHead title="Tình trạng triển khai" sub="Phân bố hạng mục theo trạng thái"/><div className="donut-row"><div className="donut" style={{background:`conic-gradient(#22c55e 0 ${doneDeg}deg,#3b82f6 ${doneDeg}deg ${activeDeg}deg,#f59e0b ${activeDeg}deg ${todoDeg}deg,#ef4444 ${todoDeg}deg 360deg)`}}><div><b>{data.total}</b><span>Tổng hạng mục</span></div></div><div className="donut-legend"><Legend c="#22c55e" l="Hoàn tất" v={done}/><Legend c="#3b82f6" l="Đang thực hiện" v={active}/><Legend c="#f59e0b" l="Chưa bắt đầu" v={todo}/><Legend c="#ef4444" l="Bị chặn" v={blocked}/></div></div></section>
  </div>

  <div className="mid-grid">
   <section className="emr-panel"><PanelHead title="Tình trạng sẵn sàng các cấu phần EMR" sub="Tổng hợp trực tiếp từ các module nguồn"/><div className="readiness-grid">{data.categories.map((c,i)=><Link href={`/emr/${c.slug}`} className="ready-card" key={c.code}><div className={`ready-icon ${tones[i%tones.length]}`}><Icon name={i%2?"file-text":"gauge"} size={18}/></div><div className="ready-main"><span>{c.label}</span><strong>{c.completion===null?"—":`${c.completion}%`}</strong><div className="emr-progress"><i style={{width:`${c.completion??0}%`}}/></div></div><em className={c.blocked?"warn":c.completion===100?"ok":"work"}>{c.total===0?"Chưa có dữ liệu":c.blocked?`${c.blocked} blocker`:c.completion===100?"Ổn định":"Đang triển khai"}</em></Link>)}</div></section>
   <section className="emr-panel"><PanelHead title="Chỉ số tuân thủ & dữ liệu điều hành" sub="Độ phủ metadata phục vụ kiểm soát"/><div className="emr-compliance"><Compliance icon="users" label="Có người phụ trách" value={data.controlCoverage.owner}/><Compliance icon="building-2" label="Có khoa/phòng" value={data.controlCoverage.department}/><Compliance icon="calendar-days" label="Có deadline" value={data.controlCoverage.deadline}/><Compliance icon="badge-check" label="Gate DONE đã xác minh" value={data.controlCoverage.gateEvidence}/></div></section>
  </div>

  <div className="bottom-grid">
   <section className="emr-panel emr-matrix-panel"><PanelHead title="Tình trạng triển khai EMR theo khoa/phòng" sub="Ma trận tiến độ, cấu phần và Go-live gate"/>{data.departmentMatrix.length?<div className="matrix-wrap"><table><thead><tr><th>#</th><th>Khoa/Phòng</th><th>Tiến độ</th>{data.categories.slice(0,6).map(c=><th key={c.code}>{c.label}</th>)}<th>Gate</th><th>Vấn đề</th></tr></thead><tbody>{data.departmentMatrix.slice(0,10).map((d,idx)=><tr key={d.id}><td>{idx+1}</td><td><strong>{d.name}</strong></td><td><b>{d.completion===null?"—":`${d.completion}%`}</b></td>{d.domains.slice(0,6).map(c=><td key={c.code}><span className={`status-dot ${c.blocked?"bad":c.completion===100?"good":c.total?"mid":"none"}`}/></td>)}<td><span className={d.gates&&d.gatesPassed===d.gates?"pill good":"pill mid"}>{d.gatesPassed}/{d.gates}</span></td><td className={d.blockers||d.overdue?"danger":""}>{d.blockers+d.overdue}</td></tr>)}</tbody></table></div>:<div className="zero-table"><Icon name="building-2" size={28}/><b>Chưa có dữ liệu khoa/phòng</b><span>Khi hạng mục được gán khoa/phòng, ma trận sẽ tự động hiển thị tại đây.</span></div>}</section>
   <section className="emr-panel emr-action"><PanelHead title="Cảnh báo & công việc cần xử lý" sub="Ưu tiên theo blocker, critical, quá hạn và Go-live gate"/><div className="action-list">{data.escalation.length?data.escalation.slice(0,6).map((x,i)=>{const c=data.categories.find(y=>y.code===x.category);return <Link href={`/emr/${c?.slug||""}`} key={x.id}><span className={`action-icon a${i%4}`}><Icon name="circle-alert" size={17}/></span><div><strong>{x.title}</strong><small>{c?.label} · {x.reasons.slice(0,2).join(" · ").replaceAll("_"," ")}</small></div><b>{x.score}</b><Icon name="chevron-right" size={15}/></Link>}):<div className="zero-action"><span className="action-icon ok"><Icon name="badge-check" size={18}/></span><div><strong>Không có cảnh báo đang mở</strong><small>Dữ liệu nguồn hiện chưa có backlog/blocker cần escalation.</small></div></div>}</div></section>
  </div>
  <div className="principle"><Icon name="info" size={16}/><span><b>Nguyên tắc kiểm soát:</b> Tiến độ công việc không đồng nghĩa Go-live readiness. Gate chỉ PASS khi DONE + có bằng chứng + đã xác minh.</span></div>
  <style jsx>{`
   .emr-command{display:grid;isolation:isolate;gap:14px;color:#102a56}.emr-title{display:flex;justify-content:space-between;align-items:flex-end;gap:18px}.crumb{font-size:11px;color:#4f83d1;font-weight:800;margin-bottom:8px}.crumb b{margin:0 7px;color:#9eb4d2}.emr-title h1{font-size:27px;margin:0;display:flex;align-items:center;gap:10px;color:#092b68}.emr-title p{margin:5px 0 0;color:#7183a1;font-size:13px}.title-icon{width:38px;height:38px;display:grid;place-items:center;border-radius:10px;background:#e8f3ff;color:#2581e8}.emr-filters{display:flex;gap:8px;flex-wrap:wrap}.emr-filters span{display:flex;align-items:center;gap:6px;padding:9px 12px;background:#fff;border:1px solid #dbe7f4;border-radius:9px;font-size:11px;color:#234a80;box-shadow:0 2px 8px rgba(20,60,110,.03)}
   .emr-kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}.emr-command .emr-kpi{background:#fff;border:1px solid #dfe9f5;border-radius:11px;padding:13px;box-shadow:0 5px 16px rgba(30,80,140,.05);min-height:82px}.emr-command .emr-kpi-top{display:flex;gap:10px;align-items:center}.emr-command .emr-kpi-icon{width:38px;height:38px;border-radius:9px;display:grid;place-items:center;color:#fff}.emr-command .emr-kpi.blue .emr-kpi-icon{background:linear-gradient(135deg,#4aa7ff,#2576e8)}.emr-command .emr-kpi.green .emr-kpi-icon{background:linear-gradient(135deg,#39d39f,#16a36f)}.emr-command .emr-kpi.orange .emr-kpi-icon{background:linear-gradient(135deg,#ffb348,#f38b20)}.emr-command .emr-kpi.purple .emr-kpi-icon{background:linear-gradient(135deg,#a777ff,#7751e8)}.emr-command .emr-kpi.cyan .emr-kpi-icon{background:linear-gradient(135deg,#43c7df,#168faf)}.emr-command .emr-kpi.red .emr-kpi-icon{background:linear-gradient(135deg,#ff6666,#ee3f4d)}.emr-command .emr-kpi label{display:block;font-size:10px;font-weight:800;color:#52709a}.emr-command .emr-kpi strong{display:block;font-size:24px;line-height:1.05;margin-top:3px;color:#082b6c}.emr-command .emr-kpi small{display:block;margin-top:8px;font-size:10px;color:#7890ad}
   .emr-panel{background:#fff;border:1px solid #dce7f4;border-radius:11px;box-shadow:0 5px 18px rgba(28,73,128,.05);padding:13px}.emr-panel-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px}.emr-panel-head h2{font-size:15px;margin:0;color:#0a2d69}.emr-panel-head p{font-size:10px;color:#7b8da8;margin:3px 0 0}.hero-grid,.mid-grid,.bottom-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(300px,.9fr);gap:12px}.chart-shell{height:170px;display:grid;grid-template-columns:40px 1fr}.yaxis{display:flex;flex-direction:column;justify-content:space-between;color:#7890ad;font-size:9px;padding:4px 6px 12px 0;text-align:right}.chart-area{position:relative;border-left:1px solid #e5edf7;border-bottom:1px solid #e5edf7}.gridlines{position:absolute;inset:0;background:repeating-linear-gradient(to bottom,transparent 0,transparent calc(25% - 1px),#edf3f9 25%)}.empty-chart{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#9aabc0;gap:5px}.empty-chart b{font-size:12px;color:#5d7393}.empty-chart span{font-size:10px}.emr-legend{display:flex;justify-content:center;align-items:center;gap:7px;font-size:9px;color:#6d829f;margin-top:8px}.lg{width:10px;height:7px;border-radius:2px}.lg.total{background:#b9dcff}.lg.complete{background:#398fe8}.lg.line{height:2px;width:18px;background:#246ed4}.donut-row{height:190px;display:flex;align-items:center;justify-content:center;gap:24px}.donut{width:138px;height:138px;border-radius:50%;display:grid;place-items:center;position:relative}.donut:after{content:"";position:absolute;width:88px;height:88px;background:#fff;border-radius:50%}.donut>div{z-index:1;text-align:center}.donut b{display:block;font-size:23px;color:#092d70}.donut span{font-size:9px;color:#8294ad}.donut-legend{display:grid;gap:10px;min-width:135px}.legend-row{display:grid;grid-template-columns:9px 1fr auto;align-items:center;gap:7px;font-size:10px}.legend-row i{width:8px;height:8px;border-radius:50%}.legend-row b{font-size:12px;color:#12356d}
   .readiness-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.ready-card{position:relative;display:grid;grid-template-columns:34px 1fr;gap:8px;padding:10px;border:1px solid #e2ebf5;border-radius:9px;text-decoration:none;color:inherit;background:#fcfdff;min-height:70px}.ready-icon{width:32px;height:32px;border-radius:8px;display:grid;place-items:center;background:#edf6ff;color:#2681e8}.ready-main span{font-size:10px;color:#4d6991}.ready-main strong{display:block;font-size:16px;color:#092d70;margin-top:2px}.emr-progress{height:5px;background:#e9eff6;border-radius:99px;overflow:hidden;margin-top:6px}.emr-progress i{display:block;height:100%;background:#24bb83;border-radius:99px}.ready-card em{position:absolute;right:8px;top:8px;font-size:8px;font-style:normal;padding:3px 6px;border-radius:99px}.ready-card em.ok{background:#e7f8f0;color:#139467}.ready-card em.warn{background:#fff0ee;color:#dc4b42}.ready-card em.work{background:#fff5df;color:#c77b12}.emr-compliance{display:grid;gap:7px}.emr-compliance-row{display:grid;grid-template-columns:30px 1fr 42px;gap:8px;align-items:center;border:1px solid #e3ebf5;border-radius:8px;padding:8px}.emr-compliance-icon{width:28px;height:28px;display:grid;place-items:center;border-radius:7px;background:#eaf8f2;color:#17a675}.emr-compliance-row label{font-size:10px;color:#526c91}.emr-compliance-row .emr-bar{height:6px;background:#e8eef5;border-radius:99px;overflow:hidden;margin-top:5px}.emr-compliance-row .emr-bar i{display:block;height:100%;background:#22b983}.emr-compliance-row b{text-align:right;color:#0a2d69;font-size:14px}
   .matrix-wrap{overflow:auto}.emr-matrix-panel table{width:100%;border-collapse:collapse;font-size:9px;min-width:720px}.emr-matrix-panel th{background:#f5f9fe;color:#3e5f8d;font-weight:800;padding:7px;border-bottom:1px solid #dfe8f3;white-space:nowrap}.emr-matrix-panel td{text-align:center;padding:8px 6px;border-bottom:1px solid #edf2f7;color:#415d84}.emr-matrix-panel th:nth-child(2),.emr-matrix-panel td:nth-child(2){text-align:left}.status-dot{display:inline-block;width:8px;height:8px;border-radius:50%}.status-dot.good{background:#20b87b}.status-dot.mid{background:#f5ad2d}.status-dot.bad{background:#ef5252}.status-dot.none{background:#aeb9c7}.pill{padding:3px 6px;border-radius:99px;font-size:8px}.pill.good{background:#e7f8f0;color:#138a61}.pill.mid{background:#fff3dd;color:#b66c0e}.danger{color:#e44343!important;font-weight:900}.zero-table{height:160px;display:flex;flex-direction:column;justify-content:center;align-items:center;gap:5px;color:#9aabc0}.zero-table b{font-size:12px;color:#526b8e}.zero-table span{font-size:9px}.action-list{display:grid}.action-list>a,.zero-action{display:grid;grid-template-columns:32px 1fr auto 14px;gap:8px;align-items:center;padding:9px 3px;border-bottom:1px solid #edf2f7;text-decoration:none;color:inherit}.action-list strong{font-size:10px;display:block;color:#173967}.action-list small{font-size:8px;color:#7d90aa;display:block;margin-top:2px}.action-list>a>b{font-size:10px;color:#e04b4b}.action-icon{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#fff0ef;color:#ef4d4d}.action-icon.a1{background:#fff6df;color:#d99417}.action-icon.a2{background:#edf5ff;color:#2c7fe5}.action-icon.a3{background:#f2edff;color:#7955dc}.action-icon.ok{background:#e8f8f1;color:#16996a}.zero-action{grid-template-columns:32px 1fr}.principle{display:flex;gap:8px;align-items:center;padding:9px 12px;border:1px solid #dce8f5;background:#f7fbff;border-radius:9px;color:#607896;font-size:10px}
   @media(max-width:1450px){.emr-kpis{grid-template-columns:repeat(3,1fr)}.readiness-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:1050px){.hero-grid,.mid-grid,.bottom-grid{grid-template-columns:1fr}.emr-title{align-items:flex-start;flex-direction:column}.emr-filters{width:100%}}@media(max-width:700px){.emr-kpis{grid-template-columns:1fr 1fr}.readiness-grid{grid-template-columns:1fr}.emr-title h1{font-size:22px}.donut-row{flex-direction:column;height:auto;padding:10px}.emr-filters span{flex:1}.emr-trend{display:none}}`}</style>
 </div>
}
function PanelHead({title,sub}:{title:string;sub:string}){return <div className="emr-panel-head"><div><h2>{title}</h2><p>{sub}</p></div></div>}
function Legend({c,l,v}:{c:string;l:string;v:number}){return <div className="legend-row"><i style={{background:c}}/><span>{l}</span><b>{v}</b></div>}
function Compliance({icon,label,value}:{icon:string;label:string;value:number}){return <div className="emr-compliance-row"><span className="emr-compliance-icon"><Icon name={icon} size={15}/></span><div><label>{label}</label><div className="emr-bar"><i style={{width:`${value}%`}}/></div></div><b>{value}%</b></div>}
function Kpi({icon,label,value,note,tone}:{icon:string;label:string;value:string;note:string;tone:string}){return <div className={`emr-kpi ${tone}`}><div className="emr-kpi-top"><span className="emr-kpi-icon"><Icon name={icon} size={18}/></span><div><label>{label}</label><strong>{value}</strong></div></div><small>{note}</small></div>}
