"use client";
import {useState} from "react";import {useRouter} from "next/navigation";
type SelfOption={id:string;label:string};type Gap={id:string;criterionRef:string;selfScore:string;externalScore:string;status:string;href:string};
export function ExternalAssessmentWorkflowClient({recordId,lifecycleStatus,canManage,canReview,selfOptions,linkedSelf,gaps,evidence}:{recordId:string;lifecycleStatus:string;canManage:boolean;canReview:boolean;selfOptions:SelfOption[];linkedSelf:SelfOption|null;gaps:Gap[];evidence:number}){const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[selfId,setSelfId]=useState(linkedSelf?.id||""),[form,setForm]=useState({criteria_item_id:"",external_score:"",note:""});
async function run(action:string,payload:Record<string,unknown>={}){setBusy(true);setError("");setNotice("");try{const response=await fetch(`/api/external-assessments/${recordId}/workflow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})}),result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Không xử lý được đánh giá ngoài.");setNotice(result.message);router.refresh()}catch(value){setError(value instanceof Error?value.message:"Không xử lý được đánh giá ngoài.")}finally{setBusy(false)}}
const changed=gaps.filter(x=>Number.isFinite(Number(x.selfScore))&&Number.isFinite(Number(x.externalScore))&&Number(x.selfScore)!==Number(x.externalScore)).length,unchanged=gaps.filter(x=>Number.isFinite(Number(x.selfScore))&&Number.isFinite(Number(x.externalScore))&&Number(x.selfScore)===Number(x.externalScore)).length;
return <section className="panel"><div className="panel-title"><div><h2>Đối chiếu kết quả đánh giá ngoài</h2><p>Điểm bệnh viện được lấy từ đợt tự đánh giá đã chốt. Chỉ nhập điểm đoàn Sở Y tế; hệ thống giữ riêng từng đợt để theo dõi lịch sử.</p></div><strong>{lifecycleStatus}</strong></div><div style={{padding:"0 18px 18px",display:"grid",gap:14}}>{error?<div className="alert error">{error}</div>:null}{notice?<div className="alert success">{notice}</div>:null}<div className="domain-metrics"><div><strong>{gaps.length}</strong><span>Đã nhập điểm SYT</span></div><div><strong>{changed}</strong><span>Có chênh lệch</span></div><div><strong>{unchanged}</strong><span>Không chênh lệch</span></div><div><strong>{evidence}</strong><span>Tài liệu đánh giá ngoài</span></div></div>
{!linkedSelf&&canReview&&lifecycleStatus!=="CLOSED"?<div className="detail-grid"><label><span>Đợt tự đánh giá đã chốt, cùng bộ tiêu chí</span><select value={selfId} onChange={e=>setSelfId(e.target.value)}><option value="">Chọn đợt đối chiếu</option>{selfOptions.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label><div style={{alignSelf:"end"}}><button className="button primary" disabled={busy||!selfId} onClick={()=>run("LINK_SELF",{self_record_id:selfId})}>Chọn đợt đối chiếu</button></div></div>:null}
{linkedSelf?<div className="alert info">Đang đối chiếu với <strong>{linkedSelf.label}</strong>. Kết quả tự đánh giá gốc không bị thay đổi.</div>:null}
{linkedSelf&&canReview&&lifecycleStatus!=="CLOSED"?<div className="page-stack"><h3>Nhập điểm đoàn Sở Y tế</h3><div className="detail-grid"><label><span>Tiêu chí *</span><input value={form.criteria_item_id} onChange={e=>setForm({...form,criteria_item_id:e.target.value})} placeholder="Chọn/nhập mã định danh tiêu chí"/></label><label><span>Điểm đoàn Sở Y tế *</span><input type="number" step="0.01" value={form.external_score} onChange={e=>setForm({...form,external_score:e.target.value})}/></label><label className="wide"><span>Ghi chú (nếu có)</span><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><button className="button primary" disabled={busy||!form.criteria_item_id||form.external_score===""} onClick={()=>run("SAVE_EXTERNAL_SCORE",form)}>Lưu điểm đối chiếu</button></div>:null}
{gaps.length?<div className="table-wrap"><table><thead><tr><th>Tiêu chí</th><th>BV tự đánh giá</th><th>Đoàn SYT</th><th>Chênh lệch</th></tr></thead><tbody>{gaps.map(x=><tr key={x.id}><td><strong>{x.criterionRef}</strong></td><td>{x.selfScore||"—"}</td><td>{x.externalScore}</td><td>{Number.isFinite(Number(x.externalScore))&&Number.isFinite(Number(x.selfScore))?Number(x.externalScore)-Number(x.selfScore):"—"}</td></tr>)}</tbody></table></div>:null}
{linkedSelf&&canManage&&lifecycleStatus!=="CLOSED"?<button className="button primary" disabled={busy||gaps.length<1} onClick={()=>{const comment=window.prompt("Kết luận đối chiếu đánh giá ngoài:");if(comment?.trim())run("CLOSE_COMPARISON",{comment:comment.trim()})}}>Chốt đối chiếu</button>:null}</div></section>}