"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

const LABEL: Record<string,string>={RECEIVED:"Tiếp nhận",TRIAGED:"Phân loại",COORDINATING:"Xử lý / xác minh",RESPONDED:"Đã phản hồi",CLOSED:"Đã đóng"};
const STEPS=[["RECEIVED","1 · Tiếp nhận"],["TRIAGED","2 · Phân loại"],["COORDINATING","3 · Xử lý / xác minh"],["RESPONDED","4 · Phản hồi"],["CLOSED","5 · Đóng"]];
export function FeedbackWorkflowClient({recordId,status,canManage,evidence,finding}:{recordId:string;status:string;canManage:boolean;evidence:number;finding:{href:string;status:string}|null}){
 const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [comment,setComment]=useState("");const [findingDue,setFindingDue]=useState("");
 async function run(action:string,payload:Record<string,unknown>={}){setBusy(true);setError("");setNotice("");try{const response=await fetch(`/api/feedback/${recordId}/workflow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Không xử lý được ý kiến khách hàng.");setNotice(result.message);setComment("");router.refresh()}catch(value){setError(value instanceof Error?value.message:"Không xử lý được ý kiến khách hàng.")}finally{setBusy(false)}}
 const idx=Math.max(0,STEPS.findIndex(([key])=>key===status));const needsText=["RECEIVED","TRIAGED","COORDINATING","RESPONDED"].includes(status);
 return <section className="panel"><div className="panel-title"><div><h2>Luồng ý kiến khách hàng</h2><p>Tiếp nhận → Phân loại → Xử lý/xác minh khi cần → Phản hồi → Đóng. Finding/Action/CAPA là luồng khắc phục riêng khi có vấn đề hệ thống.</p></div><strong>{LABEL[status]||status}</strong></div><div style={{padding:"0 18px 18px",display:"grid",gap:12}}>
  <div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(0,1fr))",gap:6}}>{STEPS.map(([key,label],i)=><div key={key} style={{padding:"8px 6px",borderRadius:9,textAlign:"center",fontSize:11,fontWeight:750,background:i<=idx?"#e6fbf8":"#f2f5f7",color:i<=idx?"#0d6f68":"#74828a"}}>{label}</div>)}</div>
  {error?<div className="alert error">{error}</div>:null}{notice?<div className="alert success">{notice}</div>:null}
  {finding?<div className="alert info">Đã sinh Finding hệ thống: <Link href={finding.href}><strong>{finding.status}</strong></Link>. Có thể tiếp tục phản hồi/đóng ý kiến khách hàng mà không chờ Finding hoàn tất.</div>:null}
  {canManage&&needsText?<label><span>{status==="RECEIVED"?"Kết quả phân loại / mức ảnh hưởng":status==="RESPONDED"?"Kết luận trước khi đóng":"Nội dung xử lý / phản hồi khách hàng"}</span><textarea rows={3} value={comment} onChange={e=>setComment(e.target.value)} placeholder={status==="RECEIVED"?"Ví dụ: Góp ý thông thường, cần Khoa Khám bệnh phối hợp xác minh...":status==="RESPONDED"?"Tóm tắt kết quả và lý do đóng hồ sơ...":"Ghi kết quả thực tế; không nhập lại nội dung ý kiến ban đầu."}/></label>:null}
  {canManage&&status==="RECEIVED"?<button className="button primary" disabled={busy||!comment.trim()} onClick={()=>run("TRIAGE",{comment:comment.trim()})}>Hoàn tất phân loại</button>:null}
  {canManage&&status==="TRIAGED"?<div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="button secondary" disabled={busy} onClick={()=>run("START_COORDINATION")}>Cần phối hợp xác minh</button><button className="button primary" disabled={busy||!comment.trim()} onClick={()=>run("MARK_RESPONDED",{comment:comment.trim()})}>Đã xử lý và phản hồi</button></div>:null}
  {canManage&&["TRIAGED","COORDINATING"].includes(status)&&!finding?<details><summary style={{cursor:"pointer",fontWeight:750}}>Có vấn đề hệ thống cần khắc phục?</summary><div style={{display:"grid",gap:8,marginTop:10}}><input type="date" value={findingDue} onChange={e=>setFindingDue(e.target.value)}/><button className="button secondary" disabled={busy||!comment.trim()||!findingDue} onClick={()=>run("CREATE_FINDING",{comment:comment.trim(),due_date:findingDue,severity:"MAJOR"})}>Tạo Finding từ nội dung xử lý</button></div></details>:null}
  {canManage&&status==="COORDINATING"?<button className="button primary" disabled={busy||!comment.trim()} onClick={()=>run("MARK_RESPONDED",{comment:comment.trim()})}>Xác nhận đã phản hồi khách hàng</button>:null}
  {canManage&&status==="RESPONDED"?<button className="button primary" disabled={busy||!comment.trim()} onClick={()=>run("CLOSE",{comment:comment.trim()})}>Đóng ý kiến khách hàng</button>:null}
  <div className="tiny muted">Minh chứng hiện có: {evidence}. Minh chứng hỗ trợ truy vết khi cần, không còn là điều kiện cứng cho mọi ý kiến thông thường.</div>
 </div></section>
}