"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
const LABELS: Record<string, string> = { DRAFT: "Nháp", PENDING_APPROVAL: "Chờ phê duyệt", IN_PROGRESS: "Đang can thiệp", RESIDUAL_REVIEW: "Re-score residual risk", CLOSED: "Đã đóng" };
type Option = { id: string; label: string };
type Step = { id: string; no: number; name: string; description: string; department: string };
type Mode = { id: string; step: string; mode: string; effect: string; cause: string; control: string; high: boolean };

export function FmeaWorkflowClient({ recordId, status, canManage, hasModel, steps, modes, highPriority, actions, incomplete, evidence, departments, stepRows, modeRows }: { recordId: string; status: string; canManage: boolean; hasModel: boolean; steps: number; modes: number; highPriority: number; actions: number; incomplete: number; evidence: number; departments: Option[]; stepRows: Step[]; modeRows: Mode[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [step, setStep] = useState({ step_no: String(stepRows.length + 1), step_name: "", description: "", responsible_department_id: "" });
  const [mode, setMode] = useState({ process_step_id: "", failure_mode: "", potential_effect: "", potential_cause: "", current_control: "", is_high_priority: false });
  async function call(url: string, action: string, payload: Record<string, unknown> = {}) { setBusy(true); setError(""); setNotice(""); try { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const json = await response.json().catch(() => ({})); if (!response.ok) throw new Error(json.error || "Không xử lý được FMEA."); setNotice(json.message); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không xử lý được FMEA."); } finally { setBusy(false); } }
  const cmd = (action: string, payload: Record<string, unknown> = {}) => call(`/api/fmea/${recordId}/workflow`, action, payload);
  const setup = (action: string, payload: Record<string, unknown>) => call(`/api/fmea/${recordId}/setup`, action, payload);
  return <section className="panel"><div className="panel-title"><div><h2>FMEA/HFMEA Workflow</h2><p>Quy trình → failure mode → ưu tiên → Action → re-score → residual risk.</p></div><strong>{LABELS[status] || status}</strong></div><div style={{ padding: "0 18px 18px", display: "grid", gap: 14 }}>
    {error ? <div className="alert error">{error}</div> : null}{notice ? <div className="alert success">{notice}</div> : null}
    <div className="domain-metrics"><div><strong>{hasModel ? "Có" : "Thiếu"}</strong><span>Mô hình điểm</span></div><div><strong>{steps}</strong><span>Bước quy trình</span></div><div><strong>{modes}</strong><span>Failure mode</span></div><div><strong>{highPriority}</strong><span>Ưu tiên cao</span></div><div><strong>{actions}/{incomplete}</strong><span>Action/chưa xong</span></div><div><strong>{evidence}</strong><span>Minh chứng</span></div></div>
    {status === "DRAFT" && canManage ? <><div className="page-stack"><h3>1. Thêm bước quy trình</h3><div className="detail-grid"><label><span>Thứ tự *</span><input type="number" min="1" value={step.step_no} onChange={(e) => setStep({ ...step, step_no: e.target.value })} /></label><label><span>Tên bước *</span><input value={step.step_name} onChange={(e) => setStep({ ...step, step_name: e.target.value })} /></label><label><span>Khoa/phòng phụ trách</span><select value={step.responsible_department_id} onChange={(e) => setStep({ ...step, responsible_department_id: e.target.value })}><option value="">Chọn...</option>{departments.map((x) => <option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label className="wide"><span>Mô tả</span><textarea rows={2} value={step.description} onChange={(e) => setStep({ ...step, description: e.target.value })} /></label></div><button className="button secondary" disabled={busy || !step.step_no || !step.step_name} onClick={() => setup("ADD_STEP", step)}>Thêm bước</button></div>
    <div className="page-stack"><h3>2. Thêm failure mode</h3><div className="detail-grid"><label><span>Bước quy trình *</span><select value={mode.process_step_id} onChange={(e) => setMode({ ...mode, process_step_id: e.target.value })}><option value="">Chọn...</option>{stepRows.map((x) => <option key={x.id} value={x.id}>{x.no}. {x.name}</option>)}</select></label><label><span>Failure mode *</span><input value={mode.failure_mode} onChange={(e) => setMode({ ...mode, failure_mode: e.target.value })} /></label><label className="wide"><span>Hậu quả tiềm ẩn</span><textarea rows={2} value={mode.potential_effect} onChange={(e) => setMode({ ...mode, potential_effect: e.target.value })} /></label><label className="wide"><span>Nguyên nhân tiềm ẩn</span><textarea rows={2} value={mode.potential_cause} onChange={(e) => setMode({ ...mode, potential_cause: e.target.value })} /></label><label className="wide"><span>Kiểm soát hiện tại</span><textarea rows={2} value={mode.current_control} onChange={(e) => setMode({ ...mode, current_control: e.target.value })} /></label><label className="domain-checkbox"><input type="checkbox" checked={mode.is_high_priority} onChange={(e) => setMode({ ...mode, is_high_priority: e.target.checked })} /><span>Đánh dấu ưu tiên cao theo đánh giá chuyên môn</span></label></div><button className="button secondary" disabled={busy || !mode.process_step_id || !mode.failure_mode} onClick={() => setup("ADD_MODE", mode)}>Thêm failure mode</button></div></> : null}
    {stepRows.length ? <div className="table-wrap"><table><thead><tr><th>Bước</th><th>Mô tả</th><th>Phụ trách</th></tr></thead><tbody>{stepRows.map((x) => <tr key={x.id}><td><strong>{x.no}. {x.name}</strong></td><td>{x.description || "—"}</td><td>{x.department || "—"}</td></tr>)}</tbody></table></div> : null}
    {modeRows.length ? <div className="table-wrap"><table><thead><tr><th>Bước</th><th>Failure mode</th><th>Hậu quả</th><th>Nguyên nhân</th><th>Kiểm soát</th><th>Ưu tiên</th></tr></thead><tbody>{modeRows.map((x) => <tr key={x.id}><td>{x.step}</td><td><strong>{x.mode}</strong></td><td>{x.effect || "—"}</td><td>{x.cause || "—"}</td><td>{x.control || "—"}</td><td>{x.high ? "Cao" : "Thường"}</td></tr>)}</tbody></table></div> : null}
    {status === "DRAFT" && canManage ? <button className="button primary" disabled={busy || !hasModel || steps < 1 || modes < 1} onClick={() => cmd("SUBMIT")}>Gửi phê duyệt FMEA</button> : null}
    {status === "PENDING_APPROVAL" && canManage ? <button className="button primary" disabled={busy} onClick={() => cmd("APPROVE")}>Phê duyệt triển khai</button> : null}
    {status === "IN_PROGRESS" && canManage ? <button className="button primary" disabled={busy || (highPriority > 0 && actions < 1) || incomplete > 0 || evidence < 1} onClick={() => cmd("REQUEST_RESIDUAL_REVIEW")}>Chuyển re-score residual risk</button> : null}
    {status === "RESIDUAL_REVIEW" && canManage ? <button className="button primary" disabled={busy} onClick={() => { const conclusion = window.prompt("Kết luận re-score và chấp nhận residual risk:"); if (conclusion?.trim()) cmd("CLOSE", { comment: conclusion.trim() }); }}>Chấp nhận residual risk & đóng</button> : null}
  </div></section>;
}
