"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

const L: Record<string, string> = { DRAFT: "Nháp", PENDING_APPROVAL: "Chờ phê duyệt", APPROVED: "Đã phê duyệt", IN_PROGRESS: "Đang PDSA", EVALUATED: "Đã đánh giá đạt", CLOSED: "Đã đóng" };
const PHASE_LABEL: Record<string, string> = { PLAN: "Plan", DO: "Do", STUDY: "Study", ACT: "Act" };
const MILESTONE_STATUS_LABEL: Record<string, string> = { PLANNED: "Dự kiến", IN_PROGRESS: "Đang thực hiện", COMPLETED: "Hoàn thành" };
const ACT_LABEL: Record<string, string> = { ADOPT: "Adopt · Chuẩn hóa", ADAPT: "Adapt · Điều chỉnh", ABANDON: "Abandon · Dừng thử nghiệm" };

type Objective = { id: string; order: number; statement: string; indicator: string | null; baseline: string | null; target: string | null; unit: string | null; due_date: string | null };
type Milestone = { id: string; order: number; title: string; phase: string; description: string | null; start_date: string | null; end_date: string | null; status: string; study_result: string | null; learning_summary: string | null; act_decision: string | null };
type Props = { recordId: string; status: string; canManage: boolean; objectives: number; milestones: number; actions: number; incomplete: number; evidence: number };

export function ImprovementProjectWorkflowClient({ recordId, status, canManage, objectives, milestones, actions, incomplete, evidence }: Props) {
  const router = useRouter();
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [summary, setSummary] = useState(""); const [result, setResult] = useState("ACHIEVED"); const [sustain, setSustain] = useState(true); const [scale, setScale] = useState(false);
  const [setupLoading, setSetupLoading] = useState(false); const [setupReady, setSetupReady] = useState(false); const [objectiveRows, setObjectiveRows] = useState<Objective[]>([]); const [milestoneRows, setMilestoneRows] = useState<Milestone[]>([]); const [projectStart, setProjectStart] = useState(""); const [projectEnd, setProjectEnd] = useState("");
  const [editingObjectiveId, setEditingObjectiveId] = useState<string | null>(null); const [objectiveStatement, setObjectiveStatement] = useState(""); const [indicator, setIndicator] = useState(""); const [baseline, setBaseline] = useState(""); const [target, setTarget] = useState(""); const [unit, setUnit] = useState(""); const [objectiveDue, setObjectiveDue] = useState("");
  const [editingMilestoneId, setEditingMilestoneId] = useState<string | null>(null); const [milestoneTitle, setMilestoneTitle] = useState(""); const [phase, setPhase] = useState("PLAN"); const [milestoneDescription, setMilestoneDescription] = useState(""); const [milestoneStart, setMilestoneStart] = useState(""); const [milestoneEnd, setMilestoneEnd] = useState("");

  const liveObjectives = setupReady ? objectiveRows.length : objectives; const liveMilestones = setupReady ? milestoneRows.length : milestones;
  const incompleteMilestones = setupReady ? milestoneRows.filter((item) => item.status !== "COMPLETED").length : liveMilestones; const completedMilestones = Math.max(liveMilestones - incompleteMilestones, 0); const milestoneEditable = ["DRAFT", "APPROVED", "IN_PROGRESS"].includes(status);
  const phasesPresent = useMemo(() => new Set(milestoneRows.map((x) => x.phase)), [milestoneRows]);
  const missingPhases = ["PLAN", "DO", "STUDY", "ACT"].filter((x) => !phasesPresent.has(x));
  const learningReady = milestoneRows.some((x) => x.phase === "STUDY" && x.status === "COMPLETED" && x.study_result && x.learning_summary) && milestoneRows.some((x) => x.phase === "ACT" && x.status === "COMPLETED" && x.act_decision);

  const loadSetup = useCallback(async () => { if (!canManage) return; setSetupLoading(true); try { const response = await fetch(`/api/improvement/projects/${recordId}/setup`, { cache: "no-store" }); const json = await response.json().catch(() => ({})); if (!response.ok) throw new Error(json.error || "Không đọc được dữ liệu SMART/PDSA."); setObjectiveRows(Array.isArray(json.objectives) ? json.objectives : []); setMilestoneRows(Array.isArray(json.milestones) ? json.milestones : []); setProjectStart(json.start_date || ""); setProjectEnd(json.target_end_date || ""); setSetupReady(true); } catch (e) { setError(e instanceof Error ? e.message : "Không đọc được dữ liệu SMART/PDSA."); } finally { setSetupLoading(false); } }, [recordId, canManage]);
  useEffect(() => { void loadSetup(); }, [loadSetup]);

  async function cmd(action: string, payload: Record<string, unknown> = {}) { setBusy(true); setError(""); setNotice(""); try { const response = await fetch(`/api/improvement/projects/${recordId}/workflow`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const json = await response.json().catch(() => ({})); if (!response.ok) throw new Error(json.error || "Không xử lý được đề án."); setNotice(json.message || "Đã cập nhật đề án."); router.refresh(); await loadSetup(); return true; } catch (e) { setError(e instanceof Error ? e.message : "Không xử lý được đề án."); return false; } finally { setBusy(false); } }
  async function setupCmd(action: string, payload: Record<string, unknown>) { setBusy(true); setError(""); setNotice(""); try { const response = await fetch(`/api/improvement/projects/${recordId}/setup`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const json = await response.json().catch(() => ({})); if (!response.ok) throw new Error(json.error || "Không lưu được dữ liệu SMART/PDSA."); setNotice(json.message || "Đã lưu."); await loadSetup(); router.refresh(); return true; } catch (e) { setError(e instanceof Error ? e.message : "Không lưu được dữ liệu SMART/PDSA."); return false; } finally { setBusy(false); } }

  async function milestoneStatusCmd(item: Milestone, action: "START" | "COMPLETE" | "RESET" | "REOPEN") {
    if (busy) return; let reason = ""; const payload: Record<string, unknown> = { milestone_id: item.id, action };
    if (action === "RESET" || action === "REOPEN") { const answer = window.prompt(action === "RESET" ? `Lý do hoàn milestone “${item.title}” về Dự kiến:` : `Lý do mở lại milestone “${item.title}”:`); if (!answer?.trim()) return; reason = answer.trim(); }
    if (action === "COMPLETE" && item.phase === "STUDY") { const measured = window.prompt("Kết quả đo lường/so sánh sau can thiệp:", item.study_result || ""); if (!measured?.trim()) return; const learning = window.prompt("Bài học rút ra từ kết quả Study:", item.learning_summary || ""); if (!learning?.trim()) return; payload.study_result = measured.trim(); payload.learning_summary = learning.trim(); }
    if (action === "COMPLETE" && item.phase === "ACT") { const decision = window.prompt("Quyết định ACT: nhập ADOPT (chuẩn hóa), ADAPT (điều chỉnh) hoặc ABANDON (dừng):", item.act_decision || "ADOPT")?.trim().toUpperCase(); if (!decision || !["ADOPT", "ADAPT", "ABANDON"].includes(decision)) { setError("Quyết định ACT phải là ADOPT, ADAPT hoặc ABANDON."); return; } payload.act_decision = decision; }
    if (action === "COMPLETE" && !["STUDY", "ACT"].includes(item.phase) && !window.confirm(`Xác nhận milestone “${item.title}” đã hoàn thành?`)) return;
    payload.reason = reason; setBusy(true); setError(""); setNotice(""); try { const response = await fetch(`/api/improvement/projects/${recordId}/milestones/status`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const json = await response.json().catch(() => ({})); if (!response.ok) throw new Error(json.error || "Không cập nhật được trạng thái milestone PDSA."); setNotice(json.message || "Đã cập nhật milestone PDSA."); await loadSetup(); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Không cập nhật được trạng thái milestone PDSA."); } finally { setBusy(false); }
  }

  function resetObjectiveForm() { setEditingObjectiveId(null); setObjectiveStatement(""); setIndicator(""); setBaseline(""); setTarget(""); setUnit(""); setObjectiveDue(""); }
  function editObjective(item: Objective) { setEditingObjectiveId(item.id); setObjectiveStatement(item.statement); setIndicator(item.indicator || ""); setBaseline(item.baseline || ""); setTarget(item.target || ""); setUnit(item.unit || ""); setObjectiveDue(item.due_date || ""); setError(""); setNotice(""); }
  async function submitObjective(e: FormEvent) { e.preventDefault(); const ok = await setupCmd(editingObjectiveId ? "UPDATE_OBJECTIVE" : "ADD_OBJECTIVE", { objective_id: editingObjectiveId || undefined, statement: objectiveStatement, indicator, baseline, target, unit, due_date: objectiveDue }); if (ok) resetObjectiveForm(); }
  async function deleteObjective(item: Objective) { const reason = window.prompt(`Lý do xóa mục tiêu SMART #${item.order}:`); if (!reason?.trim() || !window.confirm("Xóa mục tiêu SMART nháp này? Thao tác sẽ được ghi audit trail.")) return; const ok = await setupCmd("DELETE_OBJECTIVE", { objective_id: item.id, reason: reason.trim() }); if (ok && editingObjectiveId === item.id) resetObjectiveForm(); }
  function resetMilestoneForm() { setEditingMilestoneId(null); setMilestoneTitle(""); setPhase("PLAN"); setMilestoneDescription(""); setMilestoneStart(""); setMilestoneEnd(""); }
  function editMilestone(item: Milestone) { setEditingMilestoneId(item.id); setMilestoneTitle(item.title); setPhase(item.phase || "PLAN"); setMilestoneDescription(item.description || ""); setMilestoneStart(item.start_date || ""); setMilestoneEnd(item.end_date || ""); setError(""); setNotice(""); }
  async function submitMilestone(e: FormEvent) { e.preventDefault(); const ok = await setupCmd(editingMilestoneId ? "UPDATE_MILESTONE" : "ADD_MILESTONE", { milestone_id: editingMilestoneId || undefined, title: milestoneTitle, phase, description: milestoneDescription, start_date: milestoneStart, end_date: milestoneEnd }); if (ok) resetMilestoneForm(); }
  async function deleteMilestone(item: Milestone) { const reason = window.prompt(`Lý do xóa milestone “${item.title}”:`); if (!reason?.trim() || !window.confirm("Xóa milestone PDSA nháp này? Thao tác sẽ được ghi audit trail.")) return; const ok = await setupCmd("DELETE_MILESTONE", { milestone_id: item.id, reason: reason.trim() }); if (ok && editingMilestoneId === item.id) resetMilestoneForm(); }
  function evaluate(e: FormEvent) { e.preventDefault(); void cmd("EVALUATE", { objective_achievement_summary: summary, overall_result: result, sustainability_required: sustain, scaleout_recommended: scale }); }
  const phaseSummary = useMemo(() => ["PLAN", "DO", "STUDY", "ACT"].map((key) => ({ key, count: milestoneRows.filter((item) => item.phase === key).length })), [milestoneRows]);

  return <section className="panel"><div style={{ padding: 18, display: "flex", justifyContent: "space-between", gap: 12 }}><div><h2 style={{ margin: 0, fontSize: 18 }}>Improvement Project · SMART & PDSA</h2><p style={{ color: "#64748b", fontSize: 12 }}>Baseline → SMART → Plan → Do → Study → Act → Action → minh chứng → duy trì/nhân rộng.</p></div><strong>{L[status] || status}</strong></div>
    <div style={{ padding: "0 18px 18px", display: "grid", gap: 14 }}>{error ? <div className="alert error">{error}</div> : null}{notice ? <div className="alert success">{notice}</div> : null}
      <div className="domain-metrics"><div><strong>{liveObjectives}</strong><span>Mục tiêu SMART</span></div><div><strong>{completedMilestones}/{liveMilestones}</strong><span>Milestone hoàn thành</span></div><div><strong>{actions}/{incomplete}</strong><span>Action / chưa xong</span></div><div><strong>{evidence}</strong><span>Minh chứng</span></div></div>
      {canManage ? <div className="alert" style={{ fontSize: 12 }}><strong>Khung thời gian:</strong> {projectStart || "chưa đặt"} → {projectEnd || "chưa đặt"}. Trước phê duyệt phải đủ SMART và cả 4 pha PDSA. STUDY phải lưu kết quả + bài học; ACT phải có quyết định Adopt/Adapt/Abandon.</div> : null}
      {status === "DRAFT" && canManage ? <section style={{ display: "grid", gap: 10 }}><h3 style={{ margin: 0, fontSize: 15 }}>1. Mục tiêu SMART</h3><form onSubmit={submitObjective} className="domain-detail-grid"><label className="wide">Mục tiêu cụ thể *<textarea rows={3} value={objectiveStatement} onChange={(e) => setObjectiveStatement(e.target.value)} required /></label><label className="wide">Chỉ số đo lường *<input value={indicator} onChange={(e) => setIndicator(e.target.value)} required /></label><label>Baseline *<input value={baseline} onChange={(e) => setBaseline(e.target.value)} required /></label><label>Target *<input value={target} onChange={(e) => setTarget(e.target.value)} required /></label><label>Đơn vị<input value={unit} onChange={(e) => setUnit(e.target.value)} /></label><label>Hạn đạt *<input type="date" min={projectStart || undefined} max={projectEnd || undefined} value={objectiveDue} onChange={(e) => setObjectiveDue(e.target.value)} required /></label><div style={{ display: "flex", gap: 8 }}><button className="button secondary" disabled={busy || setupLoading}>{editingObjectiveId ? "Lưu mục tiêu" : "Thêm mục tiêu"}</button>{editingObjectiveId ? <button type="button" className="button tertiary" onClick={resetObjectiveForm}>Hủy</button> : null}</div></form></section> : null}
      {canManage && objectiveRows.length ? <div style={{ overflowX: "auto" }}><table className="data-table"><thead><tr><th>#</th><th>Mục tiêu</th><th>Chỉ số</th><th>Baseline</th><th>Target</th><th>Hạn</th>{status === "DRAFT" ? <th>Thao tác</th> : null}</tr></thead><tbody>{objectiveRows.map((item) => <tr key={item.id}><td>{item.order}</td><td>{item.statement}</td><td>{item.indicator || "—"}</td><td>{item.baseline || "—"}</td><td>{item.target || "—"}{item.unit ? ` ${item.unit}` : ""}</td><td>{item.due_date || "—"}</td>{status === "DRAFT" ? <td><button type="button" className="button tertiary small" onClick={() => editObjective(item)}>Sửa</button> <button type="button" className="button danger small" onClick={() => void deleteObjective(item)}>Xóa</button></td> : null}</tr>)}</tbody></table></div> : null}
      {canManage && milestoneEditable ? <section style={{ display: "grid", gap: 10 }}><h3 style={{ margin: 0, fontSize: 15 }}>2. Chu trình PDSA</h3><form onSubmit={submitMilestone} className="domain-detail-grid"><label className="wide">Milestone *<input value={milestoneTitle} onChange={(e) => setMilestoneTitle(e.target.value)} required /></label><label>Pha *<select value={phase} onChange={(e) => setPhase(e.target.value)}><option value="PLAN">Plan</option><option value="DO">Do</option><option value="STUDY">Study</option><option value="ACT">Act</option></select></label><label className="wide">Mô tả<textarea rows={2} value={milestoneDescription} onChange={(e) => setMilestoneDescription(e.target.value)} /></label><label>Bắt đầu<input type="date" min={projectStart || undefined} max={projectEnd || undefined} value={milestoneStart} onChange={(e) => setMilestoneStart(e.target.value)} /></label><label>Kết thúc<input type="date" min={projectStart || undefined} max={projectEnd || undefined} value={milestoneEnd} onChange={(e) => setMilestoneEnd(e.target.value)} /></label><div><button className="button secondary" disabled={busy}>{editingMilestoneId ? "Lưu milestone" : "Thêm milestone"}</button></div></form></section> : null}
      {canManage && milestoneRows.length ? <><div className="domain-metrics">{phaseSummary.map((x) => <div key={x.key}><strong>{x.count}</strong><span>{PHASE_LABEL[x.key]}</span></div>)}</div><div style={{ overflowX: "auto" }}><table className="data-table"><thead><tr><th>#</th><th>PDSA</th><th>Milestone / học tập</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{milestoneRows.map((item) => { const canStart = status === "IN_PROGRESS" && item.status === "PLANNED"; const canComplete = status === "IN_PROGRESS" && item.status === "IN_PROGRESS"; const canReopen = status === "IN_PROGRESS" && item.status === "COMPLETED"; return <tr key={item.id}><td>{item.order}</td><td>{PHASE_LABEL[item.phase] || item.phase}</td><td><strong>{item.title}</strong>{item.description ? <div className="muted">{item.description}</div> : null}{item.study_result ? <div><b>Kết quả:</b> {item.study_result}</div> : null}{item.learning_summary ? <div><b>Bài học:</b> {item.learning_summary}</div> : null}{item.act_decision ? <div><b>Quyết định:</b> {ACT_LABEL[item.act_decision] || item.act_decision}</div> : null}</td><td>{MILESTONE_STATUS_LABEL[item.status] || item.status}</td><td>{canStart ? <button className="button primary small" onClick={() => void milestoneStatusCmd(item, "START")}>Bắt đầu</button> : null}{canComplete ? <button className="button primary small" onClick={() => void milestoneStatusCmd(item, "COMPLETE")}>Hoàn thành</button> : null}{canReopen ? <button className="button tertiary small" onClick={() => void milestoneStatusCmd(item, "REOPEN")}>Mở lại</button> : null}{item.status === "PLANNED" && milestoneEditable ? <button className="button tertiary small" onClick={() => editMilestone(item)}>Sửa</button> : null}{status === "DRAFT" && item.status === "PLANNED" ? <button className="button danger small" onClick={() => void deleteMilestone(item)}>Xóa</button> : null}</td></tr>; })}</tbody></table></div></> : null}
      {status === "DRAFT" && canManage ? <><button className="button primary" disabled={busy || liveObjectives < 1 || liveMilestones < 1 || missingPhases.length > 0} onClick={() => void cmd("SUBMIT")}>Gửi phê duyệt</button>{missingPhases.length ? <div className="alert">Chu trình chưa đủ: <strong>{missingPhases.join(", ")}</strong>.</div> : null}</> : null}
      {status === "PENDING_APPROVAL" && canManage ? <button className="button primary" disabled={busy} onClick={() => void cmd("APPROVE")}>Phê duyệt đề án</button> : null}{status === "APPROVED" && canManage ? <button className="button primary" disabled={busy} onClick={() => void cmd("START")}>Bắt đầu triển khai PDSA</button> : null}
      {status === "IN_PROGRESS" && canManage ? <>{incompleteMilestones > 0 ? <div className="alert">Còn <strong>{incompleteMilestones}</strong> milestone chưa hoàn thành.</div> : null}{!learningReady ? <div className="alert">Chưa đủ Study → Act: cần kết quả + bài học ở STUDY và quyết định Adopt/Adapt/Abandon ở ACT.</div> : null}<form onSubmit={evaluate} className="domain-detail-grid"><label className="wide">Đánh giá mức đạt mục tiêu *<textarea rows={4} value={summary} onChange={(e) => setSummary(e.target.value)} required /></label><label>Kết quả<select value={result} onChange={(e) => setResult(e.target.value)}><option value="ACHIEVED">Đạt</option><option value="PARTIAL">Đạt một phần</option><option value="NOT_ACHIEVED">Chưa đạt</option></select></label><label><input type="checkbox" checked={sustain} onChange={(e) => setSustain(e.target.checked)} /> Cần duy trì</label><label><input type="checkbox" checked={scale} onChange={(e) => setScale(e.target.checked)} /> Đề xuất nhân rộng</label><button className="button primary" disabled={busy || incompleteMilestones > 0 || !learningReady || actions < 1 || incomplete > 0 || evidence < 1}>Đánh giá kết quả</button></form></> : null}
      {status === "EVALUATED" && canManage ? <button className="button primary" disabled={busy} onClick={() => { const x = window.prompt("Kết luận duy trì/nhân rộng:"); if (x?.trim()) void cmd("CLOSE", { comment: x.trim() }); }}>Đóng đề án</button> : null}
    </div></section>;
}
