"use client";
import {FormEvent,useMemo,useState} from "react";import {useRouter} from "next/navigation";
import {matchNC3} from "@/lib/nc3-classifier";
import {IncidentContributingFactorsClient} from "@/components/incident-contributing-factors-client";
import {IncidentRcaWorkspaceClient} from "@/components/incident-rca-workspace-client";
const LABEL:Record<string,string>={REPORTED:"Mới báo cáo",RETURNED:"Cần bổ sung",TRIAGED:"Đã xác minh",INVESTIGATION_REQUIRED:"Cần điều tra",INVESTIGATING:"Đang điều tra",ACTION_FOLLOW_UP:"Theo dõi hành động",AWAITING_CLOSURE:"Chờ đóng",CLOSED:"Đã đóng",REJECTED:"Đã từ chối (không phải sự cố)"};
export function IncidentWorkflowClient({recordId,status,canTriage,canInvestigate,canClose,initialSafetyRecorded,investigationRequired,rcaRequired,actionCount,incompleteActionCount,evidenceCount}:{recordId:string;status:string;canTriage:boolean;canInvestigate:boolean;canClose:boolean;initialSafetyRecorded:boolean;investigationRequired:boolean;rcaRequired:boolean;actionCount:number;incompleteActionCount:number;evidenceCount:number}){
 const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[verified,setVerified]=useState("");const[harm,setHarm]=useState("NO_HARM");const[serious,setSerious]=useState(false);const[needInv,setNeedInv]=useState(false);const[needRca,setNeedRca]=useState(false);const[invType,setInvType]=useState("STANDARD");const[eventSummary,setEventSummary]=useState("");const[harmConclusion,setHarmConclusion]=useState("");const[conclusion,setConclusion]=useState("");const[rcaReady,setRcaReady]=useState(!rcaRequired);
 const nc3Matches=useMemo(()=>matchNC3(verified),[verified]);
 function applyNc3Suggestion(){setSerious(true);setNeedInv(true);setNeedRca(true)}
 const[showReject,setShowReject]=useState(false);const[rejectReason,setRejectReason]=useState("DUPLICATE");const[rejectNote,setRejectNote]=useState("");
 function reject(e:FormEvent){e.preventDefault();if(rejectReason==="OTHER"&&!rejectNote.trim())return setError("Lý do \"Khác\" cần ghi rõ nội dung.");command("REJECT",{reject_reason_code:rejectReason,comment:rejectNote})}
 async function command(action:string,payload:Record<string,unknown>={}){if(busy)return;setBusy(true);setError("");setNotice("");try{const r=await fetch(`/api/incidents/${recordId}/workflow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Không xử lý được sự cố.");setNotice(j.message);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Không xử lý được sự cố.")}finally{setBusy(false)}}
 function triage(e:FormEvent){e.preventDefault();command("TRIAGE",{verified_description:verified,harm_status:harm,serious_event_flag:serious,investigation_required:needInv,rca_required:needRca})}function complete(e:FormEvent){e.preventDefault();command("COMPLETE_INVESTIGATION",{verified_event_summary:eventSummary,harm_conclusion:harmConclusion,conclusion})}
 const p=status==="CLOSED"?6:status==="AWAITING_CLOSURE"?5:status==="ACTION_FOLLOW_UP"?4:status==="INVESTIGATING"||status==="INVESTIGATION_REQUIRED"?3:status==="TRIAGED"?2:1;
 const showFactors=["INVESTIGATION_REQUIRED","INVESTIGATING","ACTION_FOLLOW_UP","AWAITING_CLOSURE","CLOSED"].includes(status);
 const showRca=rcaRequired&&["INVESTIGATING","ACTION_FOLLOW_UP","AWAITING_CLOSURE","CLOSED"].includes(status);
 return <section className="panel incident-wf"><style>{`.incident-wf{overflow:hidden}.in-head{display:flex;justify-content:space-between;gap:12px;padding:18px;border-bottom:1px solid #e7eef0}.in-head h2{margin:0;font-size:18px}.in-head p{margin:5px 0 0;color:#64748b;font-size:12px}.in-status{padding:6px 10px;border-radius:999px;background:#fff3cd;color:#8a5a00;font-size:11px;font-weight:850;height:max-content}.in-steps{display:grid;grid-template-columns:repeat(6,1fr);gap:6px;padding:14px 18px;background:#fbfdff}.in-step{text-align:center;padding:9px 4px;border-radius:9px;background:#edf2f4;color:#718087;font-size:9px;font-weight:800}.in-step.on{background:#dbeafe;color:#1d4ed8}.in-body{display:grid;gap:12px;padding:0 18px 18px}.in-metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.in-metric{border:1px solid #dfe8ea;border-radius:11px;padding:10px}.in-metric strong{display:block;font-size:17px}.in-metric span{font-size:9px;color:#64748b}.in-box{border:1px solid #dfe8ea;border-radius:12px;padding:14px}.in-box h3{margin:0 0 5px;font-size:14px}.in-box p{margin:0 0 11px;color:#64748b;font-size:11px}.in-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.in-form .wide{grid-column:1/-1}.in-checks{display:flex;gap:14px;flex-wrap:wrap}.in-checks label{display:flex;align-items:center;gap:6px}.in-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:11px}.in-warn{padding:11px;border-radius:10px;background:#fff7e6;color:#92400e;border:1px solid #f5d38a;font-size:11px}@media(max-width:760px){.in-steps,.in-metrics,.in-form{grid-template-columns:1fr 1fr}.in-form .wide{grid-column:1/-1}.in-head{display:grid}}`}</style>
 <div className="in-head"><div><h2>Incident Workflow · An toàn người bệnh</h2><p>Giữ nguyên báo cáo ban đầu; QLCL xác minh, phân loại và quyết định mức điều tra/RCA.</p></div><span className="in-status">{LABEL[status]||status}</span></div><div className="in-steps">{["Báo cáo","Xác minh","Điều tra/RCA","Action/CAPA","Gate đóng","Đã đóng"].map((x,i)=><div className={`in-step ${p>=i+1?"on":""}`} key={x}>{i+1}. {x}</div>)}</div>
 <div className="in-body">{error?<div className="alert error">{error}</div>:null}{notice?<div className="alert success">{notice}</div>:null}<div className="in-metrics"><div className="in-metric"><strong>{initialSafetyRecorded?"Có":"Thiếu"}</strong><span>Xử trí tức thời</span></div><div className="in-metric"><strong>{investigationRequired?"Có":"Không"}</strong><span>Cần điều tra</span></div><div className="in-metric"><strong>{rcaRequired?"Có":"Không"}</strong><span>Cần RCA</span></div><div className="in-metric"><strong>{actionCount}/{incompleteActionCount}</strong><span>Action / chưa xong</span></div><div className="in-metric"><strong>{evidenceCount}</strong><span>Minh chứng</span></div></div>
 {!initialSafetyRecorded&&["REPORTED","RETURNED"].includes(status)?<div className="in-warn"><strong>Thiếu ghi nhận xử trí tức thời.</strong> Cần bổ sung thông tin bảo đảm an toàn trước khi hoàn tất xác minh.</div>:null}
 {["REPORTED","RETURNED"].includes(status)&&canTriage?<div className="in-box"><div className="in-actions" style={{justifyContent:"space-between"}}><h3 style={{margin:0}}>Trước khi xác minh sâu</h3>{!showReject?<button type="button" className="button tertiary small" onClick={()=>setShowReject(true)}>Không phải sự cố</button>:null}</div>{showReject?<form className="in-form" onSubmit={reject}><label>Lý do<select value={rejectReason} onChange={e=>setRejectReason(e.target.value)}><option value="DUPLICATE">Trùng lặp với báo cáo khác</option><option value="INSUFFICIENT_INFO">Không đủ thông tin để xác minh dù đã liên hệ</option><option value="NOT_A_MEDICAL_INCIDENT">Không phải sự cố y khoa (hiểu lầm/ngoài phạm vi)</option><option value="OTHER">Khác</option></select></label><label className="wide">Ghi chú {rejectReason==="OTHER"?"*":"(không bắt buộc)"}<textarea rows={2} value={rejectNote} onChange={e=>setRejectNote(e.target.value)}/></label><div className="wide in-actions"><button type="button" className="button secondary" onClick={()=>setShowReject(false)}>Huỷ, quay lại xác minh</button><button className="button primary" disabled={busy}>Xác nhận không phải sự cố, đóng hồ sơ</button></div></form>:null}</div>:null}
 {["REPORTED","RETURNED"].includes(status)&&canTriage?<form className="in-box" onSubmit={triage}><h3>Bước 2 · Xác minh và phân loại</h3><p>Không thay đổi lời báo cáo gốc. Nội dung dưới đây là kết quả xác minh riêng của QLCL.</p><div className="in-form"><label>Mức tổn hại<select value={harm} onChange={e=>setHarm(e.target.value)}><option value="NEAR_MISS">Near-miss</option><option value="NO_HARM">Không tổn hại</option><option value="MILD">Nhẹ</option><option value="MODERATE">Trung bình</option><option value="SEVERE">Nặng</option><option value="DEATH">Tử vong</option></select></label><label className="wide">Mô tả đã xác minh *<textarea rows={4} value={verified} onChange={e=>setVerified(e.target.value)}/></label>{nc3Matches.length?<div className="wide in-warn"><strong>Gợi ý: mô tả có từ khóa khớp với Danh mục sự cố nghiêm trọng (NC3, Thông tư 43/2018/TT-BYT):</strong><ul>{nc3Matches.map(m=><li key={m.rule.code}>Mục {m.rule.code} ({m.rule.group}) — {m.rule.label}. <em>Từ khóa khớp: {m.matchedKeywords.join(", ")}</em></li>)}</ul><p>Đây chỉ là gợi ý bằng đối chiếu từ khóa, không phải kết luận tự động — QLCL tự xác minh và quyết định cuối cùng.</p>{!serious?<button type="button" className="button secondary" onClick={applyNc3Suggestion}>Áp dụng gợi ý (tick Sự cố nghiêm trọng + Cần điều tra + Cần RCA)</button>:null}</div>:null}<div className="wide in-checks"><label><input type="checkbox" checked={serious} onChange={e=>{setSerious(e.target.checked);if(e.target.checked){setNeedInv(true);setNeedRca(true)}}}/> Sự cố nghiêm trọng</label><label><input type="checkbox" checked={needInv} onChange={e=>setNeedInv(e.target.checked)}/> Cần điều tra</label><label><input type="checkbox" checked={needRca} onChange={e=>setNeedRca(e.target.checked)}/> Cần RCA</label></div></div><div className="in-actions"><button className="button primary" disabled={busy||!initialSafetyRecorded}>Hoàn tất xác minh</button></div></form>:null}
 {status==="INVESTIGATION_REQUIRED"&&canInvestigate?<div className="in-box"><h3>Bước 3 · Mở điều tra</h3><p>Sự cố nghiêm trọng tự động bắt buộc điều tra và RCA.</p><div className="in-form"><label>Loại điều tra<select value={invType} onChange={e=>setInvType(e.target.value)}><option value="STANDARD">Điều tra chuẩn</option><option value="RCA">RCA</option><option value="SENTINEL_EVENT">Sự cố nghiêm trọng</option></select></label></div><div className="in-actions"><button className="button primary" disabled={busy} onClick={()=>command("START_INVESTIGATION",{investigation_type:invType})}>Bắt đầu điều tra</button></div></div>:null}
 {showFactors?<IncidentContributingFactorsClient recordId={recordId}/>:null}
 {showRca?<IncidentRcaWorkspaceClient recordId={recordId} onReadyChange={setRcaReady}/>:null}
 {status==="INVESTIGATING"&&canInvestigate?<form className="in-box" onSubmit={complete}><h3>Bước 3 · Kết luận điều tra</h3><p>{rcaRequired?"RCA cần xác định nguyên nhân ở cấp hệ thống trước khi chuyển sang Action/CAPA.":"Tổng hợp sự kiện, tổn hại và kết luận điều tra."}</p>{rcaRequired&&!rcaReady?<div className="in-warn"><strong>RCA chưa đủ gate.</strong> Cần tối thiểu 1 mốc Timeline, 3 cấp Five Why, 1 yếu tố Fishbone và 1 nguyên nhân gốc trước khi hoàn tất điều tra.</div>:null}<div className="in-form"><label className="wide">Sự kiện đã xác minh *<textarea rows={3} value={eventSummary} onChange={e=>setEventSummary(e.target.value)}/></label><label className="wide">Kết luận tổn hại *<textarea rows={3} value={harmConclusion} onChange={e=>setHarmConclusion(e.target.value)}/></label><label className="wide">Nguyên nhân/kết luận điều tra *<textarea rows={4} value={conclusion} onChange={e=>setConclusion(e.target.value)}/></label></div><div className="in-actions"><button className="button primary" disabled={busy||(rcaRequired&&!rcaReady)}>Hoàn tất điều tra</button></div></form>:null}
 {status==="TRIAGED"&&canTriage?<div className="in-box"><h3>Bước 4 · Theo dõi phòng ngừa</h3><p>Chuyển sang tạo và theo dõi Action/CAPA để phòng tái diễn.</p><button className="button primary" disabled={busy} onClick={()=>command("START_FOLLOW_UP")}>Chuyển theo dõi hành động</button></div>:null}
 {status==="ACTION_FOLLOW_UP"&&canInvestigate?<div className="in-box"><h3>Bước 4–5 · Gate trước khi đóng</h3><p>Bắt buộc có Action, hoàn thành các Action áp dụng và có minh chứng. Không dùng việc giảm số báo cáo sự cố làm tiêu chí hiệu quả.</p><button className="button primary" disabled={busy||actionCount<1||incompleteActionCount>0||evidenceCount<1} onClick={()=>command("READY_TO_CLOSE")}>Xác nhận đủ điều kiện đóng</button></div>:null}
 {status==="AWAITING_CLOSURE"&&canClose?<div className="in-box"><h3>Bước 5 · Xác nhận đóng</h3><p>Đóng hồ sơ nhưng giữ nguyên báo cáo, kết quả xác minh, điều tra, Action và audit trail.</p><button className="button primary" disabled={busy} onClick={()=>{const reason=window.prompt("Kết luận đóng sự cố:");if(reason?.trim())command("CLOSE",{comment:reason.trim()})}}>Đóng sự cố</button></div>:null}
 </div></section>
}
