"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const LABEL: Record<string,string> = { DRAFT:"Nháp", RETURNED:"Bị trả lại", SUBMITTED:"Chờ xác minh", VERIFIED:"Đã xác minh", LOCKED:"Đã khóa" };

export function IndicatorWorkflowClient({recordId,status,canEnter,canVerify,numerator,denominator,rawValue,calculatedValue,resultLevel,localTarget,unit,calculationType}:{recordId:string;status:string;canEnter:boolean;canVerify:boolean;numerator:number|null;denominator:number|null;rawValue:number|null;calculatedValue:number|null;resultLevel:string|null;localTarget:number|null;unit:string|null;calculationType:string|null}) {
  const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const [num,setNum]=useState(numerator==null?"":String(numerator)); const [den,setDen]=useState(denominator==null?"":String(denominator)); const [raw,setRaw]=useState(rawValue==null?"":String(rawValue));
  const editable=canEnter&&["DRAFT","RETURNED"].includes(status); const out=resultLevel==="OUT_OF_TARGET";
  async function command(action:string,payload:Record<string,unknown>={}){if(busy)return;setBusy(true);setError("");setNotice("");try{const res=await fetch(`/api/indicators/measurements/${recordId}/workflow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const json=await res.json().catch(()=>({}));if(!res.ok)throw new Error(json.error||"Không xử lý được kỳ đo.");setNotice(json.message||"Đã cập nhật.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Không xử lý được kỳ đo.");}finally{setBusy(false)}}
  const values=()=>({numerator_value:num===""?null:Number(num),denominator_value:den===""?null:Number(den),raw_value:raw===""?null:Number(raw)});
  function submit(e:FormEvent){e.preventDefault();command("SUBMIT",values())}
  return <section className="panel indicator-workflow"><style>{`.indicator-workflow{overflow:hidden}.iw-head{display:flex;justify-content:space-between;gap:14px;padding:18px;border-bottom:1px solid #e7eef0}.iw-head h2{margin:0;font-size:18px}.iw-head p{margin:5px 0 0;color:#64748b;font-size:12px}.iw-status{height:max-content;padding:6px 10px;border-radius:999px;background:#eff6ff;color:#1d4ed8;font-size:11px;font-weight:850}.iw-steps{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding:14px 18px;background:#fbfdff}.iw-step{padding:9px;border-radius:10px;text-align:center;background:#edf2f4;color:#728188;font-size:11px;font-weight:800}.iw-step.on{background:#dbeafe;color:#1d4ed8}.iw-body{display:grid;gap:12px;padding:0 18px 18px}.iw-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.iw-metric{border:1px solid #dfe8ea;border-radius:12px;padding:12px}.iw-metric strong{display:block;font-size:19px}.iw-metric span{font-size:10px;color:#64748b}.iw-form{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;border:1px solid #dfe8ea;border-radius:12px;padding:14px}.iw-actions{grid-column:1/-1;display:flex;gap:8px;flex-wrap:wrap}.iw-alert{padding:12px;border-radius:11px;font-size:12px}.iw-alert.warn{background:#fff7e6;color:#92400e;border:1px solid #f5d38a}.iw-alert.ok{background:#eaf7ef;color:#166534;border:1px solid #b9e2c7}@media(max-width:700px){.iw-steps,.iw-metrics,.iw-form{grid-template-columns:1fr}.iw-actions{grid-column:auto}.iw-actions .button{width:100%}.iw-head{display:grid}}`}</style>
    <div className="iw-head"><div><h2>Indicator Workflow · Kiểm soát kỳ đo</h2><p>Nhập dữ liệu → hệ thống tính → gửi xác minh → khóa số liệu. Dữ liệu đã khóa không sửa trực tiếp.</p></div><span className="iw-status">{LABEL[status]||status}</span></div>
    <div className="iw-steps">{["Nhập & tính","Gửi xác minh","Xác minh","Khóa dữ liệu"].map((x,i)=>{const p=status==="LOCKED"?4:status==="VERIFIED"?3:status==="SUBMITTED"?2:1;return <div className={`iw-step ${p>=i+1?"on":""}`} key={x}>{i+1}. {x}</div>})}</div>
    <div className="iw-body">{error?<div className="alert error">{error}</div>:null}{notice?<div className="alert success">{notice}</div>:null}
      <div className="iw-metrics"><div className="iw-metric"><strong>{calculatedValue??"—"} {unit||""}</strong><span>Kết quả hệ thống tính</span></div><div className="iw-metric"><strong>{localTarget??"—"}</strong><span>Mục tiêu kỳ đo</span></div><div className="iw-metric"><strong>{resultLevel==="MEETS_TARGET"?"Đạt":out?"Không đạt":"Chưa đánh giá"}</strong><span>{calculationType||"Công thức chỉ số"}</span></div></div>
      {out?<div className="iw-alert warn"><strong>Cảnh báo lệch mục tiêu.</strong> Cần phân tích nguyên nhân và tạo Action/CAPA ở khối bên dưới nếu đây là chênh lệch cần can thiệp.</div>:resultLevel==="MEETS_TARGET"?<div className="iw-alert ok">Kết quả đang đáp ứng mục tiêu đã giao.</div>:null}
      {editable?<form className="iw-form" onSubmit={submit}><label>Tử số<input type="number" min="0" step="any" value={num} onChange={e=>setNum(e.target.value)}/></label><label>Mẫu số<input type="number" min="0" step="any" value={den} onChange={e=>setDen(e.target.value)}/></label><label>Giá trị thô<input type="number" min="0" step="any" value={raw} onChange={e=>setRaw(e.target.value)}/></label><div className="iw-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>command("SAVE",values())}>Lưu nháp & tính lại</button><button className="button primary" disabled={busy}>{busy?"Đang xử lý...":"Gửi xác minh"}</button></div></form>:null}
      {status==="SUBMITTED"&&canVerify?<div className="iw-form"><div className="iw-actions"><button className="button primary" disabled={busy} onClick={()=>command("VERIFY")}>Xác minh dữ liệu</button><button className="button secondary" disabled={busy} onClick={()=>{const reason=window.prompt("Lý do trả lại người nhập:");if(reason?.trim())command("RETURN",{comment:reason.trim()})}}>Trả lại để sửa</button></div></div>:null}
      {status==="VERIFIED"&&canVerify?<div className="iw-form"><div className="iw-actions"><button className="button primary" disabled={busy} onClick={()=>command("LOCK")}>Khóa kỳ đo</button></div></div>:null}
      {status==="LOCKED"?<div className="iw-alert ok"><strong>Số liệu đã khóa.</strong> Mọi điều chỉnh phải thực hiện qua quy trình có giải trình và audit trail; không sửa trực tiếp.</div>:null}
    </div>
  </section>;
}
