"use client";
import { FormEvent,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { Icon } from "@/components/icon";

type Version={id:string;version_no:number;calculation_type:string|null;desired_direction:string|null;frequency:string|null;unit:string|null;multiplier:number|null;status:string;effective_from:string|null;effective_to:string|null;published_at:string|null};
type Row={id:string;code:string|null;name:string;purpose:string|null;quality_dimension:string|null;is_active:boolean;latest_version:Version|null;published_version:Version|null};
type Form={id:string;version_id:string;code:string;name:string;purpose:string;quality_dimension:string;calculation_type:string;desired_direction:string;frequency:string;unit:string;multiplier:string;effective_from:string};
const empty:Form={id:"",version_id:"",code:"",name:"",purpose:"",quality_dimension:"",calculation_type:"PERCENTAGE",desired_direction:"HIGHER_IS_BETTER",frequency:"MONTHLY",unit:"%",multiplier:"100",effective_from:""};

const freqLabel=(v?:string|null)=>({DAILY:"Hằng ngày",WEEKLY:"Hằng tuần",MONTHLY:"Hằng tháng",QUARTERLY:"Hằng quý",SEMIANNUAL:"6 tháng",ANNUAL:"Hằng năm"}[String(v||"")]||v||"—");
const directionLabel=(v?:string|null)=>({HIGHER_IS_BETTER:"Càng cao càng tốt",LOWER_IS_BETTER:"Càng thấp càng tốt",TARGET_RANGE:"Trong khoảng mục tiêu",NEUTRAL:"Theo dõi"}[String(v||"")]||v||"—");

export function IndicatorCatalogClient({rows,canManage}:{rows:Row[];canManage:boolean}){
 const router=useRouter();const [q,setQ]=useState("");const [showInactive,setShowInactive]=useState(false);const [form,setForm]=useState<Form>(empty);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<{tone:"success"|"error";text:string}|null>(null);
 const filtered=useMemo(()=>{const n=q.trim().toLowerCase();return rows.filter(r=>(showInactive||r.is_active)&&(!n||`${r.code||""} ${r.name} ${r.purpose||""} ${r.quality_dimension||""}`.toLowerCase().includes(n)))},[rows,q,showInactive]);
 function create(){setForm(empty);setMessage(null);setOpen(true)}
 function editMeta(row:Row){const v=row.latest_version;setForm({id:row.id,version_id:v?.status==="DRAFT"?v.id:"",code:row.code||"",name:row.name,purpose:row.purpose||"",quality_dimension:row.quality_dimension||"",calculation_type:v?.calculation_type||"PERCENTAGE",desired_direction:v?.desired_direction||"HIGHER_IS_BETTER",frequency:v?.frequency||"MONTHLY",unit:v?.unit||"",multiplier:v?.multiplier===null||v?.multiplier===undefined?"":String(v.multiplier),effective_from:v?.effective_from||""});setMessage(null);setOpen(true)}
 async function ensureDraft(row:Row){setBusy(true);try{const res=await fetch(`/api/indicator-definitions/${row.id}/versions`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Không tạo được bản cập nhật.");router.refresh();setTimeout(()=>{setForm({id:row.id,version_id:data.version_id,code:row.code||"",name:row.name,purpose:row.purpose||"",quality_dimension:row.quality_dimension||"",calculation_type:row.latest_version?.calculation_type||"PERCENTAGE",desired_direction:row.latest_version?.desired_direction||"HIGHER_IS_BETTER",frequency:row.latest_version?.frequency||"MONTHLY",unit:row.latest_version?.unit||"",multiplier:row.latest_version?.multiplier===null||row.latest_version?.multiplier===undefined?"":String(row.latest_version.multiplier),effective_from:""});setOpen(true)},300)}catch(e){alert(e instanceof Error?e.message:"Có lỗi xảy ra.")}finally{setBusy(false)}}
 async function submit(e:FormEvent){e.preventDefault();if(!form.name.trim())return setMessage({tone:"error",text:"Vui lòng nhập tên chỉ số."});setBusy(true);setMessage(null);try{
   if(!form.id){const res=await fetch("/api/indicator-definitions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await res.json();if(!res.ok)throw new Error(data.error||"Không tạo được chỉ số.");setMessage({tone:"success",text:`Đã tạo ${data.code} ở trạng thái Nháp.`});router.refresh();setForm({...form,id:data.id,version_id:data.version_id,code:data.code});return;}
   const meta=await fetch(`/api/indicator-definitions/${form.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:form.code,name:form.name,purpose:form.purpose,quality_dimension:form.quality_dimension})});const metaData=await meta.json();if(!meta.ok)throw new Error(metaData.error||"Không cập nhật được định nghĩa.");
   if(form.version_id){const ver=await fetch(`/api/indicator-versions/${form.version_id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({calculation_type:form.calculation_type,desired_direction:form.desired_direction,frequency:form.frequency,unit:form.unit,multiplier:form.multiplier,effective_from:form.effective_from})});const verData=await ver.json();if(!ver.ok)throw new Error(verData.error||"Không cập nhật được phiên bản.");}
   setMessage({tone:"success",text:"Đã cập nhật chỉ số."});router.refresh();
 }catch(e){setMessage({tone:"error",text:e instanceof Error?e.message:"Có lỗi xảy ra."})}finally{setBusy(false)}}
 async function toggle(row:Row){if(!window.confirm(row.is_active?"Ngưng áp dụng chỉ số này? Các kỳ đo cũ vẫn được giữ.":"Kích hoạt lại chỉ số này?"))return;setBusy(true);try{const res=await fetch(`/api/indicator-definitions/${row.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({is_active:!row.is_active})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Không cập nhật được trạng thái.");router.refresh()}catch(e){alert(e instanceof Error?e.message:"Có lỗi xảy ra.")}finally{setBusy(false)}}
 async function publish(row:Row){const v=row.latest_version;if(!v||v.status!=="DRAFT")return;if(!window.confirm(`Phát hành ${row.code||row.name} v${v.version_no}? Phiên bản cũ vẫn được giữ lịch sử.`))return;setBusy(true);try{const res=await fetch(`/api/indicator-definitions/${row.id}/publish`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({version_id:v.id})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Không phát hành được chỉ số.");router.refresh()}catch(e){alert(e instanceof Error?e.message:"Có lỗi xảy ra.")}finally{setBusy(false)}}
 return <>
  <section className="kpi-grid"><article className="kpi-card"><span>Tổng chỉ số</span><strong>{rows.length}</strong><small>{rows.filter(x=>x.is_active).length} đang áp dụng</small></article><article className="kpi-card success"><span>Đã phát hành</span><strong>{rows.filter(x=>x.published_version).length}</strong><small>Có phiên bản vận hành</small></article><article className="kpi-card warning"><span>Đang cập nhật</span><strong>{rows.filter(x=>x.latest_version?.status==="DRAFT").length}</strong><small>Có phiên bản nháp</small></article><article className="kpi-card"><span>Ngưng áp dụng</span><strong>{rows.filter(x=>!x.is_active).length}</strong><small>Vẫn giữ dữ liệu lịch sử</small></article></section>
  <section className="panel"><div className="toolbar"><div className="search-box"><Icon name="search" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm mã, tên, chiều chất lượng..."/></div><label className="inline-check"><input type="checkbox" checked={showInactive} onChange={e=>setShowInactive(e.target.checked)}/> Hiện đã ngưng</label>{canManage?<button className="button primary" onClick={create}><Icon name="plus" size={17}/> Thêm chỉ số</button>:null}</div>
   <div className="table-wrap"><table><thead><tr><th>Mã</th><th>Chỉ số</th><th>Cấu hình hiện tại</th><th>Phiên bản</th><th>Trạng thái</th><th></th></tr></thead><tbody>{filtered.map(row=>{const v=row.latest_version;return <tr key={row.id}><td><span className="record-code-pill">{row.code||"—"}</span></td><td><strong>{row.name}</strong><span className="subline">{row.quality_dimension||"Chưa phân loại"}{row.purpose?` · ${row.purpose}`:""}</span></td><td><strong>{freqLabel(v?.frequency)}</strong><span className="subline">{directionLabel(v?.desired_direction)} · {v?.calculation_type||"—"} · {v?.unit||"—"}</span></td><td><strong>{v?`v${v.version_no}`:"—"}</strong><span className="subline">{v?.status==="PUBLISHED"?"Đã phát hành":v?.status==="DRAFT"?"Nháp":v?.status||"—"}</span></td><td><span className={`status-badge ${row.is_active?"success":"muted"}`}>{row.is_active?"Đang áp dụng":"Đã ngưng"}</span></td><td><div style={{display:"flex",gap:5,justifyContent:"flex-end",flexWrap:"wrap"}}>{canManage?<>{v?.status==="DRAFT"?<><button className="button secondary small" onClick={()=>editMeta(row)}>Cập nhật</button><button className="button tertiary small" disabled={busy} onClick={()=>publish(row)}>Phát hành</button></>:<button className="button secondary small" disabled={busy||!row.is_active} onClick={()=>ensureDraft(row)}>Tạo bản cập nhật</button>}<button className="button secondary small" onClick={()=>toggle(row)}>{row.is_active?"Ngưng":"Kích hoạt"}</button></>:null}</div></td></tr>})}{!filtered.length?<tr><td colSpan={6}><div className="empty-state">Chưa có chỉ số phù hợp.</div></td></tr>:null}</tbody></table></div>
  </section>
  {open?<div className="modal-backdrop"><form className="modal-card" onSubmit={submit} style={{width:"min(900px,calc(100vw - 32px))"}}><div className="modal-head"><div><div className="eyebrow">DANH MỤC CHỈ SỐ</div><h2>{form.id?"Cập nhật chỉ số":"Thêm chỉ số"}</h2></div><button type="button" className="icon-button" onClick={()=>setOpen(false)}><Icon name="x"/></button></div><div className="modal-body">{message?<div className={`alert ${message.tone}`}>{message.text}</div>:null}<div className="form-grid two"><label>Mã chỉ số<input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="Để trống để QARICA tự sinh CS-YYYY-####"/></label><label>Chiều chất lượng<input value={form.quality_dimension} onChange={e=>setForm({...form,quality_dimension:e.target.value})} placeholder="An toàn / Hiệu quả / Người bệnh..."/></label><label className="span-2">Tên chỉ số *<textarea rows={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="span-2">Mục đích<textarea rows={2} value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/></label><label>Loại tính<select value={form.calculation_type} onChange={e=>setForm({...form,calculation_type:e.target.value})}><option value="PERCENTAGE">Tỷ lệ %</option><option value="RAW">Giá trị thô</option><option value="COUNT">Số lượng</option><option value="RATE">Tỷ suất</option><option value="RATIO">Tỷ số</option><option value="AVERAGE">Trung bình</option></select></label><label>Chiều mong muốn<select value={form.desired_direction} onChange={e=>setForm({...form,desired_direction:e.target.value})}><option value="HIGHER_IS_BETTER">Càng cao càng tốt</option><option value="LOWER_IS_BETTER">Càng thấp càng tốt</option><option value="TARGET_RANGE">Trong khoảng mục tiêu</option><option value="NEUTRAL">Theo dõi</option></select></label><label>Tần suất<select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="DAILY">Hằng ngày</option><option value="WEEKLY">Hằng tuần</option><option value="MONTHLY">Hằng tháng</option><option value="QUARTERLY">Hằng quý</option><option value="SEMIANNUAL">6 tháng</option><option value="ANNUAL">Hằng năm</option></select></label><label>Đơn vị đo<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} placeholder="% / ca / phút / ngày..."/></label><label>Hệ số nhân<input type="number" step="0.01" value={form.multiplier} onChange={e=>setForm({...form,multiplier:e.target.value})}/></label><label>Ngày hiệu lực<input type="date" value={form.effective_from} onChange={e=>setForm({...form,effective_from:e.target.value})}/></label></div></div><div className="modal-footer"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Đóng</button><button className="button primary" disabled={busy}>{busy?"Đang lưu...":"Lưu"}</button></div></form></div>:null}
 </>;
}
