"use client";
import {useState} from "react";import {useRouter} from "next/navigation";
type Option={id:string;name?:string;short_name?:string;full_name?:string;email?:string;department_id?:string;primary_department_id?:string};
export function InspectionWorkflowClient({recordId,status,visitDate,canManage,departments,profiles,milestones,evidenceCount,incompleteCount}:{recordId:string;status:string;visitDate:string;canManage:boolean;departments:Option[];profiles:Option[];milestones:{offset:number;status:string;dueDate:string}[];evidenceCount:number;incompleteCount:number}){
 const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[department,setDepartment]=useState(departments[0]?.id||"");const available=profiles.filter(p=>!department||(p.primary_department_id||p.department_id)===department);const[owner,setOwner]=useState(available[0]?.id||"");
 async function command(action:string,payload:Record<string,unknown>={}){if(busy)return;setBusy(true);setError("");setNotice("");try{const r=await fetch(`/api/inspections/${recordId}/workflow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Không xử lý được đợt tiếp đoàn.");setNotice(j.message);router.refresh()}catch(e){setError(e instanceof Error?e.message:"Không xử lý được đợt tiếp đoàn.")}finally{setBusy(false)}}
 const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh"}).format(new Date());const days=Math.ceil((new Date(`${visitDate}T00:00:00Z`).getTime()-new Date(`${today}T00:00:00Z`).getTime())/86400000);const step=status==="CLOSED"?4:status==="FOLLOW_UP"?3:status==="ON_SITE"?2:1;
 return <section className="panel inspection-wf"><style>{`.inspection-wf{overflow:hidden}.ix-head{display:flex;justify-content:space-between;gap:12px;padding:18px;border-bottom:1px solid #e7eef0}.ix-head h2{margin:0;font-size:18px}.ix-head p{margin:5px 0 0;color:#64748b;font-size:12px}.ix-count{padding:8px 12px;border-radius:12px;background:#1d3f73;color:#fff;font-weight:900;height:max-content}.ix-steps{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;padding:14px 18px;background:#fbfdff}.ix-step{text-align:center;padding:9px;border-radius:9px;background:#edf2f4;color:#718087;font-size:10px;font-weight:800}.ix-step.on{background:#dbeafe;color:#1d4ed8}.ix-body{display:grid;gap:12px;padding:0 18px 18px}.ix-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.ix-card{border:1px solid #dfe8ea;border-radius:11px;padding:10px}.ix-card strong{display:block;font-size:13px}.ix-card span{font-size:9px;color:#64748b}.ix-card.done{background:#eaf7ef}.ix-box{border:1px solid #dfe8ea;border-radius:12px;padding:14px}.ix-box h3{margin:0 0 5px;font-size:14px}.ix-box p{margin:0 0 11px;font-size:11px;color:#64748b}.ix-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ix-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:11px}@media(max-width:760px){.ix-grid,.ix-steps,.ix-form{grid-template-columns:1fr 1fr}.ix-head{display:grid}}`}</style>
 <div className="ix-head"><div><h2>Inspection Mode · Tiếp đoàn</h2><p>Countdown được tính từ ngày đoàn đến; mỗi mốc là Action thật có owner, deadline, sản phẩm và minh chứng.</p></div><div className="ix-count">{days>0?`D-${days}`:days===0?"D-Day":`D+${Math.abs(days)}`}</div></div><div className="ix-steps">{["Chuẩn bị","Tiếp đoàn","Sau đoàn","Đóng"].map((x,i)=><div className={`ix-step ${step>=i+1?"on":""}`} key={x}>{i+1}. {x}</div>)}</div>
 <div className="ix-body">{error?<div className="alert error">{error}</div>:null}{notice?<div className="alert success">{notice}</div>:null}<div className="ix-grid">{[-30,-14,-7,-3,-1,0,1,7].map(o=>{const m=milestones.find(x=>x.offset===o);return <div className={`ix-card ${m?"done":""}`} key={o}><strong>{o<0?`D${o}`:o===0?"D-Day":`D+${o}`}</strong><span>{m?`${m.dueDate} · ${m.status}`:"Chưa tạo Action"}</span></div>})}</div>
 {["PLANNING","PREPARATION"].includes(status)&&canManage?<div className="ix-box"><h3>Tạo/hoàn thiện bộ Action countdown</h3><p>Hệ thống chỉ tạo các mốc còn thiếu, không tạo trùng khi bấm lại.</p><div className="ix-form"><label>Khoa/phòng phụ trách<select value={department} onChange={e=>{setDepartment(e.target.value);setOwner("")}}><option value="">Chọn đơn vị</option>{departments.map(d=><option key={d.id} value={d.id}>{d.short_name||d.name}</option>)}</select></label><label>Người phụ trách<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Chọn người phụ trách</option>{available.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email}</option>)}</select></label></div><div className="ix-actions"><button className="button primary" disabled={busy||!department||!owner} onClick={()=>command("GENERATE_COUNTDOWN",{lead_department_id:department,assignee_user_id:owner})}>Tạo các mốc còn thiếu</button>{status==="PREPARATION"?<button className="button secondary" disabled={busy||today<visitDate} onClick={()=>command("START_VISIT")}>Bắt đầu ngày tiếp đoàn</button>:null}</div></div>:null}
 {status==="ON_SITE"&&canManage?<div className="ix-box"><h3>Đoàn đang làm việc</h3><p>Ghi nhận tóm tắt ban đầu; tồn tại chính thức phải chuyển thành Finding, không tạo module tồn tại riêng.</p><button className="button primary" disabled={busy} onClick={()=>{const s=window.prompt("Tóm tắt kết quả/kiến nghị ban đầu:");if(s?.trim())command("COMPLETE_VISIT",{comment:s.trim()})}}>Kết thúc ngày tiếp đoàn</button></div>:null}
 {status==="FOLLOW_UP"&&canManage?<div className="ix-box"><h3>Theo dõi sau đoàn</h3><p>Còn {incompleteCount} Action chưa hoàn thành · {evidenceCount} minh chứng. Tồn tại đi theo Finding → Action → Evidence → Recheck.</p><button className="button primary" disabled={busy||incompleteCount>0||evidenceCount<1} onClick={()=>{const s=window.prompt("Kết luận đóng đợt tiếp đoàn:");if(s?.trim())command("CLOSE",{comment:s.trim()})}}>Đóng đợt tiếp đoàn</button></div>:null}
 </div></section>
}
