import { TQM_CHART_CSS, TqmDonut, TqmHorizontalBars, TqmTrend } from "@/components/tqm-charts";
import { createClient } from "@/lib/supabase/server";

type Row={id:string;record_code:string;title:string;lifecycle_status:string;department_name:string;created_at:string;updated_at:string};
type Tone="brand"|"blue"|"amber"|"red"|"green"|"slate";
const CSS=`${TQM_CHART_CSS}.ops-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.ops-kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:15px 16px}.ops-kpi span{display:block;font-size:10px;color:#728188;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.ops-kpi strong{display:block;font-size:29px;line-height:1;margin-top:8px}.ops-kpi small{display:block;font-size:10px;color:#7d8c92;margin-top:6px}.ops-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.ops-head{padding:16px 18px 4px}.ops-head h2{margin:0;font-size:15px}.ops-head p{margin:4px 0 0;color:#74838a;font-size:11px}@media(max-width:900px){.ops-grid{grid-template-columns:1fr}}@media(max-width:700px){.ops-kpis{grid-template-columns:1fr 1fr}}`;
function Kpis({items}:{items:{label:string;value:string|number;note:string}[]}){return <section className="ops-kpis">{items.map(x=><article className="ops-kpi" key={x.label}><span>{x.label}</span><strong>{x.value}</strong><small>{x.note}</small></article>)}</section>}
function statusBars(values:string[]){const m=new Map<string,number>();values.forEach(v=>m.set(v||"UNKNOWN",(m.get(v||"UNKNOWN")||0)+1));return Array.from(m.entries()).sort((a,b)=>b[1]-a[1]).map(([label,value],i)=>({label:label.replaceAll("_"," "),value,tone:(i===0?"brand":i===1?"blue":i===2?"amber":"slate") as Tone}))}
function monthPoints(values:(string|null|undefined)[]){const p=Array.from({length:12},(_,i)=>({label:`T${i+1}`,value:0}));values.forEach(value=>{if(!value)return;const d=new Date(value);if(!Number.isNaN(d.getTime()))p[d.getMonth()].value++});return p}
function depBars(rows:Row[]){const m=new Map<string,number>();rows.forEach(r=>m.set(r.department_name,(m.get(r.department_name)||0)+1));return Array.from(m.entries()).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value],i)=>({label,value,tone:(i<3?"brand":"blue") as Tone}))}
function hcmToday(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh"}).format(new Date())}

export async function OperationsObligationsOverview({rows,recordType}:{rows:Row[];recordType:string}){
 const supabase=await createClient();const ids=rows.map(r=>r.id);if(!ids.length)return null;const today=hcmToday();
 if(recordType==="DIRECTIVE"){
  const {data}=await supabase.from("external_directives").select("id,record_id,workflow_status,received_date,implementation_due_date,report_due_date").in("record_id",ids);const items=(data??[]) as any[];const completed=items.filter(x=>String(x.workflow_status)==="COMPLETED").length;const overdue=items.filter(x=>x.implementation_due_date&&x.implementation_due_date<today&&String(x.workflow_status)!=="COMPLETED").length;const evidenceSubmitted=items.filter(x=>String(x.workflow_status)==="EVIDENCE_SUBMITTED").length;const completion=items.length?Math.round(completed/items.length*100):0;
  return <><style>{CSS}</style><Kpis items={[{label:"Chỉ đạo / yêu cầu",value:items.length,note:"Trong năm đang chọn"},{label:"Đã hoàn tất",value:`${completion}%`,note:`${completed}/${items.length||0} yêu cầu`},{label:"Quá hạn",value:overdue,note:"Theo hạn thực hiện nghiệp vụ"},{label:"Chờ xác nhận",value:evidenceSubmitted,note:"Đã nộp kết quả/minh chứng"}]} /><section className="ops-grid"><article className="panel"><div className="ops-head"><h2>Khép vòng chỉ đạo</h2><p>Nhận yêu cầu → phân công → Action → minh chứng → xác nhận kết quả.</p></div><TqmDonut value={completion} label="Hoàn tất" segments={[{label:"Hoàn tất",value:completed,tone:"green"},{label:"Còn mở",value:Math.max(0,items.length-completed),tone:overdue?"red":"amber"}]}/></article><article className="panel"><div className="ops-head"><h2>Yêu cầu theo bước workflow</h2><p>Ưu tiên hồ sơ đang quá hạn hoặc đã nộp minh chứng nhưng chưa xác nhận.</p></div><TqmHorizontalBars rows={statusBars(items.map(x=>String(x.workflow_status||"OPEN")))}/></article></section><section className="ops-grid"><article className="panel"><div className="ops-head"><h2>Khối lượng theo khoa/phòng</h2><p>Cho biết đơn vị đang chịu nhiều chỉ đạo/yêu cầu nhất.</p></div><TqmHorizontalBars rows={depBars(rows)}/></article><article className="panel"><div className="ops-head"><h2>Yêu cầu tiếp nhận theo tháng</h2><p>Dùng <strong>received_date</strong>, không dùng ngày chỉnh sửa hồ sơ.</p></div><TqmTrend points={monthPoints(items.map(x=>x.received_date))} unit=""/></article></section></>;
 }
 if(recordType==="REPORT"){
  const {data}=await supabase.from("reporting_obligations").select("id,record_id,workflow_status,due_date,reporting_period_end,recipient_name").in("record_id",ids);const items=(data??[]) as any[];
  const reportIds=items.map(x=>x.id);const {data:subs}=reportIds.length?await supabase.from("report_submissions").select("reporting_obligation_id,submission_version,submitted_at").in("reporting_obligation_id",reportIds):{data:[] as any[]};const submissionRows=(subs??[]) as any[];
  const firstSubmission=new Map<string,string>();for(const s of submissionRows){if(!s.submitted_at)continue;const current=firstSubmission.get(s.reporting_obligation_id);if(!current||String(s.submitted_at)<current)firstSubmission.set(s.reporting_obligation_id,String(s.submitted_at));}
  const submitted=items.filter(x=>firstSubmission.has(x.id)).length;const timedSubmitted=items.filter(x=>x.due_date&&firstSubmission.has(x.id));const onTimeSubmitted=timedSubmitted.filter(x=>String(firstSubmission.get(x.id)).slice(0,10)<=String(x.due_date)).length;const lateSubmitted=Math.max(0,timedSubmitted.length-onTimeSubmitted);const onTimePct=timedSubmitted.length?Math.round(onTimeSubmitted/timedSubmitted.length*100):0;const overdueUnsubmitted=items.filter(x=>x.due_date&&x.due_date<today&&!firstSubmission.has(x.id)).length;const resubmissions=submissionRows.filter(x=>Number(x.submission_version)>1).length;
  return <><style>{CSS}</style><Kpis items={[{label:"Nghĩa vụ báo cáo",value:items.length,note:"Trong năm đang chọn"},{label:"Đã gửi đúng hạn",value:`${onTimePct}%`,note:`${onTimeSubmitted}/${timedSubmitted.length||0} nghĩa vụ đã gửi có hạn`},{label:"Quá hạn chưa gửi",value:overdueUnsubmitted,note:"Cần xử lý ngay"},{label:"Gửi lại",value:resubmissions,note:`${submitted} nghĩa vụ đã có submission`}]} /><section className="ops-grid"><article className="panel"><div className="ops-head"><h2>Tuân thủ thời hạn trên báo cáo đã gửi</h2><p>Mẫu số chỉ gồm nghĩa vụ đã có submission và có due_date; không coi hồ sơ chưa đến hạn là “đúng hạn”.</p></div><TqmDonut value={onTimePct} label="Gửi đúng hạn" segments={[{label:"Đúng hạn",value:onTimeSubmitted,tone:"green"},{label:"Gửi trễ",value:lateSubmitted,tone:"red"}]}/></article><article className="panel"><div className="ops-head"><h2>Báo cáo theo bước workflow</h2><p>Not due/Due → Preparing → Reviewing → Submitted → Completed.</p></div><TqmHorizontalBars rows={statusBars(items.map(x=>String(x.workflow_status||"NOT_DUE")))}/></article></section><section className="ops-grid"><article className="panel"><div className="ops-head"><h2>Nghĩa vụ theo khoa/phòng</h2><p>Nhận diện đơn vị có tải báo cáo cao.</p></div><TqmHorizontalBars rows={depBars(rows)}/></article><article className="panel"><div className="ops-head"><h2>Kỳ báo cáo kết thúc theo tháng</h2><p>Dùng <strong>reporting_period_end</strong> để phản ánh kỳ nghiệp vụ; thời điểm gửi thực tế được giữ riêng ở submission.</p></div><TqmTrend points={monthPoints(items.map(x=>x.reporting_period_end))} unit=""/></article></section></>;
 }
 return null;
}
