"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Reminder={id:string;title:string;note:string|null;due_at:string|null;priority:string;status:string};

export function PersonalReminders({initialRows,organizationId,userId}:{initialRows:Reminder[];organizationId:string;userId:string}){
 const supabase=createClient(); const [rows,setRows]=useState(initialRows); const [title,setTitle]=useState(""); const [due,setDue]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function add(){const clean=title.trim();if(!clean)return;setBusy(true);setError("");const {data,error}=await supabase.from("personal_reminders").insert({organization_id:organizationId,owner_user_id:userId,title:clean,due_at:due?new Date(due).toISOString():null}).select("id,title,note,due_at,priority,status").single();setBusy(false);if(error){setError(error.message);return}setRows(v=>[...v,data as Reminder].sort((a,b)=>(a.due_at||"9999").localeCompare(b.due_at||"9999")));setTitle("");setDue("")}
 async function complete(row:Reminder){const next=row.status==="COMPLETED"?"OPEN":"COMPLETED";const {error}=await supabase.from("personal_reminders").update({status:next,completed_at:next==="COMPLETED"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",row.id);if(error){setError(error.message);return}setRows(v=>v.map(x=>x.id===row.id?{...x,status:next}:x))}
 async function remove(id:string){const {error}=await supabase.from("personal_reminders").delete().eq("id",id);if(error){setError(error.message);return}setRows(v=>v.filter(x=>x.id!==id))}
 return <section className="work-section"><div className="section-head"><div><h2>Nhắc việc cá nhân</h2><p>Riêng tư, chỉ anh/chị nhìn thấy. Có hạn sẽ tự xuất hiện trên Lịch QLCL.</p></div></div><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 190px auto",gap:8,padding:12}}><input className="input" placeholder="Thêm việc cần nhớ…" value={title} maxLength={300} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void add()}}/><input className="input" type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/><button className="button primary small" disabled={busy||!title.trim()} onClick={()=>void add()}>Thêm</button></div>{error?<div className="alert error" style={{margin:"0 12px 12px"}}>{error}</div>:null}<div className="work-list">{rows.map(r=><div className="work-row" key={r.id}><div className="work-main"><strong style={{textDecoration:r.status==="COMPLETED"?"line-through":"none"}}>{r.title}</strong><small>{r.due_at?new Intl.DateTimeFormat("vi-VN",{timeZone:"Asia/Ho_Chi_Minh",dateStyle:"short",timeStyle:"short"}).format(new Date(r.due_at)):"Không đặt hạn"} · {r.priority}</small></div><div><span className="status-badge info">{r.status==="COMPLETED"?"Đã xong":"Cá nhân"}</span></div><button className="button secondary small" onClick={()=>void complete(r)}>{r.status==="COMPLETED"?"Mở lại":"Hoàn tất"}</button><button className="button tertiary small" onClick={()=>void remove(r.id)}>Xóa</button></div>)}{!rows.length?<div className="empty-state compact">Chưa có nhắc việc cá nhân.</div>:null}</div></section>
}
