import { TQM_CHART_CSS, TqmDonut, TqmHorizontalBars, TqmTrend } from "@/components/tqm-charts";
import { createClient } from "@/lib/supabase/server";

type Row={id:string;lifecycle_status:string;department_name:string;created_at:string;updated_at:string};
type Tone="brand"|"blue"|"amber"|"red"|"green"|"slate";
const CSS=`${TQM_CHART_CSS}.rp-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.rp-kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:15px 16px}.rp-kpi span{display:block;font-size:10px;color:#728188;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.rp-kpi strong{display:block;font-size:29px;line-height:1;margin-top:8px}.rp-kpi small{display:block;font-size:10px;color:#7d8c92;margin-top:6px}.rp-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.rp-head{padding:16px 18px 4px}.rp-head h2{margin:0;font-size:15px}.rp-head p{margin:4px 0 0;color:#74838a;font-size:11px}@media(max-width:900px){.rp-grid{grid-template-columns:1fr}}@media(max-width:700px){.rp-kpis{grid-template-columns:1fr 1fr}}`;
function Kpis({items}:{items:{label:string;value:string|number;note:string}[]}){return <section className="rp-kpis">{items.map(x=><article className="rp-kpi" key={x.label}><span>{x.label}</span><strong>{x.value}</strong><small>{x.note}</small></article>)}</section>}
function statusBars(values:string[]){const m=new Map<string,number>();values.forEach(v=>m.set(v||"UNKNOWN",(m.get(v||"UNKNOWN")||0)+1));return Array.from(m.entries()).sort((a,b)=>b[1]-a[1]).map(([label,value],i)=>({label:label.replaceAll("_"," "),value,tone:(i===0?"brand":i===1?"blue":i===2?"amber":"slate") as Tone}))}
function months(rows:Row[]){const p=Array.from({length:12},(_,i)=>({label:`T${i+1}`,value:0}));rows.forEach(r=>{const d=new Date(r.created_at);if(!Number.isNaN(d.getTime()))p[d.getMonth()].value++});return p}

export async function RiskProactiveOverview({rows,recordType}:{rows:Row[];recordType:string}){
 if(recordType!=="FMEA")return null;const supabase=await createClient();const ids=rows.map(r=>r.id);if(!ids.length)return null;
 const {data:studiesData}=await supabase.from("fmea_studies").select("id,record_id,method,workflow_status,scoring_model_version_id").in("record_id",ids);const studies=(studiesData??[]) as any[];const studyIds=studies.map(x=>x.id);
 const {data:stepsData}=studyIds.length?await supabase.from("fmea_process_steps").select("id,fmea_study_id").in("fmea_study_id",studyIds):{data:[] as any[]};const steps=(stepsData??[]) as any[];const stepIds=steps.map(x=>x.id);
 const {data:modesData}=stepIds.length?await supabase.from("fmea_failure_modes").select("id,process_step_id,is_high_priority").in("process_step_id",stepIds):{data:[] as any[]};const modes=(modesData??[]) as any[];const high=modes.filter(x=>x.is_high_priority).length;
 const {data:linksData}=await supabase.from("record_links").select("source_record_id,target_record_id").in("source_record_id",ids).eq("relation_type","HAS_ACTION");const links=(linksData??[]) as any[];const actionRecordIds=links.map(x=>x.target_record_id).filter(Boolean);const {data:actionsData}=actionRecordIds.length?await supabase.from("actions").select("record_id,workflow_status").in("record_id",actionRecordIds):{data:[] as any[]};const actions=(actionsData??[]) as any[];const actionDone=actions.filter(x=>["COMPLETED","CANCELLED","NOT_APPLICABLE"].includes(String(x.workflow_status))).length;
 const closed=studies.filter(x=>String(x.workflow_status)==="CLOSED").length;const residual=studies.filter(x=>String(x.workflow_status)==="RESIDUAL_REVIEW").length;const completion=studies.length?Math.round(closed/studies.length*100):0;const actionProgress=actions.length?Math.round(actionDone/actions.length*100):0;
 return <><style>{CSS}</style><Kpis items={[{label:"Nghiên cứu FMEA/HFMEA",value:studies.length,note:"Trong năm đang chọn"},{label:"Process step",value:steps.length,note:"Bước quy trình đã phân tích"},{label:"Failure mode ưu tiên cao",value:high,note:`${modes.length} failure mode tổng cộng`},{label:"Action can thiệp",value:actions.length,note:`${actionProgress}% đã hoàn tất`}]} /><section className="rp-grid"><article className="panel"><div className="rp-head"><h2>Khép vòng FMEA → can thiệp → re-score</h2><p>FMEA chỉ đóng sau khi Action hoàn tất, có minh chứng và residual risk được xem xét/chấp nhận.</p></div><TqmDonut value={completion} label="FMEA đã đóng" segments={[{label:"Đã đóng",value:closed,tone:"green"},{label:"Residual review",value:residual,tone:"amber"},{label:"Đang phân tích/triển khai",value:Math.max(0,studies.length-closed-residual),tone:"blue"}]}/></article><article className="panel"><div className="rp-head"><h2>FMEA theo bước workflow</h2><p>Draft → Pending approval → In progress → Residual review → Closed.</p></div><TqmHorizontalBars rows={statusBars(studies.map(x=>String(x.workflow_status||"DRAFT")))}/></article></section><section className="panel"><div className="rp-head"><h2>FMEA/HFMEA được khởi tạo theo tháng</h2><p>Dùng ngày tạo hồ sơ Registry để quan sát nhịp khởi tạo nghiên cứu; không diễn giải đây là xu hướng mức rủi ro.</p></div><TqmTrend points={months(rows)} unit=""/></section></>;
}
