import Link from "next/link";
import { MyWorkSyncClient } from "@/components/my-work-sync-client";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { TQM_CHART_CSS, TqmDonut, TqmHorizontalBars } from "@/components/tqm-charts";
import { requirePermission, requireUserContext } from "@/lib/auth";
import { formatDate } from "@/lib/format";
import { isOperationallyHiddenStatus } from "@/lib/operational-record";
import { createClient } from "@/lib/supabase/server";
import { getWorkYear } from "@/lib/work-year";

function priorityLabel(value?:string|null){if(value==="CRITICAL")return"Rất khẩn";if(value==="URGENT")return"Khẩn";if(value==="HIGH")return"Cao";if(value==="LOW")return"Thấp";return"Bình thường"}
function priorityTone(value?:string|null){if(["CRITICAL","URGENT"].includes(String(value)))return"danger";if(value==="HIGH")return"warning";if(value==="LOW")return"muted";return"info"}
function workCue(row:any){const days=Number(row.days_to_due||0);if(row.is_overdue){const late=Math.abs(days);if(late>=7)return`Đôn đốc ngay · quá hạn ${late} ngày`;return`Xử lý ngay · quá hạn ${late} ngày`}if(["EVIDENCE_SUBMITTED","VERIFYING"].includes(String(row.workflow_status)))return"Cần kiểm tra / xác minh";if(row.workflow_status==="RETURNED")return"Cần bổ sung sau khi bị trả lại";if(days===0)return"Hoàn tất trong hôm nay";if(days>0&&days<=3)return`Chuẩn bị xử lý · còn ${days} ngày`;if(["CRITICAL","URGENT"].includes(String(row.priority)))return"Ưu tiên xử lý sớm";return days>0?`Theo dõi · còn ${days} ngày`:"Cần kiểm tra tiến độ"}
function workScore(row:any){const days=Number(row.days_to_due||0);let score=0;if(row.is_overdue)score+=200+Math.abs(days)*5;if(row.workflow_status==="RETURNED")score+=150;if(["EVIDENCE_SUBMITTED","VERIFYING"].includes(String(row.workflow_status)))score+=135;if(days===0)score+=160;if(days>0&&days<=3)score+=100;if(row.priority==="CRITICAL")score+=90;else if(row.priority==="URGENT")score+=70;else if(row.priority==="HIGH")score+=40;return score}
const ACTION_SELECT="action_id,record_id,record_code,title,work_year,workflow_status,priority,due_date,is_overdue,days_to_due,lead_department_id,assignee_user_id,assignment_target_type,assignee_group_id";

export default async function TasksPage(){
 const {user}=await requireUserContext();requirePermission(user,"tasks.view");const year=await getWorkYear();const supabase=await createClient();
 const isQlcl=user.roleCodes.includes("QLCL_MANAGER")||user.roleCodes.includes("HOI_DONG_QLCL");const isDepartmentHead=user.roleCodes.includes("DEPARTMENT_HEAD");const isBoard=user.roleCodes.includes("BAN_GIAM_DOC");
 const groupAssignmentRes=await supabase
  .from("work_group_assignment_snapshots")
  .select("target_record_id,group_id,member_snapshot")
  .eq("assignment_role","ACTION_ASSIGNEE_GROUP");
 const myGroupActionRecordIds=Array.from(new Set((groupAssignmentRes.data??[]).filter((row:any)=>Array.isArray(row.member_snapshot)&&row.member_snapshot.some((member:any)=>member?.user_id===user.id)).map((row:any)=>row.target_record_id).filter(Boolean))) as string[];
 const [directActionsRes,groupActionsRes,attentionRes]=await Promise.all([
  supabase.from("vw_actions_dashboard").select(ACTION_SELECT).eq("work_year",year).eq("assignee_user_id",user.id).order("due_date",{ascending:true,nullsFirst:false}),
  myGroupActionRecordIds.length
   ? supabase.from("vw_actions_dashboard").select(ACTION_SELECT).eq("work_year",year).in("record_id",myGroupActionRecordIds).order("due_date",{ascending:true,nullsFirst:false})
   : Promise.resolve({data:[] as any[],error:null}),
  supabase.from("notifications").select("id,title,message,priority,target_route,target_record_id,created_at,is_read").eq("recipient_user_id",user.id).eq("is_read",false).order("created_at",{ascending:false}).limit(20),
 ]);
 const actionRowsById=new Map<string,any>();
 for(const row of [...(directActionsRes.data??[]),...(groupActionsRes.data??[])])actionRowsById.set((row as any).action_id,row);
 const actionsRes={data:Array.from(actionRowsById.values()),error:directActionsRes.error||groupActionsRes.error||groupAssignmentRes.error};
 let scopeActionsRes:any={data:[] as any[],error:null};
 if(isQlcl){scopeActionsRes=await supabase.from("vw_actions_dashboard").select(ACTION_SELECT).eq("work_year",year).order("due_date",{ascending:true,nullsFirst:false});}
 else if(isDepartmentHead&&user.primaryDepartmentId){scopeActionsRes=await supabase.from("vw_actions_dashboard").select(ACTION_SELECT).eq("work_year",year).eq("lead_department_id",user.primaryDepartmentId).order("due_date",{ascending:true,nullsFirst:false});}
 const sourceRows=(actionsRes.data??[]) as any[];const scopeSourceRows=(scopeActionsRes.data??[]) as any[];const recordIds=Array.from(new Set([...sourceRows,...scopeSourceRows].map(r=>r.record_id).filter(Boolean)));const recordRes=recordIds.length?await supabase.from("records").select("id,lifecycle_status").in("id",recordIds):{data:[],error:null};const hidden=new Set((recordRes.data??[]).filter((r:any)=>isOperationallyHiddenStatus(r.lifecycle_status)).map((r:any)=>r.id));
 const roleDepartmentIds=Array.from(new Set(scopeSourceRows.map(r=>r.lead_department_id).filter(Boolean)));const roleDepartmentsRes=roleDepartmentIds.length?await supabase.from("departments").select("id,name,short_name").in("id",roleDepartmentIds):{data:[],error:null};const roleDepartmentMap=new Map((roleDepartmentsRes.data??[]).map((d:any)=>[d.id,d.short_name||d.name]));
 const assignedGroupIds=Array.from(new Set([...sourceRows,...scopeSourceRows].map((r:any)=>r.assignee_group_id).filter(Boolean))) as string[];const assignedGroupsRes=assignedGroupIds.length?await supabase.from("work_groups").select("id,name,code").in("id",assignedGroupIds):{data:[],error:null};const assignedGroupMap=new Map((assignedGroupsRes.data??[]).map((g:any)=>[g.id,[g.code,g.name].filter(Boolean).join(" · ")]));
 const rows=sourceRows.filter(r=>r.workflow_status!=="CANCELLED"&&!hidden.has(r.record_id));const attention=(attentionRes.data??[]) as any[];const scopedRows=scopeSourceRows.filter(r=>!["COMPLETED","CANCELLED","CLOSED","NOT_APPLICABLE"].includes(String(r.workflow_status))&&!hidden.has(r.record_id));const firstError=actionsRes.error||attentionRes.error||scopeActionsRes.error||recordRes.error||roleDepartmentsRes.error||assignedGroupsRes.error;
 const overdue=rows.filter(r=>r.is_overdue).length,dueToday=rows.filter(r=>!r.is_overdue&&Number(r.days_to_due)===0).length,dueSoon=rows.filter(r=>!r.is_overdue&&Number(r.days_to_due)>0&&Number(r.days_to_due)<=7).length,open=rows.filter(r=>!["COMPLETED","CANCELLED","CLOSED"].includes(r.workflow_status)).length,completed=rows.filter(r=>r.workflow_status==="COMPLETED").length;
 const overdue7=rows.filter(r=>r.is_overdue&&Math.abs(Number(r.days_to_due||0))>=7).length,overdue3to6=rows.filter(r=>r.is_overdue&&Math.abs(Number(r.days_to_due||0))>=3&&Math.abs(Number(r.days_to_due||0))<7).length;
 const deadlineSegments=[{label:"Quá hạn",value:overdue,tone:"red" as const},{label:"Hôm nay",value:dueToday,tone:"amber" as const},{label:"7 ngày tới",value:dueSoon,tone:"blue" as const},{label:"Còn lại",value:Math.max(0,open-overdue-dueToday-dueSoon),tone:"slate" as const}];
 const priorityMap=new Map<string,number>();rows.filter(r=>!["COMPLETED","CLOSED"].includes(r.workflow_status)).forEach(r=>{const k=priorityLabel(r.priority);priorityMap.set(k,(priorityMap.get(k)||0)+1)});const priorityRows=["Rất khẩn","Khẩn","Cao","Bình thường","Thấp"].map((label,i)=>({label,value:priorityMap.get(label)||0,tone:(i<2?"red":i===2?"amber":i===3?"brand":"slate") as any}));
 const secretaryQueue=[...rows].filter(r=>!["COMPLETED","CLOSED"].includes(r.workflow_status)).sort((a,b)=>workScore(b)-workScore(a)).slice(0,6);
 const roleQueue=[...scopedRows].filter(r=>r.is_overdue||Number(r.days_to_due)===0||(Number(r.days_to_due)>0&&Number(r.days_to_due)<=3)||["RETURNED","EVIDENCE_SUBMITTED","VERIFYING"].includes(String(r.workflow_status))||["CRITICAL","URGENT"].includes(String(r.priority))).sort((a,b)=>workScore(b)-workScore(a)).slice(0,8);
 const roleQueueTitle=isQlcl?"Hàng đợi điều phối QLCL":isDepartmentHead?"Hàng đợi của khoa/phòng":"";const roleQueueDescription=isQlcl?"Chỉ hiển thị Action toàn viện cần can thiệp: quá hạn, sát hạn, bị trả lại, chờ xác minh hoặc mức khẩn.":"Action của khoa/phòng cần Trưởng đơn vị theo dõi hoặc can thiệp; không thay thế danh sách việc cá nhân.";
 const attentionTitle=isBoard?"Cần theo dõi / quyết định":isQlcl?"Hồ sơ cần QLCL xử lý / xác minh":isDepartmentHead?"Hồ sơ khoa/phòng cần xử lý":"Cần tôi xử lý / xác minh";
 const roleViewLabel=isBoard?"BAN GIÁM ĐỐC":isQlcl?"QLCL":isDepartmentHead?"TRƯỞNG KHOA/PHÒNG":"CÁ NHÂN";
 const secretaryHeadline=overdue7>0?`${overdue7} việc đã quá hạn từ 7 ngày trở lên cần đôn đốc ngay.`:overdue>0?`${overdue} việc đang quá hạn; ưu tiên xử lý trước các công việc mới.`:dueToday>0?`${dueToday} việc đến hạn hôm nay cần hoàn tất trước cuối ngày.`:attention.length>0?`${attention.length} hồ sơ/thông báo đang chờ bạn xử lý.`:"Không có việc cá nhân quá hạn. Tiếp tục theo dõi hàng đợi nghiệp vụ theo vai trò.";
 return <div className="page-stack my-work-page tqm-my-work">
  <MyWorkSyncClient/>
  <style>{`.tqm-my-work{max-width:1180px;margin:0 auto}.tqm-my-work .work-summary{display:flex;gap:8px;flex-wrap:wrap}.tqm-my-work .summary-chip{border:1px solid #d7e1e5;border-radius:999px;padding:7px 10px;background:#fff;font-size:11px;font-weight:800}.tqm-my-work .summary-chip.danger{border-color:#efc6c6;background:#fff5f5;color:#a83b3b}.tqm-my-work .summary-chip.warning{border-color:#f2d59a;background:#fff9eb;color:#8a5b0a}.tqm-my-work .work-section{background:#fff;border:1px solid #d3dee3;border-radius:16px;overflow:hidden}.tqm-my-work .work-section.primary{border:2px solid #9fb8c5}.tqm-my-work .section-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;padding:15px 17px;border-bottom:1px solid #e2e9ec;background:#f8fbfc}.tqm-my-work .section-head h2{margin:0;font-size:16px}.tqm-my-work .section-head p{margin:4px 0 0;color:#687a80;font-size:11px}.tqm-my-work .work-list{display:grid}.tqm-my-work .work-row{display:grid;grid-template-columns:minmax(0,1fr) 115px 110px auto;gap:12px;align-items:center;padding:13px 16px;border-bottom:1px solid #e7edef}.tqm-my-work .work-row:last-child{border-bottom:0}.tqm-my-work .work-row.danger{background:#fffafa}.tqm-my-work .work-main strong{font-size:12px}.tqm-my-work .work-main small{display:block;margin-top:4px;color:#718187;font-size:10px}.tqm-my-work .role-badge{display:inline-flex;border-radius:999px;background:#eaf2fb;color:#1d4f7a;padding:5px 8px;font-size:9px;font-weight:900}.tqm-my-work details{border-top:1px solid #dbe5e9}.tqm-my-work summary{cursor:pointer;padding:13px 16px;font-weight:800;font-size:12px;background:#fafcfd}.tqm-my-work .all-table{padding:0}.tqm-my-work .attention-list{display:grid;gap:8px;padding:12px 16px 16px}.tqm-my-work .attention-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;border:1px solid #e4eaec;border-radius:12px;padding:11px}.tqm-my-work .attention-item strong{font-size:11px}.tqm-my-work .attention-item small{display:block;margin-top:3px;color:#7b898f}.tqm-my-work .mobile-only{display:none}@media(max-width:760px){.tqm-my-work .work-row{grid-template-columns:1fr auto}.tqm-my-work .work-row>div:nth-child(2),.tqm-my-work .work-row>div:nth-child(3){display:none}.tqm-my-work .desktop-only{display:none}.tqm-my-work .mobile-only{display:block}}`}</style>
  <PageHeader eyebrow={`CÔNG VIỆC HÔM NAY · ${roleViewLabel} · ${year}`} title="Việc của tôi" description="Chỉ tập trung vào việc cần làm. Việc khẩn và đến hạn được đưa lên trước; các danh sách quản lý mở khi cần."/>
  <div className="work-summary">
    <span className={`summary-chip ${overdue?"danger":""}`}>Quá hạn: {overdue}</span>
    <span className={`summary-chip ${dueToday?"warning":""}`}>Hôm nay: {dueToday}</span>
    <span className="summary-chip">7 ngày tới: {dueSoon}</span>
    <span className="summary-chip">Đang mở: {open}</span>
  </div>
  <section className="work-section primary">
    <div className="section-head"><div><h2>Việc cần làm trước</h2><p>{secretaryHeadline} Hệ thống đã xếp theo hạn, trạng thái chờ xử lý và mức ưu tiên.</p></div></div>
    <div className="work-list">{secretaryQueue.map(r=><div className={`work-row ${r.is_overdue||r.workflow_status==="RETURNED"?"danger":""}`} key={r.action_id}><div className="work-main"><strong>{r.title}</strong><small>{r.record_code} · {workCue(r)}{r.assignment_target_type==="GROUP"?` · ${assignedGroupMap.get(r.assignee_group_id)||"Nhóm phân công"}`:""}</small></div><div><span className={`status-badge ${priorityTone(r.priority)}`}>{priorityLabel(r.priority)}</span></div><div><StatusBadge status={r.is_overdue?"OVERDUE":r.workflow_status}/></div><Link className="button primary small" href={`/tasks/${r.record_id}`}>Làm ngay</Link></div>)}{!secretaryQueue.length?<div className="empty-state">Không có việc khẩn hoặc sát hạn cần xử lý.</div>:null}</div>
  </section>
  {(isQlcl||isDepartmentHead)&&roleQueue.length?<section className="work-section"><div className="section-head"><div><div style={{display:"flex",gap:8,alignItems:"center"}}><h2>{roleQueueTitle}</h2><span className="role-badge">{isQlcl?"TOÀN VIỆN":user.primaryDepartmentName||"KHOA/PHÒNG"}</span></div><p>Chỉ các việc cần anh/chị can thiệp theo vai trò quản lý; không trộn với việc cá nhân.</p></div></div><div className="work-list">{roleQueue.map(r=><div className={`work-row ${r.is_overdue||r.workflow_status==="RETURNED"?"danger":""}`} key={`role-${r.action_id}`}><div className="work-main"><strong>{r.title}</strong><small>{roleDepartmentMap.get(r.lead_department_id)||"Chưa gán khoa/phòng"} · {workCue(r)}</small></div><div><span className={`status-badge ${priorityTone(r.priority)}`}>{priorityLabel(r.priority)}</span></div><div><StatusBadge status={r.is_overdue?"OVERDUE":r.workflow_status}/></div><Link className="button secondary small" href={`/tasks/${r.record_id}`}>Mở</Link></div>)}</div></section>:null}
  {attention.length?<section className="work-section"><details><summary>{attentionTitle} · {attention.length} thông báo chưa đọc</summary><div className="attention-list">{attention.slice(0,8).map(n=><div className="attention-item" key={n.id}><div><strong>{n.title}</strong><small>{n.message||"Có hồ sơ cần xử lý."}</small></div>{n.target_route?<Link className="button secondary small" href={n.target_route}>Mở hồ sơ</Link>:null}</div>)}</div></details></section>:null}
  <section id="all-work" className="work-section desktop-only"><details><summary>Toàn bộ việc đang giao cho tôi · {open}</summary><div className="table-wrap all-table"><table><thead><tr><th>Nội dung</th><th>Ưu tiên</th><th>Hạn</th><th>Trạng thái</th></tr></thead><tbody>{rows.filter(r=>!["COMPLETED","CANCELLED","CLOSED"].includes(r.workflow_status)).map(r=><tr key={r.action_id}><td><Link className="table-link" href={`/tasks/${r.record_id}`}>{r.title}</Link><span className="subline">{r.record_code}{r.assignment_target_type==="GROUP"?` · Nhóm: ${assignedGroupMap.get(r.assignee_group_id)||"Nhóm phân công"}`:""}</span></td><td><span className={`status-badge ${priorityTone(r.priority)}`}>{priorityLabel(r.priority)}</span></td><td className={r.is_overdue?"text-danger":""}>{formatDate(r.due_date)}</td><td><StatusBadge status={r.is_overdue?"OVERDUE":r.workflow_status}/></td></tr>)}</tbody></table></div></details></section>
  <section className="mobile-only">{rows.filter(r=>!["COMPLETED","CANCELLED","CLOSED"].includes(r.workflow_status)).map(r=><article className={`my-work-card ${r.is_overdue?"overdue":""}`} key={r.action_id}><strong>{r.title}</strong><small>{workCue(r)}</small><Link className="button primary small" href={`/tasks/${r.record_id}`}>Mở công việc</Link></article>)}</section>
  {firstError?<div className="alert error">Một phần dữ liệu tác nghiệp chưa tải được: {firstError.message}</div>:null}
 </div>
}