import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { TQM_CHART_CSS, TqmDonut, TqmHorizontalBars } from "@/components/tqm-charts";
import { requirePermission, requireUserContext } from "@/lib/auth";
import { formatDate } from "@/lib/format";
import { isOperationallyHiddenStatus } from "@/lib/operational-record";
import { createClient } from "@/lib/supabase/server";
import { getWorkYear } from "@/lib/work-year";

function priorityLabel(value?:string|null){if(value==="CRITICAL")return"Rất khẩn";if(value==="URGENT")return"Khẩn";if(value==="HIGH")return"Cao";if(value==="LOW")return"Thấp";return"Bình thường"}
function priorityTone(value?:string|null){if(["CRITICAL","URGENT"].includes(String(value)))return"danger";if(value==="HIGH")return"warning";if(value==="LOW")return"muted";return"info"}

export default async function TasksPage(){
 const {user}=await requireUserContext();requirePermission(user,"tasks.view");const year=await getWorkYear();const supabase=await createClient();
 const [actionsRes,attentionRes]=await Promise.all([
  supabase.from("vw_actions_dashboard").select("action_id,record_id,record_code,title,work_year,workflow_status,priority,due_date,is_overdue,days_to_due,lead_department_id,assignee_user_id").eq("work_year",year).eq("assignee_user_id",user.id).order("due_date",{ascending:true,nullsFirst:false}),
  supabase.from("notifications").select("id,title,message,priority,target_route,target_record_id,created_at,is_read").eq("recipient_user_id",user.id).eq("is_read",false).order("created_at",{ascending:false}).limit(12),
 ]);
 const sourceRows=(actionsRes.data??[]) as any[];const recordIds=Array.from(new Set(sourceRows.map(r=>r.record_id).filter(Boolean)));const recordRes=recordIds.length?await supabase.from("records").select("id,lifecycle_status").in("id",recordIds):{data:[],error:null};const hidden=new Set((recordRes.data??[]).filter((r:any)=>isOperationallyHiddenStatus(r.lifecycle_status)).map((r:any)=>r.id));
 const rows=sourceRows.filter(r=>r.workflow_status!=="CANCELLED"&&!hidden.has(r.record_id));const firstError=actionsRes.error||attentionRes.error||recordRes.error;const attention=(attentionRes.data??[]) as any[];
 const overdue=rows.filter(r=>r.is_overdue).length,dueToday=rows.filter(r=>!r.is_overdue&&Number(r.days_to_due)===0).length,dueSoon=rows.filter(r=>!r.is_overdue&&Number(r.days_to_due)>0&&Number(r.days_to_due)<=7).length,open=rows.filter(r=>!["COMPLETED","CANCELLED","CLOSED"].includes(r.workflow_status)).length,completed=rows.filter(r=>r.workflow_status==="COMPLETED").length;
 const deadlineSegments=[{label:"Quá hạn",value:overdue,tone:"red" as const},{label:"Hôm nay",value:dueToday,tone:"amber" as const},{label:"7 ngày tới",value:dueSoon,tone:"blue" as const},{label:"Còn lại",value:Math.max(0,open-overdue-dueToday-dueSoon),tone:"slate" as const}];
 const priorityMap=new Map<string,number>();rows.filter(r=>!["COMPLETED","CLOSED"].includes(r.workflow_status)).forEach(r=>{const k=priorityLabel(r.priority);priorityMap.set(k,(priorityMap.get(k)||0)+1)});const priorityRows=["Rất khẩn","Khẩn","Cao","Bình thường","Thấp"].map((label,i)=>({label,value:priorityMap.get(label)||0,tone:(i<2?"red":i===2?"amber":i===3?"brand":"slate") as any}));
 const urgent=rows.filter(r=>r.is_overdue||Number(r.days_to_due)===0||["CRITICAL","URGENT"].includes(String(r.priority))).slice(0,5);
 return <div className="page-stack my-work-page tqm-my-work">
  <style>{TQM_CHART_CSS+`.tqm-my-work{max-width:1280px;margin:0 auto}.tqm-my-work .kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.tqm-my-work .kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:15px 16px}.tqm-my-work .kpi span{font-size:10px;color:#718187;font-weight:800;text-transform:uppercase}.tqm-my-work .kpi strong{display:block;font-size:30px;margin-top:8px}.tqm-my-work .kpi small{font-size:10px;color:#7e8d92}.tqm-my-work .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.tqm-my-work .head{padding:16px 18px 4px}.tqm-my-work .head h2{margin:0;font-size:15px}.tqm-my-work .head p{margin:4px 0 0;color:#74838a;font-size:11px}.tqm-my-work .focus-list,.tqm-my-work .attention-list{display:grid;gap:8px;padding:8px 16px 16px}.tqm-my-work .focus-item,.tqm-my-work .attention-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;border:1px solid #e4eaec;border-radius:13px;padding:12px}.tqm-my-work .focus-item.danger,.tqm-my-work .attention-item.danger{border-color:#efc6c6;background:#fffafa}.tqm-my-work .focus-item strong,.tqm-my-work .attention-item strong{font-size:12px}.tqm-my-work .focus-item small,.tqm-my-work .attention-item small{display:block;margin-top:3px;color:#7b898f;line-height:1.4}.tqm-my-work .my-work-mobile{display:none}@media(max-width:1080px){.tqm-my-work .kpis{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.tqm-my-work .grid{grid-template-columns:1fr}.tqm-my-work .kpis{grid-template-columns:1fr 1fr}}@media(max-width:760px){.tqm-my-work .my-work-desktop{display:none}.tqm-my-work .my-work-mobile{display:grid;gap:9px}.tqm-my-work .my-work-card{display:grid;gap:10px;border:1px solid #dce6e7;border-radius:15px;background:#fff;padding:13px}.tqm-my-work .my-work-card.overdue{border-color:#efc5c5;background:#fffafa}.tqm-my-work .my-work-card-head{display:flex;justify-content:space-between;gap:10px}.tqm-my-work .my-work-code{font-size:11px;font-weight:800;color:#1d3f73}.tqm-my-work .my-work-card h3{font-size:15px;margin:3px 0}.tqm-my-work .my-work-card-meta{display:grid;grid-template-columns:1fr 1fr;gap:7px}.tqm-my-work .my-work-card-meta>div{background:#f7f9fa;border-radius:10px;padding:8px}.tqm-my-work .my-work-card-meta span{display:block;font-size:9px;color:#7b898e;font-weight:800}.tqm-my-work .my-work-card-actions .button{width:100%;justify-content:center}}`}</style>
  <PageHeader eyebrow={`CÔNG VIỆC CÁ NHÂN · ${year}`} title="Việc của tôi" description="Dashboard tác nghiệp cá nhân: Action được giao, việc quá hạn/sắp hạn và các hồ sơ đang chờ chính bạn xác minh, duyệt hoặc xử lý."/>
  <section className="kpis"><article className="kpi"><span>Quá hạn</span><strong>{overdue}</strong><small>Cần xử lý ngay</small></article><article className="kpi"><span>Đến hạn hôm nay</span><strong>{dueToday}</strong><small>Hoàn tất trong ngày</small></article><article className="kpi"><span>7 ngày tới</span><strong>{dueSoon}</strong><small>Chủ động sắp xếp</small></article><article className="kpi"><span>Chờ tôi xử lý</span><strong>{attention.length}</strong><small>Thông báo attention chưa đọc</small></article><article className="kpi"><span>Đã hoàn thành</span><strong>{completed}</strong><small>{rows.length} Action trong danh sách</small></article></section>
  {firstError?<div className="alert error">Một phần dữ liệu tác nghiệp chưa tải được: {firstError.message}</div>:null}
  <section className="grid"><article className="panel"><div className="head"><h2>Áp lực thời hạn</h2><p>Phân bố các Action đang mở theo mốc thời gian cần xử lý.</p></div><TqmDonut value={open?Math.round(overdue/open*100):0} label="Tỷ lệ quá hạn" segments={deadlineSegments}/></article><article className="panel"><div className="head"><h2>Cơ cấu ưu tiên</h2><p>Giúp sắp thứ tự xử lý Action theo mức độ quan trọng.</p></div><TqmHorizontalBars rows={priorityRows}/></article></section>
  <section className="grid"><article className="panel"><div className="head"><h2>5 Action cần tập trung trước</h2><p>Ưu tiên quá hạn, đến hạn hôm nay hoặc mức khẩn/rất khẩn.</p></div><div className="focus-list">{urgent.map(r=><div className={`focus-item ${r.is_overdue?"danger":""}`} key={r.action_id}><div><strong>{r.record_code} · {r.title}</strong><small>{r.is_overdue?`Quá hạn ${Math.abs(Number(r.days_to_due||0))} ngày`:Number(r.days_to_due)===0?"Đến hạn hôm nay":`Còn ${r.days_to_due} ngày`} · {priorityLabel(r.priority)}</small></div><Link className="button primary small" href={`/tasks/${r.record_id}`}>Xử lý</Link></div>)}{!urgent.length?<div className="empty-state">Không có Action khẩn hoặc sát hạn.</div>:null}</div></article><article className="panel"><div className="head"><h2>Cần tôi xử lý / xác minh</h2><p>Tín hiệu attention cá nhân từ các workflow; không trộn vào Dashboard điều hành toàn viện.</p></div><div className="attention-list">{attention.slice(0,6).map(n=><div className={`attention-item ${["CRITICAL","URGENT","HIGH"].includes(String(n.priority))?"danger":""}`} key={n.id}><div><strong>{n.title}</strong><small>{n.message||"Có hồ sơ cần bạn xử lý."}</small></div>{n.target_route?<Link className="button secondary small" href={n.target_route}>Mở</Link>:null}</div>)}{!attention.length?<div className="empty-state">Không có attention chưa đọc đang chờ bạn.</div>:null}</div></article></section>
  <section className="panel my-work-desktop"><div className="table-wrap"><table><thead><tr><th>Mã</th><th>Nội dung</th><th>Ưu tiên</th><th>Hạn</th><th>Trạng thái</th></tr></thead><tbody>{rows.map(r=><tr key={r.action_id}><td><Link className="table-link" href={`/tasks/${r.record_id}`}>{r.record_code}</Link></td><td><strong>{r.title}</strong></td><td><span className={`status-badge ${priorityTone(r.priority)}`}>{priorityLabel(r.priority)}</span></td><td className={r.is_overdue?"text-danger":""}>{formatDate(r.due_date)}</td><td><StatusBadge status={r.is_overdue?"OVERDUE":r.workflow_status}/></td></tr>)}{!rows.length?<tr><td colSpan={5}><div className="empty-state">Chưa có Action đang hoạt động.</div></td></tr>:null}</tbody></table></div></section>
  <section className="my-work-mobile">{rows.map(r=><article className={`my-work-card ${r.is_overdue?"overdue":""}`} key={r.action_id}><div className="my-work-card-head"><div><div className="my-work-code">{r.record_code}</div><h3>{r.title}</h3></div><StatusBadge status={r.is_overdue?"OVERDUE":r.workflow_status}/></div><div className="my-work-card-meta"><div><span>Hạn</span><strong>{formatDate(r.due_date)}</strong></div><div><span>Ưu tiên</span><strong>{priorityLabel(r.priority)}</strong></div></div><div className="my-work-card-actions"><Link className="button primary" href={`/tasks/${r.record_id}`}>Mở công việc</Link></div></article>)}</section>
 </div>
}
