import Link from "next/link";
import { redirect } from "next/navigation";
import { DomainCreateClient } from "@/components/domain-create-client";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { TQM_CHART_CSS, TqmDonut, TqmHorizontalBars, TqmTrend } from "@/components/tqm-charts";
import { hasAnyPermission, requireUserContext } from "@/lib/auth";
import { hcmMonthNumber, incidentAttentionRank } from "@/lib/incident-dashboard";
import { isOperationallyHiddenStatus } from "@/lib/operational-record";
import { routeForRecord } from "@/lib/record-route";
import { createClient } from "@/lib/supabase/server";
import { getWorkYear } from "@/lib/work-year";

const HARM_LABEL:Record<string,string>={NO_HARM:"Không tổn hại",NEAR_MISS:"Suýt xảy ra",MILD:"Nhẹ",MODERATE:"Trung bình",SEVERE:"Nặng",DEATH:"Tử vong"};
function harmTone(v:string){if(["DEATH","SEVERE"].includes(v))return"red" as const;if(v==="MODERATE")return"amber" as const;if(["MILD","NO_HARM"].includes(v))return"blue" as const;return"slate" as const}

export default async function IncidentsPage(){
 const {user}=await requireUserContext();if(!hasAnyPermission(user,["incident.report","incident.view_summary","incident.view_case","incident.triage"]))redirect("/dashboard?forbidden=1");const year=await getWorkYear();const supabase=await createClient();
 const [recordsRes,incidentsRes,depsRes]=await Promise.all([
  supabase.from("records").select("id,record_code,title,lifecycle_status,owner_department_id").eq("record_type","INCIDENT").eq("work_year",year).order("created_at",{ascending:false}),
  supabase.from("incidents").select("id,record_id,workflow_status,harm_status,serious_event_flag,reported_at,incident_location_text,lead_department_id"),
  supabase.from("departments").select("id,name,short_name").eq("is_active",true)
 ]);
 const records=((recordsRes.data??[]) as any[]).filter(r=>!isOperationallyHiddenStatus(r.lifecycle_status));const recordMap=new Map(records.map(r=>[r.id,r]));const depMap=new Map((depsRes.data??[]).map((d:any)=>[d.id,d.short_name||d.name]));
 const rows=((incidentsRes.data??[]) as any[]).filter(x=>recordMap.has(x.record_id)).map(x=>{const r:any=recordMap.get(x.record_id);return{...x,...r,department:String(depMap.get(x.lead_department_id||r.owner_department_id)||"Chưa xác định"),route:routeForRecord("INCIDENT",x.record_id)}});
 const isOpen=(x:any)=>!["CLOSED","CANCELLED"].includes(String(x.workflow_status));const openRows=rows.filter(isOpen);const seriousOpen=openRows.filter(x=>x.serious_event_flag).length;const investigating=openRows.filter(x=>["INVESTIGATION_REQUIRED","INVESTIGATING","ACTION_FOLLOW_UP"].includes(x.workflow_status)).length;const unclassified=openRows.filter(x=>!x.harm_status||String(x.harm_status)==="UNCLASSIFIED").length;const closed=rows.filter(x=>x.workflow_status==="CLOSED").length;
 const harmMap=new Map<string,number>();rows.forEach(x=>{const k=String(x.harm_status||"UNCLASSIFIED");harmMap.set(k,(harmMap.get(k)||0)+1)});const harmSegments=Array.from(harmMap.entries()).map(([k,value])=>({label:HARM_LABEL[k]||"Chưa phân loại",value,tone:harmTone(k)}));
 const locMap=new Map<string,number>();rows.forEach(x=>{const k=String(x.incident_location_text||x.department||"Chưa xác định").trim()||"Chưa xác định";locMap.set(k,(locMap.get(k)||0)+1)});const locationBars=Array.from(locMap.entries()).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([label,value],i)=>({label,value,tone:(i<3?"red":i<6?"amber":"blue") as any}));
 const depAgg=new Map<string,number>();rows.forEach(x=>depAgg.set(x.department,(depAgg.get(x.department)||0)+1));const depBars=Array.from(depAgg.entries()).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([label,value],i)=>({label,value,tone:(i<3?"brand":"blue") as any}));
 const months=Array.from({length:12},(_,i)=>({label:`T${i+1}`,value:0}));let missingReportedAt=0;rows.forEach(x=>{const month=hcmMonthNumber(x.reported_at);if(month===null){missingReportedAt++;return}months[month-1].value++});
 const attentionRows=[...openRows].sort((a,b)=>incidentAttentionRank(b)-incidentAttentionRank(a)||String(b.reported_at||"").localeCompare(String(a.reported_at||"")));
 const firstError=[recordsRes,incidentsRes,depsRes].find((x:any)=>x.error)?.error;const canReport=user.permissions.includes("incident.report")||user.permissions.includes("incident.triage");
 return <div className="page-stack incident-tqm">
  <style>{TQM_CHART_CSS+`.incident-tqm .kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.incident-tqm .kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:16px}.incident-tqm .kpi.alert{border-color:#efc6c6;background:#fffafa}.incident-tqm .kpi.warn{border-color:#f2d4a7;background:#fffcf5}.incident-tqm .kpi span{font-size:10px;color:#718187;font-weight:800;text-transform:uppercase}.incident-tqm .kpi strong{display:block;font-size:30px;margin-top:8px}.incident-tqm .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.incident-tqm .head{padding:16px 18px 4px}.incident-tqm .head h2{margin:0;font-size:15px}.incident-tqm .head p{margin:4px 0 0;color:#74838a;font-size:11px}.incident-tqm .hot-list{display:grid;gap:8px;padding:8px 16px 16px}.incident-tqm .hot-row{display:grid;grid-template-columns:minmax(0,1.5fr) 120px 110px auto;gap:10px;align-items:center;border:1px solid #e4eaec;border-radius:13px;padding:12px}.incident-tqm .hot-row.serious{border-color:#efc6c6;background:#fffafa}.incident-tqm .empty-work{padding:22px 18px;color:#65758a}.incident-tqm .analytics>summary{cursor:pointer;font-weight:800;padding:16px 18px;background:#fff;border:1px solid #e1e9ec;border-radius:15px}.incident-tqm .analytics[open]>summary{border-radius:15px 15px 0 0}.incident-tqm .analytics-body{display:grid;gap:14px;padding-top:14px}@media(max-width:900px){.incident-tqm .grid{grid-template-columns:1fr}.incident-tqm .kpis{grid-template-columns:1fr 1fr}.incident-tqm .hot-row{grid-template-columns:1fr 1fr}.incident-tqm .hot-row>div:first-child{grid-column:1/-1}}`}</style>
  <PageHeader eyebrow={`AN TOÀN & RỦI RO · ${year}`} title="Sự cố y khoa" description="Màn hình xử lý sự cố hằng ngày: ưu tiên hồ sơ nghiêm trọng, chưa phân loại và đang cần điều tra; phân tích xu hướng được đặt riêng phía dưới." actions={canReport?<DomainCreateClient recordType="INCIDENT" workYear={year}/>:null}/>
  {firstError?<div className="alert error">Một phần dữ liệu chưa tải được: {firstError.message}</div>:null}
  <section className="kpis"><article className={`kpi ${seriousOpen?"alert":""}`}><span>Nghiêm trọng đang mở</span><strong>{seriousOpen}</strong><small>Cần ưu tiên rà soát</small></article><article className={`kpi ${unclassified?"warn":""}`}><span>Chưa phân loại</span><strong>{unclassified}</strong><small>Trong các hồ sơ đang mở</small></article><article className={`kpi ${investigating?"warn":""}`}><span>Cần / đang điều tra</span><strong>{investigating}</strong><small>RCA và theo dõi hành động</small></article><article className="kpi"><span>Đang mở</span><strong>{openRows.length}</strong><small>{closed} hồ sơ đã đóng</small></article></section>
  <section className="panel"><div className="head"><h2>Hồ sơ cần xử lý</h2><p>Chỉ hiển thị hồ sơ chưa đóng. Sự cố nghiêm trọng và hồ sơ cần điều tra được đưa lên trước để tránh chìm trong danh sách lịch sử.</p></div>{attentionRows.length?<div className="hot-list">{attentionRows.slice(0,20).map(x=><div className={`hot-row ${x.serious_event_flag?"serious":""}`} key={x.id}><div><strong>{x.record_code} · {x.title}</strong><small className="subline">{x.incident_location_text||x.department}</small></div><div>{HARM_LABEL[x.harm_status]||x.harm_status||"Chưa phân loại"}</div><div><StatusBadge status={x.workflow_status}/></div><Link className="button tertiary small" href={x.route}>Xử lý hồ sơ</Link></div>)}</div>:<div className="empty-work">Không có sự cố đang mở cần xử lý.</div>}</section>
  <details className="analytics"><summary>Phân tích an toàn người bệnh</summary><div className="analytics-body">
   <section className="grid"><article className="panel"><div className="head"><h2>Xu hướng báo cáo sự cố 12 tháng</h2><p>Dùng reported_at theo múi giờ Việt Nam. {missingReportedAt?`${missingReportedAt} hồ sơ thiếu/không hợp lệ ngày báo cáo không được đưa vào xu hướng.`:"Tất cả hồ sơ có ngày báo cáo hợp lệ."}</p></div><TqmTrend points={months} unit=""/></article><article className="panel"><div className="head"><h2>Cơ cấu mức tổn hại</h2><p>Phân bố theo mức tổn hại đã ghi nhận.</p></div><TqmDonut value={rows.length?Math.round(rows.filter(x=>x.serious_event_flag).length/rows.length*100):0} label="Nghiêm trọng" segments={harmSegments.length?harmSegments:[{label:"Chưa có dữ liệu",value:1,tone:"slate"}]}/></article></section>
   <section className="grid"><article className="panel"><div className="head"><h2>Điểm nóng nơi xảy ra</h2><p>Xếp giảm dần theo số sự cố ghi nhận; không diễn giải như tỷ lệ rủi ro khi chưa có mẫu số hoạt động.</p></div><TqmHorizontalBars rows={locationBars}/></article><article className="panel"><div className="head"><h2>Sự cố theo khoa/phòng phụ trách</h2><p>Khối lượng hồ sơ theo đơn vị đầu mối xử lý; không dùng để xếp hạng chất lượng khoa khi chưa hiệu chỉnh theo quy mô.</p></div><TqmHorizontalBars rows={depBars}/></article></section>
  </div></details>
 </div>
}