import Link from "next/link";
import { redirect } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { TQM_CHART_CSS, TqmDonut, TqmHorizontalBars, TqmTrend } from "@/components/tqm-charts";
import { requireUserContext } from "@/lib/auth";
import { isOperationallyHiddenStatus } from "@/lib/operational-record";
import { filterRegistryAnalyticsRows, registryMonthlyCounts } from "@/lib/registry-analytics";
import { createClient } from "@/lib/supabase/server";
import { getWorkYear } from "@/lib/work-year";

const TYPE_LABELS:Record<string,string>={ACTION:"Action",PROGRAM:"Kế hoạch",DIRECTIVE:"Chỉ đạo",REPORT:"Báo cáo",INSPECTION:"Tiếp đoàn",INDICATOR_MEASUREMENT:"Chỉ số",MONITORING:"Giám sát",FINDING:"Finding",INCIDENT:"Sự cố",CAPA:"CAPA",RISK:"Rủi ro",FMEA:"FMEA",IMPROVEMENT_PROJECT:"Đề án cải tiến",IMPROVEMENT_PROPOSAL:"Đề xuất cải tiến",ASSESSMENT:"Tự đánh giá",EXTERNAL_ASSESSMENT:"Đánh giá ngoài",AUDIT:"Audit",SAFETY_ALERT:"Bài học/cảnh báo",FEEDBACK:"Phản ánh"};

function one(value:string|string[]|undefined){return Array.isArray(value)?value[0]:value}

export default async function AnalyticsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {user}=await requireUserContext();if(!user.permissions.includes("reports.analytics"))redirect("/dashboard?forbidden=1");
 const supabase=await createClient();const year=await getWorkYear();const params=await searchParams;
 const monthRaw=Number(one(params.month)||0);const month=Number.isInteger(monthRaw)&&monthRaw>=1&&monthRaw<=12?monthRaw:null;const departmentId=one(params.department)?.trim()||null;const status=(one(params.status)||"ALL").toUpperCase();
 const [{data,error},{data:departments}]=await Promise.all([
  supabase.from("records").select("record_type,lifecycle_status,owner_department_id,created_at,updated_at").eq("work_year",year),
  supabase.from("departments").select("id,name,short_name").eq("is_active",true).order("name"),
 ]);
 const allRows=(data??[]) as any[];const operational=allRows.filter(r=>!isOperationallyHiddenStatus(r.lifecycle_status));const rows=filterRegistryAnalyticsRows(operational,{month,departmentId,status});const cancelled=allRows.filter(r=>r.lifecycle_status==="CANCELLED").length;
 const byType=new Map<string,number>(),byDept=new Map<string,number>(),byStatus=new Map<string,number>();
 rows.forEach(r=>{byType.set(r.record_type,(byType.get(r.record_type)||0)+1);byStatus.set(r.lifecycle_status,(byStatus.get(r.lifecycle_status)||0)+1);if(r.owner_department_id)byDept.set(r.owner_department_id,(byDept.get(r.owner_department_id)||0)+1)});
 const depMap=new Map((departments??[]).map((d:any)=>[d.id,d.short_name||d.name]));
 const typeData=Array.from(byType.entries()).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([k,v],i)=>({label:TYPE_LABELS[k]||k,value:v,tone:(i<4?"brand":"blue") as any}));
 const deptData=Array.from(byDept.entries()).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([k,v],i)=>({label:String(depMap.get(k)||"Chưa rõ"),value:v,tone:(i<3?"brand":"blue") as any}));
 const active=rows.filter(r=>r.lifecycle_status==="ACTIVE").length,closed=rows.filter(r=>r.lifecycle_status==="CLOSED").length,unassigned=rows.filter(r=>!r.owner_department_id).length,closure=rows.length?Math.round(closed/rows.length*100):0;
 const statusSegments=Array.from(byStatus.entries()).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([label,value],i)=>({label:label.replaceAll("_"," "),value,tone:(i===0?"brand":i===1?"green":i===2?"blue":i===3?"amber":"slate") as any}));
 const months=registryMonthlyCounts(rows);
 const query=new URLSearchParams();if(month)query.set("month",String(month));if(departmentId)query.set("department",departmentId);if(status!=="ALL")query.set("status",status);const exportHref=`/api/analytics/registry/export${query.toString()?`?${query}`:""}`;
 const selectedDepartment=departmentId?String(depMap.get(departmentId)||"Khoa/Phòng đã chọn"):"Tất cả khoa/phòng";
 return <div className="page-stack tqm-analytics">
  <style>{TQM_CHART_CSS+`.tqm-analytics .filters{display:grid;grid-template-columns:150px minmax(220px,1fr) 190px auto auto;gap:9px;align-items:end;padding:14px 16px}.tqm-analytics .filters label{display:grid;gap:5px;font-size:10px;font-weight:800;color:#64748b;text-transform:uppercase}.tqm-analytics .filters select{min-height:40px}.tqm-analytics .filter-note{padding:0 16px 14px;font-size:11px;color:#64748b}.tqm-analytics .kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.tqm-analytics .kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:16px}.tqm-analytics .kpi span{font-size:10px;color:#718187;font-weight:800;text-transform:uppercase}.tqm-analytics .kpi strong{display:block;font-size:30px;margin-top:8px}.tqm-analytics .kpi small{font-size:10px;color:#7d8c92}.tqm-analytics .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.tqm-analytics .head{padding:16px 18px 4px}.tqm-analytics .head h2{margin:0;font-size:15px}.tqm-analytics .head p{margin:4px 0 0;color:#74838a;font-size:11px}@media(max-width:900px){.tqm-analytics .filters{grid-template-columns:1fr 1fr}.tqm-analytics .grid{grid-template-columns:1fr}.tqm-analytics .kpis{grid-template-columns:1fr 1fr}}@media(max-width:560px){.tqm-analytics .filters{grid-template-columns:1fr}.tqm-analytics .filters .button{width:100%;justify-content:center}}`}</style>
  <PageHeader eyebrow={`PHÂN TÍCH QLCL · ${year}`} title="Quality Intelligence" description="Bức tranh TQM toàn viện từ cùng Registry nghiệp vụ. KPI, biểu đồ và file Excel dùng chung một logic lọc."/>
  {error?<div className="alert error">Không tải được dữ liệu: {error.message}</div>:null}
  <section className="panel"><form className="filters" method="get"><label>Tháng<select name="month" defaultValue={month?String(month):""}><option value="">Tất cả tháng</option>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>Tháng {i+1}</option>)}</select></label><label>Khoa/Phòng<select name="department" defaultValue={departmentId||""}><option value="">Tất cả khoa/phòng</option>{(departments??[]).map((d:any)=><option key={d.id} value={d.id}>{d.short_name||d.name}</option>)}</select></label><label>Trạng thái<select name="status" defaultValue={status}><option value="ALL">Tất cả trạng thái</option><option value="ACTIVE">Đang hoạt động</option><option value="CLOSED">Đã đóng</option></select></label><button className="button primary" type="submit">Áp dụng</button><a className="button secondary" href={exportHref}>Xuất Excel (CSV)</a></form><div className="filter-note">Bộ lọc hiện tại: {month?`Tháng ${month}`:"Cả năm"} · {selectedDepartment} · {status==="ALL"?"Tất cả trạng thái":status}. Nhịp theo tháng được tính bằng <strong>ngày hồ sơ được ghi nhận (created_at)</strong>, không dùng ngày sửa gần nhất.</div></section>
  <section className="kpis"><article className="kpi"><span>Hồ sơ vận hành</span><strong>{rows.length}</strong><small>{cancelled} hồ sơ đã hủy trong năm được tách riêng</small></article><article className="kpi"><span>Đang hoạt động</span><strong>{active}</strong><small>Theo đúng bộ lọc hiện tại</small></article><article className="kpi"><span>Đã đóng</span><strong>{closure}%</strong><small>{closed} hồ sơ hoàn tất trong tập lọc</small></article><article className="kpi"><span>Thiếu đơn vị sở hữu</span><strong>{unassigned}</strong><small>Cần hoàn thiện trách nhiệm</small></article></section>
  <section className="grid"><article className="panel"><div className="head"><h2>Cơ cấu module chất lượng</h2><p>Phân bố hồ sơ trong đúng tập dữ liệu đang lọc.</p></div><TqmHorizontalBars rows={typeData}/></article><article className="panel"><div className="head"><h2>Trạng thái Registry</h2><p>Tỷ trọng vòng đời của tập hồ sơ đang lọc.</p></div><TqmDonut value={closure} label="Đã đóng" segments={statusSegments.length?statusSegments:[{label:"Chưa có dữ liệu",value:1,tone:"slate"}]}/></article></section>
  <section className="grid"><article className="panel"><div className="head"><h2>Khối lượng theo khoa/phòng</h2><p>Phân bố trách nhiệm theo đơn vị trong tập lọc.</p></div><TqmHorizontalBars rows={deptData}/></article><article className="panel"><div className="head"><h2>Nhịp phát sinh/tiếp nhận 12 tháng</h2><p>Số hồ sơ được tạo trong từng tháng theo created_at; không diễn giải đây là xu hướng kết quả chất lượng.</p></div><TqmTrend points={months} unit=""/></article></section>
  <section className="module-shortcuts-grid"><Link className="module-shortcut" href="/dashboard"><strong>Dashboard điều hành</strong><span>Quay về bức tranh TQM tổng hợp →</span></Link><Link className="module-shortcut" href="/tasks"><strong>Việc của tôi</strong><span>Đi tới công việc đang phụ trách →</span></Link><Link className="module-shortcut" href="/cancelled-records"><strong>Hồ sơ đã hủy</strong><span>Tra cứu dữ liệu ngoài vận hành →</span></Link></section>
 </div>
}
