import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

const SUPPORTED=new Set(["DIRECTIVE","REPORT","INSPECTION","INDICATOR_MEASUREMENT","FINDING","INCIDENT","CAPA","RISK","FMEA","IMPROVEMENT_PROPOSAL","IMPROVEMENT_PROJECT","ASSESSMENT","EXTERNAL_ASSESSMENT","AUDIT","SAFETY_ALERT","FEEDBACK"]);
const text=(v:unknown)=>v===null||v===undefined?null:String(v).trim()||null;
const num=(v:unknown)=>v===null||v===undefined||v===""?null:Number(v);
const bool=(v:unknown)=>v===true||v==="true"||v===1||v==="1";

async function context(recordType:string){
 const supabase=await createClient();const {data:{user},error}=await supabase.auth.getUser();if(error||!user)return {ok:false as const,response:NextResponse.json({error:"Chưa đăng nhập."},{status:401})};
 const {data:allowed}=await supabase.rpc("can_create_record_type",{p_record_type:recordType});
 let can=!!allowed;if(recordType==="INCIDENT"&&!can){const {data:r}=await supabase.rpc("has_permission",{p_permission_code:"incident.report"});can=!!r;}
 if(!can)return {ok:false as const,response:NextResponse.json({error:"Bạn không có quyền tạo hồ sơ này."},{status:403})};
 const admin=createAdminClient();const {data:caller}=await admin.from("profiles").select("organization_id,is_active,full_name,department_id").eq("user_id",user.id).maybeSingle();
 if(!caller?.organization_id||!caller.is_active)return {ok:false as const,response:NextResponse.json({error:"Tài khoản chưa gắn bệnh viện hoặc đã ngưng hoạt động."},{status:403})};
 return {ok:true as const,user,admin,caller};
}

export async function GET(request:Request){
 const url=new URL(request.url);const recordType=String(url.searchParams.get("type")||"").toUpperCase();const workYear=Number(url.searchParams.get("year")||new Date().getFullYear());
 if(!SUPPORTED.has(recordType))return NextResponse.json({error:"Loại hồ sơ chưa hỗ trợ."},{status:400});const ctx=await context(recordType);if(!ctx.ok)return ctx.response;const {admin,caller}=ctx;
 const [{data:departments},{data:profiles}]=await Promise.all([
  admin.from("departments").select("id,name,short_name").eq("organization_id",caller.organization_id).eq("is_active",true).order("name"),
  admin.from("profiles").select("user_id,full_name,email,department_id").eq("organization_id",caller.organization_id).eq("is_active",true).order("full_name")
 ]);
 let criteriaVersions:any[]=[];let indicatorAssignments:any[]=[];let fmeaModels:any[]=[];
 if(["ASSESSMENT","EXTERNAL_ASSESSMENT"].includes(recordType)){
  const {data:versions}=await admin.from("criteria_set_versions").select("id,criteria_set_id,version_no,effective_from,status").eq("status","PUBLISHED").order("published_at",{ascending:false});const setIds=Array.from(new Set((versions??[]).map((v:any)=>v.criteria_set_id)));
  const {data:sets}=setIds.length?await admin.from("criteria_sets").select("id,code,name").in("id",setIds):{data:[]};const map=new Map((sets??[]).map((s:any)=>[s.id,s]));criteriaVersions=(versions??[]).map((v:any)=>({id:v.id,label:`${map.get(v.criteria_set_id)?.code||""} ${map.get(v.criteria_set_id)?.name||"Bộ tiêu chí"} · v${v.version_no}`.trim()}));
 }
 if(recordType==="INDICATOR_MEASUREMENT"){
  const {data:assign}=await admin.from("indicator_assignments").select("id,indicator_version_id,department_id,frequency,local_target,status").eq("work_year",workYear).eq("status","ACTIVE");const versionIds=Array.from(new Set((assign??[]).map((a:any)=>a.indicator_version_id)));const {data:versions}=versionIds.length?await admin.from("indicator_definition_versions").select("id,indicator_definition_id,version_no,unit").in("id",versionIds):{data:[]};const defIds=Array.from(new Set((versions??[]).map((v:any)=>v.indicator_definition_id)));const {data:defs}=defIds.length?await admin.from("indicator_definitions").select("id,code,name").in("id",defIds):{data:[]};const vm=new Map((versions??[]).map((v:any)=>[v.id,v]));const dm=new Map((defs??[]).map((d:any)=>[d.id,d]));const depm=new Map((departments??[]).map((d:any)=>[d.id,d.short_name||d.name]));indicatorAssignments=(assign??[]).map((a:any)=>{const v=vm.get(a.indicator_version_id);const d=v?dm.get(v.indicator_definition_id):null;return {id:a.id,label:`${d?.code||""} ${d?.name||"Chỉ số"} · ${depm.get(a.department_id)||"Toàn viện"} · ${a.frequency||"chưa đặt tần suất"}`.trim()}});
 }
 if(recordType==="FMEA"){const {data}=await admin.from("fmea_scoring_model_versions").select("id,name,method,version_no").eq("status","PUBLISHED").order("effective_from",{ascending:false});fmeaModels=(data??[]).map((x:any)=>({id:x.id,label:`${x.name} · ${x.method} v${x.version_no}`}));}
 return NextResponse.json({departments:departments??[],profiles:profiles??[],criteria_versions:criteriaVersions,indicator_assignments:indicatorAssignments,fmea_models:fmeaModels});
}

export async function POST(request:Request){
 const body=await request.json();const recordType=String(body.record_type||"").toUpperCase();if(!SUPPORTED.has(recordType))return NextResponse.json({error:"Loại hồ sơ chưa hỗ trợ."},{status:400});const ctx=await context(recordType);if(!ctx.ok)return ctx.response;const {admin,caller,user}=ctx;
 const title=String(body.title||"").trim();const workYear=Number(body.work_year);const f=(body.fields||{}) as Record<string,unknown>;if(!title)return NextResponse.json({error:"Tên hồ sơ là bắt buộc."},{status:400});if(!Number.isInteger(workYear)||workYear<2000||workYear>2200)return NextResponse.json({error:"Năm làm việc không hợp lệ."},{status:400});
 let ownerDepartmentId=text(body.owner_department_id);let ownerUserId=text(body.owner_user_id);
 if(recordType==="INCIDENT")ownerDepartmentId=text(f.incident_location_department_id)||caller.department_id||null;
 if(recordType==="INDICATOR_MEASUREMENT"){
  const assignmentId=text(f.indicator_assignment_id);if(!assignmentId)return NextResponse.json({error:"Cần chọn chỉ số được phân công."},{status:400});const {data:a}=await admin.from("indicator_assignments").select("id,department_id,collector_user_id,work_year,status").eq("id",assignmentId).eq("work_year",workYear).maybeSingle();if(!a||a.status!=="ACTIVE")return NextResponse.json({error:"Phân công chỉ số không hợp lệ hoặc không còn hoạt động."},{status:400});ownerDepartmentId=a.department_id;ownerUserId=a.collector_user_id||user.id;
 }
 if(ownerDepartmentId){const {data:d}=await admin.from("departments").select("id,is_active").eq("id",ownerDepartmentId).eq("organization_id",caller.organization_id).maybeSingle();if(!d?.is_active)return NextResponse.json({error:"Khoa/phòng phụ trách không hợp lệ."},{status:400});}
 if(ownerUserId){const {data:p}=await admin.from("profiles").select("user_id,is_active").eq("user_id",ownerUserId).eq("organization_id",caller.organization_id).maybeSingle();if(!p?.is_active)return NextResponse.json({error:"Người phụ trách không hợp lệ."},{status:400});}
 const {data:code,error:codeError}=await admin.rpc("next_record_code",{p_org:caller.organization_id,p_record_type:recordType,p_work_year:workYear});if(codeError||!code)return NextResponse.json({error:codeError?.message||"Không cấp được mã hồ sơ."},{status:400});
 const {data:record,error:recordError}=await admin.from("records").insert({organization_id:caller.organization_id,record_type:recordType,record_code:code,title,work_year:workYear,owner_department_id:ownerDepartmentId,owner_user_id:ownerUserId,lifecycle_status:"ACTIVE",created_by:user.id}).select("id,record_code").single();if(recordError||!record)return NextResponse.json({error:recordError?.message||"Không tạo được hồ sơ Registry."},{status:400});
 const fail=async(message:string)=>{await admin.from("records").update({lifecycle_status:"ARCHIVED"}).eq("id",record.id);return NextResponse.json({error:message},{status:400});};
 let domain:any=null;let err:any=null;
 if(recordType==="DIRECTIVE")({data:domain,error:err}=await admin.from("external_directives").insert({record_id:record.id,source_authority:text(f.source_authority),directive_type:text(f.directive_type),received_date:text(f.received_date),implementation_due_date:text(f.implementation_due_date),report_due_date:text(f.report_due_date),summary:text(f.summary),requirements:text(f.requirements),lead_department_id:ownerDepartmentId,owner_user_id:ownerUserId,priority:text(f.priority)||"NORMAL",workflow_status:"OPEN"}).select("id").single());
 else if(recordType==="REPORT")({data:domain,error:err}=await admin.from("reporting_obligations").insert({record_id:record.id,report_type:text(f.report_type),reporting_period:text(f.reporting_period),reporting_period_start:text(f.reporting_period_start),reporting_period_end:text(f.reporting_period_end),data_cutoff_date:text(f.data_cutoff_date),due_date:text(f.due_date),preparing_department_id:ownerDepartmentId,preparer_user_id:ownerUserId,recipient_name:text(f.recipient_name),submission_method:text(f.submission_method),workflow_status:"NOT_DUE",notes:text(f.notes)}).select("id").single());
 else if(recordType==="INSPECTION"){if(!text(f.inspection_type)||!text(f.visit_date))return fail("Loại kiểm tra và ngày đoàn đến là bắt buộc.");({data:domain,error:err}=await admin.from("inspection_events").insert({record_id:record.id,inspection_type:text(f.inspection_type),authority:text(f.authority),visit_date:text(f.visit_date),lead_department_id:ownerDepartmentId,owner_user_id:ownerUserId,workflow_status:"PLANNING"}).select("id").single());}
 else if(recordType==="INDICATOR_MEASUREMENT"){const assignmentId=text(f.indicator_assignment_id),periodStart=text(f.period_start),periodEnd=text(f.period_end);if(!assignmentId||!periodStart||!periodEnd)return fail("Cần chọn chỉ số và kỳ đo.");if(periodEnd<periodStart)return fail("Ngày kết thúc kỳ đo không được trước ngày bắt đầu.");({data:domain,error:err}=await admin.from("indicator_measurements").insert({record_id:record.id,indicator_assignment_id:assignmentId,period_start:periodStart,period_end:periodEnd,numerator_value:num(f.numerator_value),denominator_value:num(f.denominator_value),raw_value:num(f.raw_value),source_mode:"MANUAL",workflow_status:"DRAFT",entered_by:user.id}).select("id").single());}
 else if(recordType==="FINDING"){if(!text(f.description))return fail("Mô tả Finding là bắt buộc.");({data:domain,error:err}=await admin.from("findings").insert({record_id:record.id,finding_type:text(f.finding_type),description:text(f.description),severity:text(f.severity),lead_department_id:ownerDepartmentId,owner_user_id:ownerUserId,identified_at:text(f.identified_at)||new Date().toISOString(),due_date:text(f.due_date),immediate_action:text(f.immediate_action),workflow_status:"OPEN"}).select("id").single());}
 else if(recordType==="INCIDENT"){if(!text(f.initial_description))return fail("Mô tả sự cố là bắt buộc.");const now=new Date().toISOString();const onBehalfDepartmentId=text(f.on_behalf_department_id);const reporterDepartmentId=onBehalfDepartmentId||caller.department_id||null;({data:domain,error:err}=await admin.from("incidents").insert({record_id:record.id,occurred_at:text(f.occurred_at),detected_at:text(f.detected_at),reported_at:now,incident_location_department_id:text(f.incident_location_department_id),incident_location_text:text(f.incident_location_text),summary:text(f.initial_description),workflow_status:"REPORTED",lead_department_id:ownerDepartmentId,case_owner_user_id:null}).select("id").single());if(domain&&!err){const dept=ownerDepartmentId?(await admin.from("departments").select("name").eq("id",ownerDepartmentId).maybeSingle()).data:null;const reporterDept=reporterDepartmentId?(await admin.from("departments").select("name").eq("id",reporterDepartmentId).maybeSingle()).data:null;const {error:reportError}=await admin.from("incident_reports").insert({incident_id:domain.id,report_type:text(f.report_type)||"VOLUNTARY",reporter_user_id:user.id,reporter_name_snapshot:onBehalfDepartmentId?null:(caller.full_name||null),reporter_department_id:reporterDepartmentId,reporter_department_name_snapshot:reporterDept?.name||dept?.name||null,reporter_identity_confidential:bool(f.reporter_identity_confidential),incident_location_department_id:text(f.incident_location_department_id),occurred_at:text(f.occurred_at),detected_at:text(f.detected_at),initial_description:text(f.initial_description),initial_harm_assessment:text(f.initial_harm_assessment),initial_response_description:text(f.initial_response_description),patient_name:text(f.patient_name),patient_code:text(f.patient_code),mandatory_report_flag:text(f.report_type)==="MANDATORY"});if(reportError)err=reportError;}}
 else if(recordType==="CAPA"){if(!text(f.problem_statement))return fail("Vấn đề cần CAPA là bắt buộc.");({data:domain,error:err}=await admin.from("capas").insert({record_id:record.id,problem_statement:text(f.problem_statement),priority:text(f.priority)||"NORMAL",immediate_correction:text(f.immediate_correction),lead_department_id:ownerDepartmentId,owner_user_id:ownerUserId,workflow_status:"DRAFT",approval_required:bool(f.approval_required),effectiveness_due_date:text(f.effectiveness_due_date)}).select("id").single());}
 else if(recordType==="RISK"){if(!text(f.risk_event))return fail("Sự kiện rủi ro là bắt buộc.");({data:domain,error:err}=await admin.from("risks").insert({record_id:record.id,identified_year:workYear,risk_event:text(f.risk_event),cause_summary:text(f.cause_summary),potential_consequence:text(f.potential_consequence),process_name:text(f.process_name),location_department_id:ownerDepartmentId,owner_department_id:ownerDepartmentId,owner_user_id:ownerUserId,workflow_status:"IDENTIFIED",next_review_date:text(f.next_review_date),review_frequency:text(f.review_frequency)}).select("id").single());}
 else if(recordType==="FMEA"){const method=text(f.method);if(!method||!["FMEA","HFMEA"].includes(method))return fail("Cần chọn FMEA hoặc HFMEA.");({data:domain,error:err}=await admin.from("fmea_studies").insert({record_id:record.id,method,title,process_name:text(f.process_name),scope:text(f.scope),work_year:workYear,lead_department_id:ownerDepartmentId,lead_user_id:ownerUserId,start_date:text(f.start_date),target_completion_date:text(f.target_completion_date),scoring_model_version_id:text(f.scoring_model_version_id),workflow_status:"DRAFT"}).select("id").single());}
 else if(recordType==="IMPROVEMENT_PROPOSAL"){if(!text(f.problem_description))return fail("Vấn đề/thực trạng là bắt buộc.");({data:domain,error:err}=await admin.from("improvement_proposals").insert({record_id:record.id,work_year:workYear,title,problem_description:text(f.problem_description),reason_for_improvement:text(f.reason_for_improvement),source_type:text(f.source_type),proposing_department_id:ownerDepartmentId,proposer_user_id:ownerUserId||user.id,existing_data_summary:text(f.existing_data_summary),proposed_scope:text(f.proposed_scope),workflow_status:"DRAFT"}).select("id").single());}
 else if(recordType==="IMPROVEMENT_PROJECT")({data:domain,error:err}=await admin.from("improvement_projects").insert({record_id:record.id,work_year:workYear,title,problem_statement:text(f.problem_statement),lead_department_id:ownerDepartmentId,project_leader_user_id:ownerUserId,start_date:text(f.start_date),target_end_date:text(f.target_end_date),scope_description:text(f.scope_description),workflow_status:"DRAFT"}).select("id").single());
 else if(recordType==="ASSESSMENT"){const version=text(f.criteria_version_id),roundType=text(f.round_type);if(!version||!roundType)return fail("Bộ tiêu chí và loại đợt là bắt buộc.");const {data:v}=await admin.from("criteria_set_versions").select("id,status").eq("id",version).maybeSingle();if(v?.status!=="PUBLISHED")return fail("Chỉ được tạo đợt từ bộ tiêu chí đã PUBLISHED.");({data:domain,error:err}=await admin.from("assessment_rounds").insert({record_id:record.id,criteria_version_id:version,work_year:workYear,round_type:roundType,start_date:text(f.start_date),submission_deadline:text(f.submission_deadline),review_deadline:text(f.review_deadline),finalization_date:text(f.finalization_date),workflow_status:"DRAFT"}).select("id").single());if(domain&&!err){const {data:criteria}=await admin.from("criteria_items").select("id").eq("criteria_version_id",version);if(criteria?.length)await admin.from("assessment_round_criteria").insert(criteria.map((c:any)=>({assessment_round_id:domain.id,criterion_id:c.id,is_required:true})));}}
 else if(recordType==="EXTERNAL_ASSESSMENT"){if(!text(f.authority))return fail("Cơ quan/đoàn đánh giá là bắt buộc.");({data:domain,error:err}=await admin.from("external_assessment_events").insert({record_id:record.id,authority:text(f.authority),assessment_date:text(f.assessment_date),criteria_version_id:text(f.criteria_version_id),notes:text(f.notes)}).select("id").single());}
 else if(recordType==="AUDIT"){if(!text(f.audit_type))return fail("Loại Audit / Tracer là bắt buộc.");({data:domain,error:err}=await admin.from("audits").insert({record_id:record.id,audit_type:text(f.audit_type),work_year:workYear,title,objective:text(f.objective),start_date:text(f.start_date),end_date:text(f.end_date),lead_auditor_id:ownerUserId,workflow_status:"DRAFT"}).select("id").single());}
 else if(recordType==="SAFETY_ALERT")({data:domain,error:err}=await admin.from("safety_alerts").insert({record_id:record.id,title,summary:text(f.summary),lesson:text(f.lesson),recommendation:text(f.recommendation),expires_at:text(f.expires_at),status:"DRAFT"}).select("id").single());
 else if(recordType==="FEEDBACK"){if(!text(f.description))return fail("Nội dung phản ánh là bắt buộc.");({data:domain,error:err}=await admin.from("feedback_records").insert({record_id:record.id,feedback_type:text(f.feedback_type),received_at:text(f.received_at)||new Date().toISOString(),source_channel:text(f.source_channel),subject:text(f.subject),description:text(f.description),related_department_id:ownerDepartmentId,owner_user_id:ownerUserId,response_due_at:text(f.response_due_at),workflow_status:"RECEIVED"}).select("id").single());}
 if(err||!domain)return fail(err?.message||"Không tạo được dữ liệu nghiệp vụ.");
 return NextResponse.json({ok:true,record_id:record.id,record_code:record.record_code,domain_id:domain.id});
}
