import Link from "next/link";
import { redirect } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
import { TQM_CHART_CSS, TqmDonut, TqmHorizontalBars, TqmTrend } from "@/components/tqm-charts";
import { hasAnyPermission, requireUserContext } from "@/lib/auth";
import { formatDate, formatDateTime } from "@/lib/format";
import { createClient } from "@/lib/supabase/server";

export default async function EvidencePage(){
 const {user}=await requireUserContext();if(!hasAnyPermission(user,["evidence.upload","evidence.review","criteria.view"]))redirect("/dashboard?forbidden=1");const supabase=await createClient();
 const [recentRes,totalRes,validCountRes,unverifiedCountRes]=await Promise.all([
  supabase.from("evidence").select("id,title,evidence_type,document_number,document_date,validity_status,uploaded_at,owner_department_id,original_file_name,file_size").order("uploaded_at",{ascending:false}).limit(300),
  supabase.from("evidence").select("id",{count:"exact",head:true}),
  supabase.from("evidence").select("id",{count:"exact",head:true}).eq("validity_status","VALID"),
  supabase.from("evidence").select("id",{count:"exact",head:true}).neq("validity_status","VALID"),
 ]);
 const rows=(recentRes.data??[]) as any[];const total=totalRes.count??0,valid=validCountRes.count??0,unverified=unverifiedCountRes.count??0,validPct=total?Math.round(valid/total*100):0;
 const departmentIds=Array.from(new Set(rows.map(r=>r.owner_department_id).filter(Boolean)));const deps=departmentIds.length?await supabase.from("departments").select("id,name,short_name").in("id",departmentIds):{data:[],error:null};const depMap=new Map((deps.data??[]).map((r:any)=>[r.id,r.short_name||r.name]));
 const sampleValid=rows.filter(r=>r.validity_status==="VALID").length,sampleOther=Math.max(0,rows.length-sampleValid),sampleValidPct=rows.length?Math.round(sampleValid/rows.length*100):0;
 const typeMap=new Map<string,number>();const depAgg=new Map<string,number>();const months=Array.from({length:12},(_,i)=>({label:`T${i+1}`,value:0}));rows.forEach(r=>{const t=r.evidence_type||"Khác";typeMap.set(t,(typeMap.get(t)||0)+1);const d=String(depMap.get(r.owner_department_id)||"Chưa xác định");depAgg.set(d,(depAgg.get(d)||0)+1);const x=new Date(r.uploaded_at);if(!Number.isNaN(x.getTime()))months[x.getMonth()].value++});
 const depBars=Array.from(depAgg.entries()).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value],i)=>({label,value,tone:(i<3?"brand":"blue") as any}));const typeBars=Array.from(typeMap.entries()).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([label,value],i)=>({label,value,tone:(i<3?"green":"blue") as any}));
 const firstError=[recentRes,totalRes,validCountRes,unverifiedCountRes,deps].find((x:any)=>x.error)?.error;
 return <div className="page-stack evidence-tqm">
  <style>{TQM_CHART_CSS+`.evidence-tqm .kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.evidence-tqm .kpi{background:#fff;border:1px solid #e1e9ec;border-radius:17px;padding:16px}.evidence-tqm .kpi span{font-size:10px;color:#718187;font-weight:800;text-transform:uppercase}.evidence-tqm .kpi strong{display:block;font-size:30px;margin-top:8px}.evidence-tqm .kpi small{font-size:10px;color:#7d8c92}.evidence-tqm .grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.evidence-tqm .head{padding:16px 18px 4px}.evidence-tqm .head h2{margin:0;font-size:15px}.evidence-tqm .head p{margin:4px 0 0;color:#74838a;font-size:11px}@media(max-width:900px){.evidence-tqm .grid{grid-template-columns:1fr}.evidence-tqm .kpis{grid-template-columns:1fr 1fr}}`}</style>
  <PageHeader eyebrow="TÀI LIỆU & MINH CHỨNG" title="Kho minh chứng" description="KPI sử dụng số đếm toàn kho theo phạm vi RLS của người dùng. Biểu đồ cơ cấu và danh sách phía dưới sử dụng tối đa 300 bản gần nhất để giữ hiệu năng."/>
  {firstError?<div className="alert error">Không tải được đầy đủ kho minh chứng: {firstError.message}</div>:null}
  <section className="kpis"><article className="kpi"><span>Tổng minh chứng</span><strong>{total}</strong><small>Toàn bộ theo phạm vi được phép xem</small></article><article className="kpi"><span>Hợp lệ toàn kho</span><strong>{validPct}%</strong><small>{valid}/{total || 0} minh chứng</small></article><article className="kpi"><span>Chưa xác nhận hợp lệ</span><strong>{unverified}</strong><small>Các trạng thái ngoài VALID</small></article><article className="kpi"><span>Mẫu đang hiển thị</span><strong>{rows.length}</strong><small>Tối đa 300 bản gần nhất</small></article></section>
  <section className="grid"><article className="panel"><div className="head"><h2>Hiệu lực của 300 bản gần nhất</h2><p>Tỷ lệ mẫu gần nhất: {sampleValidPct}% hợp lệ; dùng để quan sát cơ cấu gần đây, trong khi KPI phía trên là toàn kho.</p></div><TqmDonut value={sampleValidPct} label="Hợp lệ gần đây" segments={[{label:"Hợp lệ",value:sampleValid,tone:"green"},{label:"Chưa xác nhận hợp lệ",value:sampleOther,tone:"amber"}]}/></article><article className="panel"><div className="head"><h2>Minh chứng theo khoa/phòng</h2><p>Phân bố trong tối đa 300 bản gần nhất; dùng để định hướng drill-down, không phải xếp hạng toàn viện.</p></div><TqmHorizontalBars rows={depBars}/></article></section>
  <section className="grid"><article className="panel"><div className="head"><h2>Cơ cấu loại minh chứng gần đây</h2><p>Top nhóm tài liệu trong tối đa 300 bản gần nhất.</p></div><TqmHorizontalBars rows={typeBars}/></article><article className="panel"><div className="head"><h2>Nhịp tải của tập minh chứng gần nhất</h2><p>Phân bố thời điểm tải lên của tối đa 300 bản đang hiển thị.</p></div><TqmTrend points={months} unit=""/></article></section>
  <section className="module-shortcuts-grid"><Link className="module-shortcut" href="/tasks"><strong>Việc của tôi</strong><span>Nộp minh chứng từ Action →</span></Link><Link className="module-shortcut" href="/assessments"><strong>Tự đánh giá</strong><span>Dùng minh chứng cho tiêu chí →</span></Link><Link className="module-shortcut" href="/audits"><strong>Audit / Tracer</strong><span>Tra cứu bằng chứng theo đợt →</span></Link></section>
  <section className="panel module-list-panel"><div className="panel-title"><div><h2>300 minh chứng gần nhất</h2><p>File mở qua API bảo vệ quyền truy cập.</p></div></div><div className="table-wrap"><table><thead><tr><th>Minh chứng</th><th>Đơn vị</th><th>Ngày / số văn bản</th><th>Trạng thái</th><th>Tải lên</th><th></th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><strong>{r.title}</strong><span className="subline">{r.original_file_name||r.evidence_type||"—"}{r.file_size?` · ${Math.max(1,Math.round(r.file_size/1024))} KB`:""}</span></td><td>{depMap.get(r.owner_department_id)||"—"}</td><td><strong>{formatDate(r.document_date)}</strong><span className="subline">{r.document_number||"—"}</span></td><td><StatusBadge status={r.validity_status}/></td><td>{formatDateTime(r.uploaded_at)}</td><td><a className="button tertiary small" href={`/api/evidence/${r.id}/download`} target="_blank" rel="noreferrer">Mở file</a></td></tr>)}{!rows.length?<tr><td colSpan={6}><div className="empty-state">Chưa có minh chứng.</div></td></tr>:null}</tbody></table></div></section>
 </div>
}
